export const LEGACY_DATA_SCHEMA_VERSION = 1;
export const SECOND_PREVIOUS_DATA_SCHEMA_VERSION = 2;
export const PREVIOUS_DATA_SCHEMA_VERSION = 3;
export const IMMEDIATE_PREVIOUS_DATA_SCHEMA_VERSION = 4;
export const VALUE_EVIDENCE_DATA_SCHEMA_VERSION = 5;
export const DATA_SCHEMA_VERSION = 6;
