import assert from "node:assert/strict";
import test from "node:test";
import {createEmptySnapshot} from "../../src/core/domain/model.ts";
import {ACTIVE_CLASSROOM_SETTING_ID,ACTIVE_CLASSROOM_SETTING_TYPE} from "../../src/core/domain/classroom.ts";
import {previewDutyRequest,dutyDefaultConfig,dutyCalendarId} from "../../src/features/class-duty-schedule/class-duty-model.ts";
import {CLASS_DUTY_SETTING_TYPE} from "../../src/core/domain/class-duty-schedule.ts";
const id=n=>`11111111-1111-4111-8111-${String(n).padStart(12,"0")}`,base={createdAt:"2026-09-01T08:00:00.000Z",updatedAt:"2026-09-01T08:00:00.000Z",civilDate:"2026-09-01",schemaVersion:1,deletedAt:null};
function data(count=20){const d=createEmptySnapshot();d.academicYears=[{...base,id:id(1),name:"Kurgu yıl",startDate:"2026-09-01",endDate:"2027-06-30",status:"active"}];d.classrooms=[{...base,id:id(2),academicYearId:id(1),name:"Kurgu sınıf"}];d.settings=[{...base,id:ACTIVE_CLASSROOM_SETTING_ID,settingType:ACTIVE_CLASSROOM_SETTING_TYPE,academicYearId:id(1),classroomId:id(2)}];d.students=Array.from({length:count},(_,i)=>({...base,id:id(i+10),academicYearId:id(1),classroomId:id(2),displayName:`Kurgu Çocuk ${i+1}`,active:true}));return d;}
const preview=(d,config)=>previewDutyRequest(d,{kind:"create",scheduleId:id(3),operationId:id(4),config},new Date("2026-09-01T09:00:00Z"));
test("Meyve görevleri tekrar açıldığında aynı dağılım, sınırlı kapasitede açık kalan çocuklar",()=>{const d=data(),c=dutyDefaultConfig(d,"fruit","2026-09");c.weekdays=[1,3];const a=preview(d,c),b=preview(d,c);assert.deepEqual(a.rows,b.rows);assert.equal(a.rows.length,8);assert.equal(a.unassignedStudentIds.length,12);assert.equal(new Set(a.rows.map(r=>r.studentId)).size,8);assert.match(dutyCalendarId("f1111111-1111-4111-8111-202609140001"),/^[0-9a-f]{8}-/u);c.capacity=3;const full=preview(d,c);assert.equal(full.unassignedStudentIds.length,0);const counts=d.students.map(s=>full.rows.filter(r=>r.studentId===s.id).length);assert.ok(Math.max(...counts)-Math.min(...counts)<=1);});
test("Tatil/kapalı gün ve sonradan katılan çocuk için gerçek tarih üyeliği uygulanır",()=>{const d=data(2);d.calendarEntries=[{...base,id:id(8),academicYearId:id(1),classroomId:id(2),entryType:"no_school",title:"Kurgu okul kapalı",startDate:"2026-09-07",endDate:"2026-09-09",status:"planned"}];d.students[1].enrollments=[{id:id(9),academicYearId:id(1),classroomId:id(2),startedOn:"2026-09-15",status:"active",schemaVersion:1}];const c=dutyDefaultConfig(d,"fruit","2026-09");c.weekdays=[1,2,3,4,5];const p=preview(d,c);assert.equal(p.rows.some(r=>r.startOn>="2026-09-07"&&r.startOn<="2026-09-09"),false);assert.equal(p.rows.some(r=>r.studentId===d.students[1].id&&r.startOn<"2026-09-15"),false);});
test("Haftanın çocuğunda tüm uygun çocuklar sıra almadan tekrar yok, haftalar kesişmez",()=>{const d=data(5),c=dutyDefaultConfig(d,"child-of-week","2026-09");c.avoidFruitWeek=false;const p=preview(d,c);assert.equal(new Set(p.rows.map(r=>r.studentId)).size,p.rows.length);assert.equal(p.rows.length,4);assert.equal(p.unassignedStudentIds.length,1);for(const r of p.rows)assert.ok(r.startOn<=r.endOn);});
function keep(d,p,scheduleId=id(3)){const record={...base,id:id(99),settingType:CLASS_DUTY_SETTING_TYPE,academicYearId:id(1),classroomId:id(2),studentId:null,workflow:{kind:'schedule-revision',scheduleId,operationId:id(4),operationHash:'a'.repeat(64),revision:1,previousRevisionId:null,effectiveOn:p.effectiveOn,config:p.config,rows:p.rows}};d.settings.push(record);return record;}
test('Yeni ay önce sıra gelmeyen çocukları alır; geçmiş ayın dağılımı değişmez',()=>{const d=data(12),september=preview(d,dutyDefaultConfig(d,'fruit','2026-09'));keep(d,september);const before=JSON.stringify(d.settings),oct=previewDutyRequest(d,{kind:'create',scheduleId:id(5),operationId:id(6),config:dutyDefaultConfig(d,'fruit','2026-10')},new Date('2026-09-01T09:00:00Z'));assert.ok(oct.rows.every(r=>!september.rows.some(s=>s.studentId===r.studentId)));assert.equal(JSON.stringify(d.settings),before);});
test('Karıştırma bugün/geçmiş/sabit görevleri korur, yeni yıl sınırı aşılmaz',()=>{const d=data(5),p=preview(d,dutyDefaultConfig(d,'fruit','2026-09'));p.rows.at(-1).locked=true;keep(d,p);const q=previewDutyRequest(d,{kind:'redistribute',scheduleId:id(3),operationId:id(7),config:{...p.config,seed:72}},new Date('2026-09-16T09:00:00Z'));for(const row of p.rows.filter(r=>r.startOn<='2026-09-16'||r.locked))assert.deepEqual(q.rows.find(r=>r.id===row.id),row);assert.throws(()=>preview(d,{...p.config,endOn:'2027-07-01'}),/dönem/u);});
test('Haftanın çocuğu aynı çocuğun meyve haftasına otomatik atanmaz',()=>{const d=data(8),fruit=preview(d,dutyDefaultConfig(d,'fruit','2026-09'));keep(d,fruit);const config=dutyDefaultConfig(d,'child-of-week','2026-09'),week=previewDutyRequest(d,{kind:'create',scheduleId:id(5),operationId:id(6),config},new Date('2026-09-01T09:00:00Z'));for(const row of week.rows)assert.ok(!fruit.rows.some(r=>r.studentId===row.studentId&&r.startOn>=row.startOn&&r.startOn<=row.endOn));});
