import test from "node:test";
import assert from "node:assert/strict";
import { createPdfPrinter, PDF_PRINT_CLEANUP_DELAY_MS } from "../../src/features/documents/print-pdf-artifact.ts";
const artifact = () => ({ blob: new Blob(["%PDF-kurgu-same-source"], { type: "application/pdf" }), url: "blob:preview-owned", fileName: "kurgu.pdf", byteLength: 22, dispose() { throw new Error("Printer must not dispose the preview artifact"); } });
function bench(options = {}) {
  const state = { loaded: null, rendered: [], added: [], printed: 0, pdfDestroyed: 0, stageDisposed: 0, timerCleared: 0, listenerRemoved: 0, afterPrint: null, fallback: null, guardCalls: 0, current: true };
  const pdf = { pageCount: options.pageCount ?? 3, async renderPage(number) { state.rendered.push(number); if (options.renderError === number) throw new Error("Kurgu render hatası"); return { widthPoints: number === 2 ? 419.527559 : 595.275591, heightPoints: number === 2 ? 595.275591 : 841.889764, blob: new Blob([`Kurgu sayfa ${number}`], { type: "image/png" }), links: options.links?.[number - 1] }; }, async destroy() { state.pdfDestroyed += 1; } };
  const stage = { async addPage(page, number) { state.added.push({ ...page, number }); if (options.changeOnLastPage && number === pdf.pageCount) state.current = false; if (options.imageError) throw new Error("Kurgu resim hatası"); }, async ready() { if (options.changeOnReady) state.current = false; }, onAfterPrint(callback) { state.afterPrint = callback; return () => { state.listenerRemoved += 1; }; }, print() { state.printed += 1; if (options.nativeError) throw new Error("Kurgu yazdırma hatası"); if (options.syncAfterPrint) state.afterPrint(); }, dispose() { state.stageDisposed += 1; } };
  const environment = { async loadPdf(bytes) { state.loaded = bytes; if (options.parseError) throw new Error("PDF yazdırma için okunamadı."); return pdf; }, async createStage() { if (options.stageError) throw new Error("Kurgu iframe hatası"); return stage; }, setTimer(callback, delay) { assert.equal(delay, PDF_PRINT_CLEANUP_DELAY_MS); state.fallback = callback; return 71; }, clearTimer(timer) { assert.equal(timer, 71); state.timerCleared += 1; } };
  return { state, print: createPdfPrinter(environment), guard: async () => { state.guardCalls += 1; if (!state.current) throw new Error("Yazdırma hazırlığı iptal edildi; kaynak değişti."); } };
}
test("önizlemenin aynı byte'ları ile bütün sayfalar sırayla hazırlanır ve print bir kez çağrılır", async () => { const b = bench(), source = artifact(); await b.print(source, b.guard); assert.deepEqual(b.state.loaded, new Uint8Array(await source.blob.arrayBuffer())); assert.deepEqual(b.state.rendered, [1, 2, 3]); assert.deepEqual(b.state.added.map(p => p.number), [1, 2, 3]); assert.equal(b.state.added[1].widthPoints, 419.527559); assert.equal(b.state.printed, 1); assert.equal(b.state.pdfDestroyed, 1); assert.equal(b.state.stageDisposed, 0); assert.ok(b.state.guardCalls >= 8); b.state.afterPrint(); assert.equal(b.state.stageDisposed, 1); assert.equal(b.state.timerCleared, 1); assert.equal(b.state.listenerRemoved, 1); });
test("son render sonrası kaynak değişimi bütün işi temizler ve yazdırmaz", async () => { const b = bench({ changeOnLastPage: true }); await assert.rejects(b.print(artifact(), b.guard), /kaynak değişti/u); assert.equal(b.state.printed, 0); assert.equal(b.state.pdfDestroyed, 1); assert.equal(b.state.stageDisposed, 1); });
test("printten hemen önce canlı izin/kapalı dialog denetimi başarısızsa yazdırılmaz", async () => { const b = bench({ changeOnReady: true }); await assert.rejects(b.print(artifact(), b.guard), /iptal edildi/u); assert.equal(b.state.printed, 0); assert.equal(b.state.pdfDestroyed, 1); assert.equal(b.state.stageDisposed, 1); assert.equal(b.state.timerCleared, 1); });
test("PDF ayrıştırma başarısızsa iframe veya print kaynağı oluşturulmaz", async () => { const b = bench({ parseError: true }); await assert.rejects(b.print(artifact(), b.guard), /PDF yazdırma/u); assert.equal(b.state.printed, 0); assert.equal(b.state.stageDisposed, 0); assert.equal(b.state.fallback, null); });
test("render/iframe/resim hataları yüklenen PDF'yi ve oluşturulan sahneyi bırakmaz", async () => { for (const options of [{ renderError: 2 }, { stageError: true }, { imageError: true }]) { const b = bench(options); await assert.rejects(b.print(artifact(), b.guard)); assert.equal(b.state.printed, 0); assert.equal(b.state.pdfDestroyed, 1); assert.equal(b.state.stageDisposed, options.stageError ? 0 : 1); } });
test("afterprint gelmezse sınırlı fallback kaynakları bir kez temizler", async () => { const b = bench(); await b.print(artifact(), b.guard); b.state.fallback(); b.state.afterPrint(); b.state.fallback(); assert.equal(b.state.stageDisposed, 1); assert.equal(b.state.timerCleared, 1); assert.equal(b.state.listenerRemoved, 1); });
test("eşzamanlı afterprint veya native print hatası kaynak sızıntısı yaratmaz", async () => { const success = bench({ syncAfterPrint: true }); await success.print(artifact(), success.guard); assert.equal(success.state.stageDisposed, 1); const failed = bench({ nativeError: true }); await assert.rejects(failed.print(artifact(), failed.guard), /yazdırma/u); assert.equal(failed.state.stageDisposed, 1); assert.equal(failed.state.pdfDestroyed, 1); });
test("başlangıçta iptal edilmiş iş PDF bile yüklemez", async () => { const b = bench(); b.state.current = false; await assert.rejects(b.print(artifact(), b.guard), /iptal edildi/u); assert.equal(b.state.loaded, null); assert.equal(b.state.stageDisposed, 0); assert.equal(b.state.printed, 0); });
test("URI bağlantıları ilgili sayfayla birlikte sahneye değişmeden aktarılır", async () => { const links = [[{ url: "https://example.test/bir", x: 10, y: 20, width: 30, height: 12 }], undefined, [{ url: "http://example.test/uc", x: 70, y: 80, width: 90, height: 14 }]]; const b = bench({ links }); await b.print(artifact(), b.guard); assert.deepEqual(b.state.added.map(page => page.links), links); b.state.afterPrint(); });
