import { useEffect, useRef, useState } from "react";
import { KeyboardInput } from "../../mobile";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { familyResponseBoardModel } from "./family-response-board-model.ts";
import { applyFamilyResponse, FAMILY_RESPONSE_CHANGED, type FamilyResponseRequest } from "./family-response-board-service.ts";
import { HOME_GAME_CARDS_CHANGED } from "../home-game-cards/home-game-card-service.ts";
import "./family-response-board.css";

export interface FamilyResponseBoardPanelProps {store:LocalDataStore;refreshKey?:string|number;disabled?:boolean;onChanged?:()=>void;onOpenPlan?:(planId:string)=>void;onOpenMeeting?:(appointmentId:string)=>void;onPrepareCard?:()=>void;onOpenStudent?:(studentId:string)=>void;}
export function FamilyResponseBoardPanel({store,refreshKey,disabled=false,onChanged,onOpenPlan,onOpenMeeting,onPrepareCard,onOpenStudent}:FamilyResponseBoardPanelProps){
  const [model,setModel]=useState<ReturnType<typeof familyResponseBoardModel>|null>(null),[day,setDay]=useState(""),[feedbackId,setFeedbackId]=useState(""),[contactId,setContactId]=useState(""),[slot,setSlot]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const guard=useRef(false),generation=useRef(0),sequence=useRef(0),reload=useRef<()=>void>(()=>{});
  useEffect(()=>{const version=++generation.current;let timer:ReturnType<typeof setTimeout>|undefined;const read=()=>{const seq=++sequence.current;setLoading(true);clearTimeout(timer);timer=setTimeout(()=>{store.readSnapshot().then(snapshot=>{if(version!==generation.current||seq!==sequence.current)return;setModel(familyResponseBoardModel(snapshot,day||undefined));setLoading(false);}).catch(()=>{if(version===generation.current&&seq===sequence.current){setLoading(false);setMessage("Aile dönüşleri okunamadı. Yenileyip tekrar deneyin.");}});},50);};reload.current=read;read();window.addEventListener(FAMILY_RESPONSE_CHANGED,read);window.addEventListener(HOME_GAME_CARDS_CHANGED,read);return()=>{generation.current++;clearTimeout(timer);window.removeEventListener(FAMILY_RESPONSE_CHANGED,read);window.removeEventListener(HOME_GAME_CARDS_CHANGED,read);};},[store,day,refreshKey]);
  const row=model?.rows.find(r=>r.feedback.some(f=>f.record.id===feedbackId)),response=row?.feedback.find(f=>f.record.id===feedbackId);
  const locked=disabled||busy||loading;
  async function apply(request:FamilyResponseRequest){if(!model||locked||guard.current)return;guard.current=true;setBusy(true);setMessage("");try{const saved=await applyFamilyResponse(store,{request,expectedFingerprint:model.fingerprint});setMessage(saved.workflow.kind==="response-action"&&saved.workflow.action==="plan"?"Kaynak etkinlik seçili çocuk için günlük plana yerleştirildi.":"Gerçek aile yanıtı veli görüşmesinin gündemine eklendi.");reload.current();try{onChanged?.();}catch{setMessage("Adım kaydedildi. Kayıtlı sonucu açabilir veya panoyu yenileyebilirsiniz.");}}catch(error){setMessage(error instanceof Error?error.message:"Aile dönüş adımı kaydedilemedi.");reload.current();}finally{guard.current=false;setBusy(false);}}
  return <section className="family-response-board" aria-label="Aile dönüş panosu"><h3>Aile dönüş panosu</h3><p>Hazırladığınız kartlar ve aileden gelen gerçek yanıtlar. Yanıtı seçin; etkinliği yeniden planlayın veya veli görüşmesinin gündemine ekleyin.</p>
    {loading&&!model&&<p role="status">Aile dönüşleri okunuyor…</p>}
    {model&&!model.rows.length&&<div><p>Henüz hazırlanmış aile oyun kartı yok.</p><button type="button" disabled={disabled||!onPrepareCard} onClick={onPrepareCard}>Aile oyun kartı hazırla</button></div>}
    {model?.rows.map(r=><article key={r.card.id}><h4>{r.name} · {r.card.workflow.kind==="prepared"?r.card.workflow.title:""}</h4><p>Kart hazırlandı: {r.card.civilDate}</p>{!r.feedback.length&&<p>Aile yanıtı henüz kaydedilmedi.</p>}{r.feedback.map(f=><div key={f.record.id}>{f.record.workflow.kind==="feedback"&&<blockquote>{f.record.workflow.receivedOn} · {f.record.workflow.source==="written"?"Yazılı yanıt":"Sözlü yanıt"}<br/>{f.record.workflow.text}</blockquote>}<button type="button" disabled={locked||!!r.reason} aria-pressed={feedbackId===f.record.id} onClick={()=>{setFeedbackId(f.record.id);setContactId("");setSlot("");setMessage("");}}>Bu aile yanıtıyla ilerle</button>{f.actions.map(a=>a.workflow.kind==="response-action"?<p key={a.id}>{a.workflow.targetDate} · {a.workflow.action==="plan"?"Etkinlik yeniden planlandı":"Görüşme gündemine eklendi"}<button type="button" onClick={()=>{if(a.workflow.kind!=="response-action")return;if(a.workflow.planId)onOpenPlan?.(a.workflow.planId);if(a.workflow.appointmentId)onOpenMeeting?.(a.workflow.appointmentId);}}>{a.workflow.action==="plan"?"Kayıtlı planı aç":"Kayıtlı görüşmeyi aç"}</button></p>:null)}</div>)}{r.reason&&<p>{r.reason}</p>}</article>)}
    {row&&response&&model&&<section aria-label="Seçili aile yanıtının sonraki adımı"><h4>{row.name} için sonraki adım</h4><label>Sonraki adım günü<KeyboardInput type="date" aria-label="Sonraki adım günü" value={model.selectedDay} min={model.days[0]} max={model.days.at(-1)} disabled={locked} onChange={e=>{setDay(e.target.value);setSlot("");}}/></label><div aria-label="Hazır boş öğretim günleri">{model.emptyDays.slice(0,5).map(date=><button type="button" key={date} disabled={locked} aria-pressed={model.selectedDay===date} onClick={()=>{setDay(date);setSlot("");}}>{date} · Boş güne yerleştir</button>)}</div><p>Boş öğretim günü seçildiğinde aynı kaynak etkinlik yalnız bu çocuk için yeniden planlanır.</p>{model.planReason&&<p>{model.planReason}</p>}<button type="button" disabled={locked||!model.canPlan} onClick={()=>void apply({feedbackId,action:"plan",day:model.selectedDay})}>Kaynak etkinliği bu güne yeniden planla</button>
      <h4>Veli görüşmesinin gündemine ekle</h4>{row.appointments.map(a=>a.plan?.workflow.kind==="appointment"?<button type="button" key={a.plan.id} disabled={locked} onClick={()=>{if(a.plan?.workflow.kind!=="appointment")return;void apply({feedbackId,action:"meeting",day:a.plan.workflow.scheduledOn,contactId:a.plan.workflow.contact.id,startTime:a.plan.workflow.startTime,appointmentId:a.plan.workflow.appointmentId});}}>{a.plan.workflow.scheduledOn} {a.plan.workflow.startTime} · {a.plan.workflow.contact.name} · Mevcut görüşmeye ekle</button>:null)}
      <label>Görüşülecek kayıtlı yakın<select aria-label="Görüşülecek kayıtlı yakın" value={contactId} disabled={locked} onChange={e=>setContactId(e.target.value)}><option value="">Kişiyi seçin</option>{row.contacts.map(c=><option key={c.id} value={c.id}>{c.name} · {c.relationship||c.kind}</option>)}</select></label>{!row.contacts.length&&<div><p>Bu çocuğun kayıtlı yakını bulunmuyor.</p><button type="button" disabled={locked||!onOpenStudent} onClick={()=>onOpenStudent?.(row.card.studentId)}>Yakın bilgilerini aç</button></div>}
      <label>Yeni görüşmenin saati<select aria-label="Yeni görüşmenin saati" disabled={locked} value={slot} onChange={e=>setSlot(e.target.value)}><option value="">Saati seçin</option>{model.slots.map(s=><option key={s.startTime} value={s.startTime}>{s.startTime}–{s.endTime} · Okul{s.createAvailability?" · uygun saat ve randevu oluştur":""}</option>)}</select></label><button type="button" disabled={locked||!contactId||!slot} onClick={()=>void apply({feedbackId,action:"meeting",day:model.selectedDay,contactId,startTime:slot})}>Bu yanıtla veli görüşmesi oluştur</button>
    </section>}
    {message&&<p role="status">{message}</p>}<button type="button" disabled={busy} onClick={()=>reload.current()}>Aile dönüşlerini yenile</button>
  </section>;
}


