import {canonicalJson} from "../../core/backup/canonical-json.ts";
import {civilDateInIstanbul,isCivilDate} from "../../core/domain/attendance.ts";
import {resolveActiveClassroomScope} from "../../core/domain/classroom-scope.ts";
import {currentClassDutySchedules,isClassDutyConfig,type ClassDutyConfig,type ClassDutyKind,type ClassDutyRecord,type ClassDutyRow} from "../../core/domain/class-duty-schedule.ts";
import {resolveSchoolDay,schoolCivilDates} from "../../core/domain/school-calendar.ts";
import {resolveStudentMembershipOn} from "../../core/domain/student-membership.ts";
import type {DataSnapshot,StoredRecord} from "../../core/domain/model.ts";
import type {LocalDataStore} from "../../core/repository/contracts.ts";

export type DutyChange={rowId:string;studentId?:string;startOn?:string;locked?:boolean;status?:ClassDutyRow["status"]};
export type DutyRequest={operationId:string;scheduleId:string}&({kind:"create";config:ClassDutyConfig}|{kind:"redistribute";config:ClassDutyConfig}|{kind:"changes";changes:DutyChange[]}|{kind:"shift";rowIds:string[];days:number});
export interface DutyDiff{rowId:string;before:ClassDutyRow|null;after:ClassDutyRow|null}
export interface DutyPreview{request:DutyRequest;expectedFingerprint:string;config:ClassDutyConfig;rows:ClassDutyRow[];diff:DutyDiff[];unassignedStudentIds:string[];unfilled:number;skippedDates:number;revision:number;effectiveOn:string}
export const dutyKindLabel=(kind:ClassDutyKind)=>kind==="fruit"?"Meyve günü":"Haftanın çocuğu";
export function dutyAddDays(day:string,n:number){const date=new Date(`${day}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);}
export function dutyWeekStart(day:string){return dutyAddDays(day,-((new Date(`${day}T12:00:00Z`).getUTCDay()+6)%7));}
export function dutyMonthPeriod(month:string){if(!/^\d{4}-\d{2}$/u.test(month))throw new Error("Geçerli bir ay seçin.");const start=`${month}-01`;if(!isCivilDate(start))throw new Error("Geçerli bir ay seçin.");const date=new Date(`${start}T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+1);return{startOn:start,endOn:dutyAddDays(date.toISOString().slice(0,10),-1)};}
const uuid=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(v);
const hash=(text:string)=>{let h=2166136261;for(const c of text){h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;}return h;};
const rowId=(scheduleId:string,date:string,index:number)=>`${scheduleId.slice(0,24)}${date.replace(/-/gu,"")}${String(index).padStart(4,"0")}`;
export function dutyCalendarId(id:string){return`${((parseInt(id.slice(0,8),16)^0x5a5a5a5a)>>>0).toString(16).padStart(8,"0")}${id.slice(8)}`;}
function context(data:DataSnapshot){const scope=resolveActiveClassroomScope(data);if(!scope)throw new Error("Görev çizelgesi için etkin sınıfı seçin.");const year=data.academicYears.find(y=>y.id===scope.academicYearId)!;return{scope,year,classroom:data.classrooms.find(c=>c.id===scope.classroomId)!};}
export function dutySourceFingerprint(data:DataSnapshot){const {scope,year,classroom}=context(data);return canonicalJson({scope,year,classroom,students:data.students.filter(s=>s.classroomId===scope.classroomId||Array.isArray(s.enrollments)&&s.enrollments.some(e=>e&&typeof e==="object"&&(e as Record<string,unknown>).classroomId===scope.classroomId)).sort((a,b)=>a.id.localeCompare(b.id)),schedules:currentClassDutySchedules(data,scope),closures:data.calendarEntries.filter(e=>e.classroomId===scope.classroomId&&e.academicYearId===scope.academicYearId&&e.entryType==="no_school").sort((a,b)=>a.id.localeCompare(b.id))});}
export function dutyEligible(data:DataSnapshot,studentId:string,day:string){const {scope,year}=context(data),student=data.students.find(s=>s.id===studentId);if(!student)return false;const result=resolveStudentMembershipOn(student,{...scope,academicYear:year,civilDate:day});return result.eligible&&!result.issues.length;}
export function dutyTeachingDates(data:DataSnapshot,start:string,end:string){const {scope,year}=context(data);return schoolCivilDates(start,end).filter(civilDate=>resolveSchoolDay({academicYear:year,classroomId:scope.classroomId,calendarEntries:data.calendarEntries,civilDate}).isTeachingDay);}
function dates(data:DataSnapshot,config:ClassDutyConfig){const teaching=dutyTeachingDates(data,config.startOn,config.endOn).filter(d=>config.weekdays.includes(new Date(`${d}T12:00:00Z`).getUTCDay()));if(config.kind==="fruit")return teaching.map(d=>({startOn:d,endOn:d}));const groups=new Map<string,string[]>();for(const day of teaching){const key=dutyWeekStart(day);groups.set(key,[...(groups.get(key)??[]),day]);}return[...groups.values()].map(days=>({startOn:days[0]!,endOn:days.at(-1)!}));}
function validateConfig(data:DataSnapshot,config:ClassDutyConfig){const {year}=context(data);if(!isClassDutyConfig(config)||!config.studentIds.length||config.startOn<String(year.startDate)||config.endOn>String(year.endDate))throw new Error("Görev türünü, dönem içindeki günleri, çocukları ve kapasiteyi kontrol edin.");if(config.studentIds.some(id=>!data.students.some(s=>s.id===id)))throw new Error("Seçilen çocuklardan biri artık kayıtlı değil.");}
function rowEnd(data:DataSnapshot,kind:ClassDutyKind,start:string,limit:string){if(kind==="fruit")return start;return dutyTeachingDates(data,start,[dutyAddDays(dutyWeekStart(start),6),limit].sort()[0]!).at(-1)??start;}
function fairRows(data:DataSnapshot,config:ClassDutyConfig,scheduleId:string,kept:ClassDutyRow[],today:string,strictFuture:boolean){
  const {scope}=context(data),all=currentClassDutySchedules(data,scope),history=all.filter(s=>s.workflow.config.kind===config.kind&&s.workflow.scheduleId!==scheduleId).flatMap(s=>s.workflow.rows).filter(r=>r.status!=="cancelled"&&r.startOn<config.startOn);
  const existing=[...kept],periodCount=new Map<string,number>(),priorCount=new Map<string,number>(),last=new Map<string,string>();for(const row of history){priorCount.set(row.studentId,(priorCount.get(row.studentId)??0)+1);last.set(row.studentId,[last.get(row.studentId)??"",row.startOn].sort().at(-1)!);}for(const row of kept.filter(r=>r.status!=="cancelled")){periodCount.set(row.studentId,(periodCount.get(row.studentId)??0)+1);last.set(row.studentId,[last.get(row.studentId)??"",row.startOn].sort().at(-1)!);}
  const fruitWeeks=new Set(all.filter(s=>s.workflow.config.kind==="fruit").flatMap(s=>s.workflow.rows.filter(r=>r.status!=="cancelled"&&r.status!=="missed").map(r=>`${r.studentId}:${dutyWeekStart(r.startOn)}`)));let unfilled=0;
  for(const slot of dates(data,config)){if(strictFuture?slot.startOn<=today:slot.startOn<today)continue;const fixed=existing.filter(r=>r.startOn===slot.startOn&&r.status!=="cancelled");for(let index=fixed.length;index<config.capacity;index++){
      const eligible=config.studentIds.filter(id=>dutyEligible(data,id,slot.startOn)&&dutyEligible(data,id,slot.endOn)&&!existing.some(r=>r.studentId===id&&r.status!=="cancelled"&&r.startOn<=slot.endOn&&r.endOn>=slot.startOn)&&!(config.kind==="child-of-week"&&config.avoidFruitWeek&&fruitWeeks.has(`${id}:${dutyWeekStart(slot.startOn)}`)));
      eligible.sort((a,b)=>{const ac=periodCount.get(a)??0,bc=periodCount.get(b)??0,ap=priorCount.get(a)??0,bp=priorCount.get(b)??0;return(config.kind==="child-of-week"?ac-bc:ac+ap-bc-bp)||(ap-bp)||(last.get(a)??"").localeCompare(last.get(b)??"")||hash(`${config.seed}:${slot.startOn}:${a}`)-hash(`${config.seed}:${slot.startOn}:${b}`)||a.localeCompare(b);});
      const studentId=eligible[0];if(!studentId){unfilled++;continue;}let serial=index,id=rowId(scheduleId,slot.startOn,serial);while(existing.some(r=>r.id===id))id=rowId(scheduleId,slot.startOn,++serial);existing.push({id,calendarEntryId:dutyCalendarId(id),studentId,...slot,locked:false,status:"planned"});periodCount.set(studentId,(periodCount.get(studentId)??0)+1);last.set(studentId,slot.startOn);
  }}return{rows:existing.sort((a,b)=>a.startOn.localeCompare(b.startOn)||a.id.localeCompare(b.id)),unfilled};
}
export function previewDutyRequest(data:DataSnapshot,request:DutyRequest,now=new Date()):DutyPreview{
  const allowedKeys=request.kind==="create"||request.kind==="redistribute"?["kind","operationId","scheduleId","config"]:request.kind==="changes"?["kind","operationId","scheduleId","changes"]:["kind","operationId","scheduleId","rowIds","days"];if(Object.keys(request).length!==allowedKeys.length||Object.keys(request).some(key=>!allowedKeys.includes(key)))throw new Error("Çizelge isteği tanınmayan veya eksik alan içeriyor.");
  const {scope,year}=context(data),today=civilDateInIstanbul(now);if(!uuid(request.operationId)||!uuid(request.scheduleId)||year.status==="archived")throw new Error("Etkin sınıf ve geçerli işlem kimliği gerekli.");const current=currentClassDutySchedules(data,scope).find(s=>s.workflow.scheduleId===request.scheduleId);let config:ClassDutyConfig,rows:ClassDutyRow[],unfilled=0;
  if(request.kind==="create"||request.kind==="redistribute"){
    config=structuredClone(request.config);validateConfig(data,config);if(request.kind==="create"&&current)throw new Error("Bu çizelge zaten kaydedildi; kayıtlı sürümü açın.");if(request.kind==="redistribute"&&!current)throw new Error("Yeniden dağıtılacak çizelge bulunamadı.");if(current&&current.workflow.config.kind!==config.kind)throw new Error("Kayıtlı görevin türü değiştirilemez.");
    if(currentClassDutySchedules(data,scope).some(s=>s.workflow.scheduleId!==request.scheduleId&&s.workflow.config.kind===config.kind&&s.workflow.config.startOn<=config.endOn&&s.workflow.config.endOn>=config.startOn))throw new Error("Bu dönemde aynı türde kayıtlı çizelge var; o çizelgenin kalan günlerini düzenleyin.");
    const kept=current?.workflow.rows.filter(r=>r.startOn<=today||r.locked||r.status!=="planned")??[];if(kept.some(r=>r.startOn<config.startOn||r.endOn>config.endOn))throw new Error("Geçmiş, sabit veya gerçekleşmiş görevleri yeni dönemin dışında bırakamazsınız.");const result=fairRows(data,config,request.scheduleId,kept,today,request.kind==="redistribute");rows=result.rows;unfilled=result.unfilled;
  }else{
    if(!current)throw new Error("Düzenlenecek çizelge bulunamadı.");config=structuredClone(current.workflow.config);rows=structuredClone(current.workflow.rows);let changes:DutyChange[];
    if(request.kind==="shift"){if(!Number.isInteger(request.days)||request.days<1||request.days>60||!request.rowIds.length||new Set(request.rowIds).size!==request.rowIds.length)throw new Error("Kaydırılacak gelecekteki görevleri ve gün sayısını seçin.");changes=request.rowIds.map(rowId=>{const row=rows.find(r=>r.id===rowId);if(!row||row.startOn<=today||row.locked||row.status!=="planned")throw new Error("Toplu kaydırma yalnız seçili, sabitlenmemiş gelecekteki görevler içindir.");const target=dutyTeachingDates(data,dutyAddDays(row.startOn,request.days),String(year.endDate))[0];if(!target)throw new Error("Eğitim yılı içinde kaydırılabilecek gün kalmadı.");config.endOn=[config.endOn,rowEnd(data,config.kind,target,String(year.endDate))].sort().at(-1)!;return{rowId,startOn:target};});}
    else if(request.kind==="changes"){if(!request.changes.length||new Set(request.changes.map(c=>c.rowId)).size!==request.changes.length)throw new Error("Değiştirilecek farklı görev satırlarını seçin.");changes=request.changes;}else throw new Error("Geçersiz çizelge işlemi.");
    for(const change of changes){if(Object.keys(change).some(k=>!["rowId","studentId","startOn","locked","status"].includes(k)))throw new Error("Çizelge değişikliği tanınmayan alan içeriyor.");const row=rows.find(r=>r.id===change.rowId);if(!row)throw new Error("Seçilen görev satırı bulunamadı.");const moving=(change.startOn!==undefined&&change.startOn!==row.startOn)||(change.studentId!==undefined&&change.studentId!==row.studentId);if(moving&&(row.startOn<today||row.status!=="planned"||row.locked))throw new Error("Geçmiş, gerçekleşmiş veya sabit görevin günü/çocuğu değiştirilemez.");if(change.startOn!==undefined){if(!isCivilDate(change.startOn)||change.startOn<today||!dutyTeachingDates(data,change.startOn,change.startOn).length)throw new Error("Yeni görev günü geçmişte veya okulun kapalı olduğu tarihte olamaz.");row.startOn=change.startOn;row.endOn=rowEnd(data,config.kind,row.startOn,config.endOn);}if(change.studentId!==undefined){row.studentId=change.studentId;if(!config.studentIds.includes(row.studentId))config.studentIds.push(row.studentId);}if(change.locked!==undefined){if(typeof change.locked!=="boolean")throw new Error("Sabit gün seçimi geçersiz.");row.locked=change.locked;}if(change.status!==undefined){if(!["planned","completed","missed","cancelled"].includes(change.status)||((change.status==="completed"||change.status==="missed")&&row.startOn>today))throw new Error("Gelecekteki görev gerçekleşmiş olarak kaydedilemez.");row.status=change.status;}
      if(moving&&(!dutyEligible(data,row.studentId,row.startOn)||!dutyEligible(data,row.studentId,row.endOn)))throw new Error("Çocuk yeni görev tarihinde bu sınıfa kayıtlı değil.");
    }
  }
  for(const row of rows){if(row.startOn<config.startOn||row.endOn>config.endOn)throw new Error("Yeni görev günü çizelge dönemi içinde olmalıdır.");if(rows.filter(r=>r.startOn===row.startOn&&r.status!=="cancelled").length>config.capacity)throw new Error("Hedef günün kişi kapasitesi dolu. Önce iki görevi karşılıklı değiştirin veya kapasiteyi artırın.");if(row.status!=="cancelled"&&rows.some(other=>other.id!==row.id&&other.studentId===row.studentId&&other.status!=="cancelled"&&other.startOn<=row.endOn&&other.endOn>=row.startOn))throw new Error("Aynı çocuk çakışan iki göreve atanamaz.");}
  if(currentClassDutySchedules(data,scope).some(s=>s.workflow.scheduleId!==request.scheduleId&&s.workflow.config.kind===config.kind&&s.workflow.config.startOn<=config.endOn&&s.workflow.config.endOn>=config.startOn))throw new Error("Yeni dönem aynı türdeki başka çizelgeyle çakışıyor; dönemleri ayrı tutun.");
  const before=current?.workflow.rows??[],ids=new Set([...before.map(r=>r.id),...rows.map(r=>r.id)]),diff=[...ids].flatMap(rowId=>{const a=before.find(r=>r.id===rowId)??null,b=rows.find(r=>r.id===rowId)??null;return canonicalJson(a)===canonicalJson(b)?[]:[{rowId,before:a,after:b}];});
  return{request:structuredClone(request),expectedFingerprint:dutySourceFingerprint(data),config,rows,diff,unassignedStudentIds:config.studentIds.filter(id=>!rows.some(r=>r.studentId===id&&r.status!=="cancelled")),unfilled,skippedDates:schoolCivilDates(config.startOn,config.endOn).length-dutyTeachingDates(data,config.startOn,config.endOn).length,revision:(current?.workflow.revision??0)+1,effectiveOn:diff.map(d=>d.after?.startOn??d.before!.startOn).filter(d=>d>=today).sort()[0]??today};
}
export function classDutyForCalendarEntry(data:DataSnapshot,entryId:string){return currentClassDutySchedules(data).find(s=>s.workflow.rows.some(r=>r.calendarEntryId===entryId))??null;}
export function classDutyWeekSummary(data:DataSnapshot,{civilDate}:{civilDate:string}){const scope=resolveActiveClassroomScope(data);if(!scope)return[];const start=dutyWeekStart(civilDate),end=dutyAddDays(start,6);return currentClassDutySchedules(data,scope).flatMap(s=>s.workflow.rows.filter(r=>r.startOn<=end&&r.endOn>=start&&r.status!=="cancelled").map(row=>({scheduleId:s.workflow.scheduleId,rowId:row.id,kind:s.workflow.config.kind,title:dutyKindLabel(s.workflow.config.kind),studentId:row.studentId,studentName:String(data.students.find(c=>c.id===row.studentId)?.displayName??""),civilDate:row.startOn,endOn:row.endOn,status:row.status}))).sort((a,b)=>a.civilDate.localeCompare(b.civilDate));}
export async function loadClassDutyWeekSummary(store:LocalDataStore,input:{civilDate:string}){return classDutyWeekSummary(await store.readSnapshot(),input);}
export function dutyDefaultConfig(data:DataSnapshot,kind:ClassDutyKind,month:string){const {scope,year}=context(data),period=dutyMonthPeriod(month),prior=currentClassDutySchedules(data,scope).filter(r=>r.workflow.config.kind===kind&&r.workflow.config.endOn<period.startOn).sort((a,b)=>b.workflow.config.endOn.localeCompare(a.workflow.config.endOn))[0]?.workflow.config;return{kind,startOn:[period.startOn,String(year.startDate)].sort().at(-1)!,endOn:[period.endOn,String(year.endDate)].sort()[0]!,weekdays:prior?.weekdays??(kind==="fruit"?[3]:[1,2,3,4,5]),studentIds:data.students.filter(s=>schoolCivilDates(period.startOn,period.endOn).some(d=>dutyEligible(data,s.id,d))).map(s=>s.id),capacity:prior?.capacity??1,avoidFruitWeek:prior?.avoidFruitWeek??true,seed:prior?.seed??0,participation:prior?.participation??["Sevdiği oyunu sınıfla paylaşma"]} satisfies ClassDutyConfig;}


