import {PDFDocument} from 'pdf-lib';
import {canonicalJson} from '../../core/backup/canonical-json.ts';
import type {LocalDataStore} from '../../core/repository/contracts.ts';
import {createBinaryZip} from '../documents/binary-zip.ts';
import {createSemanticTaggedPdf,type SemanticPdfNode} from '../documents/semantic-tagged-pdf.ts';
import {TEACHER_DOCUMENT_THEME,TEACHER_PRINT_THEME} from '../documents/document-theme.ts';
import {validatePdfSelection,type PdfPreviewRecipe} from '../documents/pdf-preview-model.ts';
import {wordDocumentStyles,wordRunningFooter,wordRunningHeader,wordXmlText} from '../documents/word-document-design.ts';
import {createMonthlyWallCalendarPdf} from '../planning/planning-calendar-pdf.ts';
import {dutyBoardModel,dutyDocumentModel,dutyDocumentFingerprint,dutyRevisionSource,dutyScheduleRows,dutyStatusLabel,type DutyDocumentModel} from './class-duty-document-model.ts';
import {createClassDutySpreadsheet} from './class-duty-spreadsheet.ts';
import {dutyAddDays,dutyMonthPeriod,dutyWeekStart} from './class-duty-model.ts';

export async function createClassDutyPdf(model:DutyDocumentModel,options:{studentIds?:readonly string[];template?:string;appearance?:string;highlightChanges?:boolean}={}){
 const ids=options.studentIds??model.students.map(s=>s.id),rows=model.rows.filter(r=>ids.includes(r.studentId)),nodes:SemanticPdfNode[]=[];
 const columns=[0,1,2,...(rows.some(r=>r.locked)?[3]:[]),...(options.highlightChanges&&model.record.workflow.revision>1?[4]:[])];
 const context=`${model.schoolName} · ${model.classroomName}`;
 if(options.template==='calendar'){
  let month=model.record.workflow.config.startOn.slice(0,7),index=0;
  while(month<=model.record.workflow.config.endOn.slice(0,7)){
   const period=dutyMonthPeriod(month),start=dutyWeekStart(period.startOn),end=dutyAddDays(dutyWeekStart(period.endOn),6),grid:string[][]=[];let week:string[]=[];
   for(let day=start;day<=end;day=dutyAddDays(day,1)){const matching=rows.filter(r=>r.startOn<=day&&r.endOn>=day&&day.slice(0,7)===month);week.push(day.slice(0,7)!==month?'':`${Number(day.slice(-2))}${matching.length?'\n'+matching.map(r=>`${r.studentName}\n${dutyStatusLabel(r.status)}${r.locked?' · Sabit':''}`).join('\n'):''}`);if(week.length===7){grid.push(week);week=[];}}
   nodes.push({kind:'heading',level:1,text:`${model.title} · ${month}`,continuationHeaderText:`${context} · ${model.title} · ${month} · v${model.record.workflow.revision}`,pageBreakBefore:index>0,forcePageBreakBefore:index>0},{kind:'paragraph',text:context},{kind:'paragraph',text:dutyRevisionSource(model.record)},{kind:'table',headers:['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'],rows:grid,columnWeights:[1,1,1,1,1,.8,.8],cellPadding:8,fontSize:10,balancePages:true},{kind:'paragraph',text:`${model.teacherName} · Okul Öncesi Öğretmeni`});
   month=dutyAddDays(period.endOn,1).slice(0,7);index++;
  }
 }else if(options.template==='child-card'){
  for(const [index,row] of rows.entries())nodes.push({kind:'heading',level:1,text:model.title,pageBreakBefore:index>0,forcePageBreakBefore:index>0},{kind:'paragraph',text:context},{kind:'heading',level:2,text:row.studentName},{kind:'paragraph',text:row.startOn===row.endOn?row.startOn:`${row.startOn} – ${row.endOn}`},{kind:'paragraph',text:`Görev durumu: ${dutyStatusLabel(row.status)}`},{kind:'heading',level:2,text:'Birlikte hazırlanacaklar'},{kind:'list',items:model.record.workflow.config.participation.length?model.record.workflow.config.participation:['Öğretmenin kayıtlı çizelgesindeki göreve hazırlanma']},{kind:'paragraph',text:`Öğretmen: ${model.teacherName}`},{kind:'paragraph',text:dutyRevisionSource(model.record),tone:'meta'});
 }else nodes.push({kind:'heading',level:1,text:model.title},{kind:'paragraph',text:context},{kind:'paragraph',text:`${model.academicYearName} · ${dutyRevisionSource(model.record)}`},{kind:'table',headers:columns.map(i=>['Görev tarihi','Çocuk','Durum','Gün','Sürüm farkı'][i]!),rows:dutyScheduleRows(model,ids).map(row=>columns.map(i=>row[i]!)),columnWeights:columns.map(i=>[1.5,3.2,1.2,.7,1.2][i]!),fontSize:10,cellPadding:7,balancePages:true,continuationContextColumns:[0,1],preserveContinuationContext:true},{kind:'paragraph',text:`Öğretmen: ${model.teacherName}`},...(model.record.workflow.config.kind==='child-of-week'&&model.record.workflow.config.participation.length?[{kind:'heading',level:2,text:'Seçilen katılım hazırlıkları'} as const,{kind:'list',items:model.record.workflow.config.participation} as const]:[]));
 if(!rows.length)throw Error('Bu seçimde belgeye alınacak kayıtlı görev yok.');
 return createSemanticTaggedPdf({title:model.title,theme:options.appearance==='ink-saving'?TEACHER_PRINT_THEME:TEACHER_DOCUMENT_THEME,orientation:options.template==='calendar'?'landscape':'portrait',pageMargin:32,nodes,artifactHeaderText:context,artifactFooterText:`${model.teacherName} · Okul Öncesi Öğretmeni · v${model.record.workflow.revision}`,includeTotalPages:true});
}

export function createClassDutyWord(model:DutyDocumentModel,ids:readonly string[]=model.students.map(s=>s.id),highlightChanges=false){
 const columns=[0,1,2,...(model.rows.some(r=>ids.includes(r.studentId)&&r.locked)?[3]:[]),...(highlightChanges&&model.record.workflow.revision>1?[4]:[])],weights=columns.map(i=>[1.5,3.2,1.2,.7,1.2][i]!),total=weights.reduce((a,b)=>a+b,0);
 const x=wordXmlText,p=(text:string,style?:string)=>`<w:p><w:pPr>${style?`<w:pStyle w:val="${style}"/>`:''}<w:spacing w:after="90"/></w:pPr><w:r><w:t xml:space="preserve">${x(text)}</w:t></w:r></w:p>`,widths=weights.map(w=>Math.floor(w*9250/total)),cell=(text:string,i:number,header:boolean)=>`<w:tc><w:tcPr><w:tcW w:w="${widths[i]}" w:type="dxa"/>${header?'<w:shd w:fill="17324D"/>':''}</w:tcPr><w:p><w:r><w:rPr>${header?'<w:b/><w:color w:val="FFFFFF"/>':''}</w:rPr><w:t xml:space="preserve">${x(text)}</w:t></w:r></w:p></w:tc>`;
 const table=[['Görev tarihi','Çocuk','Durum','Gün','Sürüm farkı'],...dutyScheduleRows(model,ids)].map(row=>columns.map(i=>row[i]!)).map((row,i)=>`<w:tr><w:trPr><w:cantSplit/>${i===0?'<w:tblHeader/>':''}</w:trPr>${row.map((v,j)=>cell(v,j,i===0)).join('')}</w:tr>`).join('');
 const body=p(model.title,'Title')+p(`${model.schoolName} · ${model.classroomName}`)+p(`${model.academicYearName} · ${dutyRevisionSource(model.record)}`)+`<w:tbl><w:tblPr><w:tblW w:w="9250" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellMar><w:top w:w="95" w:type="dxa"/><w:left w:w="85" w:type="dxa"/><w:bottom w:w="95" w:type="dxa"/><w:right w:w="85" w:type="dxa"/></w:tblCellMar><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(s=>`<w:${s} w:val="single" w:sz="6" w:color="607D91"/>`).join('')}</w:tblBorders></w:tblPr><w:tblGrid>${widths.map(w=>`<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid>${table}</w:tbl>`+p(`Öğretmen: ${model.teacherName}`)+(model.record.workflow.config.participation.length?p('Seçilen katılım hazırlıkları','Heading1')+model.record.workflow.config.participation.map(t=>p(t)).join(''):'');
 const relns='http://schemas.openxmlformats.org/package/2006/relationships',off='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const files:{name:string;text:string}[]=[
  {name:'[Content_Types].xml',text:`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${[['document','document.main'],['styles','styles'],['header1','header'],['footer1','footer']].map(([name,type])=>`<Override PartName="/word/${name}.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.${type}+xml"/>`).join('')}</Types>`},
  {name:'_rels/.rels',text:`<Relationships xmlns="${relns}"><Relationship Id="main" Type="${off}/officeDocument" Target="word/document.xml"/></Relationships>`},
  {name:'word/_rels/document.xml.rels',text:`<Relationships xmlns="${relns}">${[['styles','styles'],['header','header1'],['footer','footer1']].map(([id,file])=>`<Relationship Id="${id}" Type="${off}/${id}" Target="${file}.xml"/>`).join('')}</Relationships>`},
  {name:'word/document.xml',text:`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="${off}"><w:body>${body}<w:sectPr><w:headerReference w:type="default" r:id="header"/><w:footerReference w:type="default" r:id="footer"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="900" w:right="1100" w:bottom="900" w:left="1100" w:header="400" w:footer="400"/></w:sectPr></w:body></w:document>`},
  {name:'word/styles.xml',text:wordDocumentStyles(20,true)},
  {name:'word/header1.xml',text:wordRunningHeader(model.title,`${model.classroomName} · v${model.record.workflow.revision}`)},
  {name:'word/footer1.xml',text:wordRunningFooter(`${model.teacherName} · ${model.record.workflow.config.startOn} – ${model.record.workflow.config.endOn}`)}
 ];
 return{bytes:createBinaryZip(files.map(f=>({name:f.name,bytes:new TextEncoder().encode(f.text.startsWith("<?xml")?f.text:'<?xml version="1.0" encoding="UTF-8"?>'+f.text)}))),mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',fileName:`Gorev_Cizelgesi_${model.record.workflow.config.startOn}_v${model.record.workflow.revision}.docx`};
}

export async function createClassDutyRecipe(store:LocalDataStore,scheduleId:string):Promise<PdfPreviewRecipe>{
 const model=dutyDocumentModel(await store.readSnapshot(),scheduleId),expected=dutyDocumentFingerprint(model);
 const recipe:PdfPreviewRecipe={title:model.title,description:'Kayıtlı görevler ve gerçek takvim tarihleri. PDF, düzenlenebilir Word ve aynı sürüme bağlı Excel aynı kaynaktan hazırlanır.',fields:[{id:'schedule',label:'Tarihler, çocuklar ve gerçekleşme durumu'},{id:'changes',label:'Son sürümde değişen satırları göster'}],students:model.students,supportsAppearance:true,templates:[{id:'list',label:'Dikey A4 sınıf çizelgesi'},{id:'calendar',label:'Yatay A4 dönem takvimi'},{id:'child-card',label:'Çocuk başına A4 katılım kartı'}],initial:{fields:['schedule'],studentIds:model.students.map(s=>s.id),template:'list'},printEnabled:true,refresh:()=>createClassDutyRecipe(store,scheduleId),
  assertExportAllowed:async s=>{validatePdfSelection(recipe,s);if(!s.fields.includes("schedule"))throw Error("Çizelge alanını seçin.");if(dutyDocumentFingerprint(dutyDocumentModel(await store.readSnapshot(),scheduleId))!==expected)throw Error('Çizelgenin sürümü veya çocuk kaynağı değişti. Seçimleri koruyarak belgeyi güncelleyin.');},
  build:async s=>{await recipe.assertExportAllowed!(s);return{bytes:await createClassDutyPdf(model,{studentIds:s.studentIds,template:s.template,appearance:s.appearance,highlightChanges:s.fields.includes("changes")}),mimeType:'application/pdf',fileName:`${model.record.workflow.config.kind==='fruit'?'Meyve_Gunu':'Haftanin_Cocugu'}_${model.record.workflow.config.startOn}_v${model.record.workflow.revision}.pdf`};},
  exportActions:[{id:'word',label:'Word indir',templates:['list'],build:async s=>{await recipe.assertExportAllowed!(s);return createClassDutyWord(model,s.studentIds,s.fields.includes("changes"));}},{id:'xlsx',label:'Düzenlenebilir Excel indir',templates:['list'],build:async s=>{await recipe.assertExportAllowed!(s);if(s.studentIds?.length!==model.students.length)throw Error('Excel geri aktarımı bütün çizelgeyi korur. Excel için tüm çocukları seçin.');return createClassDutySpreadsheet(model);}}]};return recipe;
}
export async function createClassDutyBoardRecipe(store:LocalDataStore,monthKey:string):Promise<PdfPreviewRecipe>{
 const model=dutyBoardModel(await store.readSnapshot(),monthKey),expected=canonicalJson(model),ids=[...new Set([...model.calendar.studentIds,...model.schedules.flatMap(s=>s.students.map(p=>p.id))])],data=await store.readSnapshot(),students=ids.map(id=>({id,label:String(data.students.find(s=>s.id===id)?.displayName??'')}));
 const recipe:PdfPreviewRecipe={title:'Sınıf panosu paketi',description:'Bu ayın kayıtlı meyve günü ve haftanın çocuğu çizelgeleri, gerçek aylık takvimle tek PDF dosyasında.',fields:[{id:'board',label:'Kayıtlı görev çizelgeleri ve aylık takvim'}],...(students.length?{students}:{}),initial:{fields:['board'],...(students.length?{studentIds:ids}:{})},printEnabled:true,refresh:()=>createClassDutyBoardRecipe(store,monthKey),assertExportAllowed:async s=>{validatePdfSelection(recipe,s);if(students.length&&(s.studentIds?.length!==ids.length||ids.some(id=>!s.studentIds?.includes(id))))throw Error('Birleşik panonun kayıtlı çocuk kapsamı birlikte korunmalıdır.');if(canonicalJson(dutyBoardModel(await store.readSnapshot(),monthKey))!==expected)throw Error('Pano kaynakları değişti. Aylık paketi güncelleyin.');},build:async s=>{await recipe.assertExportAllowed!(s);const pdf=await PDFDocument.create();for(const schedule of model.schedules){const bytes=await createClassDutyPdf(schedule);const source=await PDFDocument.load(bytes);for(const p of await pdf.copyPages(source,source.getPageIndices()))pdf.addPage(p);}const file=await createMonthlyWallCalendarPdf(model.calendar),source=await PDFDocument.load(file.bytes);for(const p of await pdf.copyPages(source,source.getPageIndices()))pdf.addPage(p);pdf.setTitle(`Sınıf panosu · ${monthKey}`);return{bytes:await pdf.save(),mimeType:'application/pdf',fileName:`Sinif_Panosu_${monthKey}.pdf`};}};return recipe;
}





