import {expect,test} from '@playwright/test';
test.setTimeout(90000);
test('Görev çizelgesi gerçek takvime atomik yazılır; tekrar, eski kaynak, yedek ve çocuk silme korunur',async({page})=>{
 await page.goto('/tests/runtime-fixture.html');const result=await page.evaluate(async()=>{
  const core=await import('/src/core/index.ts'),fx=await import('/tests/fixtures/class-duty-fixture.mjs'),svc=await import('/src/features/class-duty-schedule/class-duty-service.ts'),domain=await import('/src/core/domain/class-duty-schedule.ts'),life=await import('/src/features/students/student-lifecycle.ts');
  const store=new core.IndexedDbDataStore({databaseName:`duty-${crypto.randomUUID()}`}),f=await fx.makeClassDutyFixture(store),before=await store.readSnapshot(),original=store.transaction.bind(store);let puts=0;
  store.transaction=async(mode,collections,task)=>original(mode,collections,async tx=>task(new Proxy(tx,{get(target,key){if(key==='putMany')return async(c,records)=>{await target.putMany(c,records);if(++puts===2)throw Error('Kurgu ikinci yazım kesintisi');};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}})));
  let failed=false;try{await f.save();}catch(e){failed=true;if(!String(e).includes('Kurgu ikinci'))throw e;}store.transaction=original;
  const rollback=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot()),saved=await f.save(),repeat=await f.save();
  let stale=false;try{await svc.applyClassDutySchedule(store,{request:{...f.request,operationId:crypto.randomUUID(),scheduleId:crypto.randomUUID()},expectedFingerprint:f.preview.expectedFingerprint,now:f.now});}catch{stale=true;}
  const snapshot=await store.readSnapshot();domain.assertClassDutyRelationships(snapshot);const linked=saved.record.workflow.rows.every(r=>snapshot.calendarEntries.some(e=>e.id===r.calendarEntryId&&e.startDate===r.startOn));
  const options={appVersion:'0.43.0',clock:()=>new Date('2026-09-17T12:00:00Z')},backup=new core.BackupService(store,options),bytes=await backup.exportBackup(),verified=await backup.parseAndVerifyBackup(bytes);
  const enc=await import('/src/core/backup/encrypted-backup.ts'),password='Kurgu görev yedeği!',encrypted=backup.serializeEncryptedBackup(await enc.encryptBackupText(core.canonicalJson(verified),{appVersion:'0.43.0',createdAt:verified.manifest.createdAt},password));
  const target=new core.IndexedDbDataStore({databaseName:`duty-copy-${crypto.randomUUID()}`}),restorer=new core.BackupService(target,options);await restorer.restoreEncryptedBackup(encrypted,password,{mode:'replace',createRecoverySnapshot:false});const exact=core.canonicalJson(snapshot)===core.canonicalJson(await target.readSnapshot());
  const preview=life.previewPermanentStudentDeletion(snapshot,f.input.studentId);await life.permanentlyDeleteStudent(store,{studentId:f.input.studentId,confirmationName:preview.displayName,expectedFingerprint:preview.fingerprint,now:new Date('2026-09-17T11:00:00Z')});const after=await store.readSnapshot();domain.assertClassDutyRelationships(after);await backup.parseAndVerifyBackup(await backup.exportBackup());
  const records=domain.classDutyRecords(after),removed=records.every(r=>!r.workflow.config.studentIds.includes(f.input.studentId)&&r.workflow.rows.every(x=>x.studentId!==f.input.studentId)),peer=records[0].workflow.rows.some(r=>r.studentId===f.otherStudentId);store.close();target.close();return{failed,puts,rollback,changed:saved.changed,repeat:repeat.changed,stale,linked,exact,verified:!!verified,removed,peer};
 });expect(result).toEqual({failed:true,puts:2,rollback:true,changed:true,repeat:false,stale:true,linked:true,exact:true,verified:true,removed:true,peer:true});
});
test('Sabitleme, karşılıklı çocuk değişimi, toplu kaydırma ve gerçekleşme kaynak sürümlerini korur',async({page})=>{
 await page.goto('/tests/runtime-fixture.html');const result=await page.evaluate(async()=>{
  const core=await import('/src/core/index.ts'),fx=await import('/tests/fixtures/class-duty-fixture.mjs'),svc=await import('/src/features/class-duty-schedule/class-duty-service.ts'),dom=await import('/src/core/domain/class-duty-schedule.ts'),calendar=await import('/src/features/calendar/academic-calendar.ts');
  const store=new core.IndexedDbDataStore({databaseName:`duty-revisions-${crypto.randomUUID()}`}),f=await fx.makeClassDutyFixture(store);let saved=await f.save();const initial=saved.record.workflow.rows,first=initial[0],second=initial[1];
  const apply=async(changes,now=f.now)=>{const request={kind:'changes' as const,scheduleId:f.request.scheduleId,operationId:crypto.randomUUID(),changes},preview=await svc.previewClassDutySchedule(store,request,{now});return svc.applyClassDutySchedule(store,{request,expectedFingerprint:preview.expectedFingerprint,now});};
  await apply([{rowId:first.id,locked:true}]);let locked=false;try{await apply([{rowId:first.id,startOn:'2026-10-08'}]);}catch{locked=true;}await apply([{rowId:first.id,locked:false}]);
  saved=await apply([{rowId:first.id,studentId:second.studentId},{rowId:second.id,studentId:first.studentId}]);const swapped=saved.record.workflow.rows[0].studentId===second.studentId&&saved.record.workflow.rows[1].studentId===first.studentId;
  const shift={kind:'shift' as const,scheduleId:f.request.scheduleId,operationId:crypto.randomUUID(),rowIds:saved.record.workflow.rows.map(r=>r.id),days:1},p=await svc.previewClassDutySchedule(store,shift,{now:f.now});saved=await svc.applyClassDutySchedule(store,{request:shift,expectedFingerprint:p.expectedFingerprint,now:f.now});const shifted=saved.record.workflow.rows.every((r,i)=>r.startOn>initial[i].startOn);
  let future=false;try{await apply([{rowId:first.id,status:'completed'}]);}catch{future=true;}const now=new Date('2026-10-09T09:00:00Z');saved=await apply([{rowId:first.id,status:'completed'}],now);
  const shuffle={...f.request,kind:'redistribute' as const,operationId:crypto.randomUUID(),config:{...saved.record.workflow.config,seed:50}};const next=await svc.previewClassDutySchedule(store,shuffle,{now});const preserved=next.rows.find(r=>r.id===first.id)?.status==='completed'&&next.rows.find(r=>r.id===first.id)?.startOn===saved.record.workflow.rows[0].startOn;
  let generic=false;try{await calendar.removeCalendarEntry(store,{id:first.calendarEntryId,now});}catch(e){generic=String(e).includes("çizelge");}
  const snapshot=await store.readSnapshot();dom.assertClassDutyRelationships(snapshot);const versions=dom.classDutyRecords(snapshot).length;await new core.BackupService(store,{appVersion:'0.43.0',clock:()=>now}).exportBackup();store.close();return{locked,swapped,shifted,future,preserved,generic,versions};
 });expect(result).toEqual({locked:true,swapped:true,shifted:true,future:true,preserved:true,generic:true,versions:6});
});

