import { test, expect, type Page } from "@playwright/test";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { PDFDocument } from "pdf-lib";
const production = process.env.DAILY_ROUTINE_PRODUCTION === "1", output = `output/daily-routine-cards-2026-09-08/${production ? "production" : "dev"}`;
async function setup(page: Page) {
  await page.addInitScript(() => { const original = URL.createObjectURL.bind(URL); (window as any).__routinePdfBlobs = []; URL.createObjectURL = (blob: Blob | MediaSource) => { if (blob instanceof Blob && blob.type === "application/pdf") (window as any).__routinePdfBlobs.push(blob.arrayBuffer().then(b => crypto.subtle.digest("SHA-256", b)).then(b => Array.from(new Uint8Array(b)).map(n => n.toString(16).padStart(2, "0")).join(""))); return original(blob); }; });
  await mkdir(output, { recursive: true }); await page.clock.install({ time: new Date("2026-09-18T09:00:00.000Z") }); await page.goto("/classroom?native=1");
  const dialog = page.getByRole("dialog", { name: "Sınıfını hazırla", exact: true }); await dialog.getByLabel("Okul adı").fill("Kurgu Anaokulu"); await dialog.getByLabel("Öğretmen adı soyadı").fill("Kurgu Öğretmen"); await dialog.getByLabel("Sınıf adı").fill("Kurgu Rutin Sınıfı"); await dialog.getByLabel("Maarif Modeli yaş grubu", { exact: true }).selectOption({ label: "60–72 ay" }); await dialog.getByRole("button", { name: "Sınıfımı hazırla", exact: true }).click(); await expect(dialog).toBeHidden();
  if (production) { await expect.poll(() => page.evaluate(() => Boolean((window as Window & { __maarifosPwaStatus?: { offlineReady?: boolean } }).__maarifosPwaStatus?.offlineReady)), { timeout: 60000 }).toBe(true); await page.context().setOffline(true); await page.reload({ waitUntil: "domcontentloaded" }); }
}
async function open(page: Page) { await page.getByRole("region", { name: "Sınıf yönetimi işleri", exact: true }).getByRole("button").first().click(); const d = page.getByRole("dialog", { name: "Sınıf yönetimi", exact: true }); await d.getByLabel("Sınıf yönetimi alanı").selectOption("routines"); await expect(d.getByTestId("daily-routine-cards-workspace")).toBeVisible(); return d; }
async function count(page: Page) { return page.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const store = new IndexedDbDataStore(); try { return (await store.readSnapshot()).settings.filter(r => r.settingType === "daily-routine-cards-v1").length; } finally { store.close(); } }); }
async function pdf(page: Page, a5: boolean, pages: number) {
  await page.getByRole("button", { name: "Kayıtlı kartları PDF önizle", exact: true }).click(); const preview = page.getByRole("dialog", { name: "PDF önizlemesi", exact: true });
  if (a5) { await preview.getByText("Şablon ve belge kapsamı", { exact: true }).click(); await preview.getByLabel("Hazır şablon").selectOption("a5"); }
  const canvas = preview.locator("canvas").first(); await expect(canvas).toHaveAttribute("data-pdf-rendered", "true", { timeout: 60000 });
  if (a5) await expect(preview.getByText(`Sayfa 1 / ${pages}`, { exact: true })).toBeVisible();
  const download = page.waitForEvent("download"); await preview.getByRole("button", { name: "Bu PDF'yi indir", exact: true }).click(); const file = await download; const path = `${output}/routine-${a5 ? "A5" : "A4"}.pdf`; await file.saveAs(path); const bytes = await readFile(path); expect(bytes.subarray(0, 5).toString()).toBe("%PDF-"); const doc = await PDFDocument.load(bytes); expect(doc.getPageCount()).toBe(pages); const size = doc.getPage(0).getSize(); expect(size.width).toBeCloseTo((a5 ? 148 : 210) * 72 / 25.4, 3); expect(size.height).toBeCloseTo((a5 ? 210 : 297) * 72 / 25.4, 3);
  const hashes = await page.evaluate(() => Promise.all((window as any).__routinePdfBlobs)) as string[], hash = createHash("sha256").update(bytes).digest("hex"); expect(hashes.at(-1)).toBe(hash); expect(hashes.at(-2)).toBe(hash); await writeFile(`${output}/routine-${a5 ? "A5" : "A4"}-receipt.json`, JSON.stringify({ syntheticOnly: true, pages, sizePoints: size, previewAndDownloadSha256: hash, sameBytes: true }, null, 2));
  await canvas.scrollIntoViewIfNeeded(); await canvas.screenshot({ path: `${output}/routine-${a5 ? "A5" : "A4"}-preview.png` }); await preview.getByRole("button", { name: "PDF önizlemesini kapat", exact: true }).click(); await expect(preview).toBeHidden();
}
test("390px: açık taslak, sıra/başlık/simge, kısa/tam sürüm, gerçek A4/A5 PDF ve reload", async ({ page }) => {
  await setup(page); let d = await open(page); await expect(d.getByText("TASLAK · Bu değişiklikler henüz kaydedilmedi", { exact: true })).toBeVisible(); await expect(d.getByTestId("routine-card")).toHaveCount(6); if (!production) expect(await count(page)).toBe(0);
  if (!production) { const boundary = await page.evaluate(async () => { const { fitRoutineCardTitle, wrapRoutineText } = await import("/src/features/daily-routine-cards/routine-title-layout.ts"); const font = await new FontFace("RoutinePrint", "url(/assets/fonts/MaarifOSSans-Regular.ttf)").load(); document.fonts.add(font); const ctx = document.createElement("canvas").getContext("2d")!; const title = "Güne birlikte merhaba diyerek oyun zamanı başlar. ".repeat(4).trim(); ctx.font = "18px RoutinePrint"; const height = wrapRoutineText(ctx, title, 300).length * 18 * 1.22; const result = fitRoutineCardTitle(ctx, title, 300, height, 34); return { size: result.fontSize, drawingFont: ctx.font, contentPreserved: result.titleLines.join(" ") === title }; }); expect(boundary).toEqual({ size: 18, drawingFont: "18px RoutinePrint", contentPreserved: true }); }
  const first = d.getByTestId("routine-card").first(); await first.getByText("1. kartı düzenle", { exact: true }).click(); await first.getByLabel("1. kart başlığı", { exact: true }).fill("Güne birlikte merhaba"); await first.getByLabel("1. kart simgesi", { exact: true }).selectOption("group"); await first.getByLabel("1. kart süresi (dakika)", { exact: true }).fill("20"); await d.getByLabel("Başlangıç saati (isteğe bağlı)").fill("09:00"); await first.getByRole("button", { name: "1. kartı aşağı taşı", exact: true }).click(); await expect(d.getByTestId("routine-card").nth(1).locator("strong")).toHaveText("Güne birlikte merhaba");
  await d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true }).click(); await expect(d.getByText("Kayıtlı kart sürümü", { exact: true })).toBeVisible(); if (!production) expect(await count(page)).toBe(1); expect(await d.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await d.getByTestId("routine-card").first().scrollIntoViewIfNeeded(); await page.screenshot({ path: `${output}/routine-editor-390.png` }); await pdf(page, false, 1); await pdf(page, true, 6);
  await d.getByLabel("Gün düzeni", { exact: true }).selectOption("full"); await expect(d.getByTestId("routine-card")).toHaveCount(10); await expect(d.getByText("TASLAK · Bu değişiklikler henüz kaydedilmedi", { exact: true })).toBeVisible(); await d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true }).click(); await expect(d.getByText("Kayıtlı kart sürümü", { exact: true })).toBeVisible(); await page.reload(); d = await open(page); await expect(d.getByTestId("routine-card").nth(1).locator("strong")).toHaveText("Güne birlikte merhaba"); await d.getByLabel("Gün düzeni").selectOption("full"); await expect(d.getByTestId("routine-card")).toHaveCount(10); await expect(d.getByText("Kayıtlı kart sürümü", { exact: true })).toBeVisible();
});
test("IDB: eski kart taslağı ikinci sekme kaydını veya değişen sınıfı ezmez", async ({ page, context }) => {
  test.skip(production, "İkinci sekme ve sınıf değişimi geliştirme modülü fixture'ı kullanır."); await setup(page); const d = await open(page); const other = await context.newPage(); await other.goto("/classroom?native=1");
  await other.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const { seedDailyRoutineCardsFixture } = await import("/tests/fixtures/daily-routine-cards-fixture.mjs"); const store = new IndexedDbDataStore(); try { const s = await store.readSnapshot(), current = s.settings.find(r => r.settingType === "active-classroom-selection")!; await seedDailyRoutineCardsFixture(store, { scope: { academicYearId: current.academicYearId, classroomId: current.classroomId } }); } finally { store.close(); } });
  await d.getByRole("button", { name: "Kart kaynaklarını yenile", exact: true }).click(); await expect(d.getByRole("alert")).toContainText("Başka oturumda yeni kart sürümü"); await expect(d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true })).toBeDisabled(); expect(await count(page)).toBe(1);
  await other.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const store = new IndexedDbDataStore(); try { await store.transaction("readwrite", ["classrooms", "settings"], async tx => { const rooms = await tx.getAll("classrooms"), settings = await tx.getAll("settings"), current = settings.find(r => r.settingType === "active-classroom-selection")!, id = crypto.randomUUID(); await tx.putMany("classrooms", [{ ...rooms.find(r => r.id === current.classroomId)!, id, name: "Kurgu diğer sınıf" }]); await tx.putMany("settings", [{ ...current, classroomId: id }]); }); } finally { store.close(); } }); await d.getByRole("button", { name: "Kart kaynaklarını yenile", exact: true }).click(); await expect(d.getByRole("alert")).toContainText("Eski kart taslağının başka sınıfa yazılmaması"); await expect(d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true })).toHaveCount(0); expect(await count(page)).toBe(1); await other.close();
});
test("IDB: gerçek günlük akış on kart olur; kaynak revizyonu uyarır, tarihçe korunur", async ({ page }) => {
  test.skip(production, "Gerçek akış fixture'ı geliştirme modülü API'si kullanır."); await setup(page);
  await page.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const { routinePlan } = await import("/tests/fixtures/daily-routine-cards-fixture.mjs"); const store = new IndexedDbDataStore(); try { const s = await store.readSnapshot(), setting = s.settings.find(r => r.settingType === "active-classroom-selection")!; await store.transaction("readwrite", ["plans"], tx => tx.putMany("plans", [routinePlan({ academicYearId: setting.academicYearId, classroomId: setting.classroomId })])); } finally { store.close(); } });
  const d = await open(page); await d.getByLabel("Kayıtlı günlük akış", { exact: true }).selectOption({ label: "Kurgu öğretmen günlük akışı" }); await d.getByRole("button", { name: "Günlük akıştan taslak hazırla", exact: true }).click(); await expect(d.getByTestId("routine-card")).toHaveCount(10); await expect(d.getByTestId("routine-card").first()).toContainText("09:00–09:24"); await expect(d.getByTestId("routine-card").nth(7)).toHaveClass(/routine-card-hidden/u); await d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true }).click(); await expect(d.getByText("Kayıtlı kart sürümü", { exact: true })).toBeVisible();
  await page.clock.setFixedTime(new Date("2026-09-18T10:01:00.000Z")); await page.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const { reviseTeacherOwnedDailyFlow } = await import("/src/core/domain/teacher-owned-daily-flow.ts"); const store = new IndexedDbDataStore(); try { await store.transaction("readwrite", ["plans"], async tx => { const p = (await tx.getAll("plans"))[0]; const flow = p.teacherOwnedDailyFlow; await tx.putMany("plans", [{ ...p, updatedAt: "2026-09-18T10:00:00.000Z", teacherOwnedDailyFlow: reviseTeacherOwnedDailyFlow(flow, flow.blocks.map((b, i) => ({ ...b, title: i ? b.title : "Güncellenen karşılama" })), crypto.randomUUID(), new Date("2026-09-18T10:00:00.000Z")) }]); }); } finally { store.close(); } });
  await d.getByRole("button", { name: "Kart kaynaklarını yenile", exact: true }).click(); await expect(d.getByText(/Günlük akış kaynağı değişti veya kaldırıldı/u)).toBeVisible(); await expect(d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true })).toBeDisabled(); await d.getByLabel("Kayıtlı günlük akış", { exact: true }).selectOption({ label: "Kurgu öğretmen günlük akışı" }); await d.getByRole("button", { name: "Günlük akıştan taslak hazırla", exact: true }).click(); await d.getByRole("button", { name: "Rutin kartlarını kaydet", exact: true }).click(); await expect(d.getByText("Önceki kart sürümleri (2)", { exact: true })).toBeVisible(); await page.reload(); const reloaded = await open(page); await expect(reloaded.getByTestId("routine-card").first()).toContainText("Güncellenen karşılama"); expect(await count(page)).toBe(2);
});
