import { useEffect, useRef, useState } from "react";
import { KeyboardInput, useKeyboard } from "../../mobile";
import { civilDateInIstanbul } from "../../core/domain/attendance.ts";
import { resolveActiveClassroomScope, type ActiveClassroomScope } from "../../core/domain/classroom-scope.ts";
import { dailyRoutineCards, dailyRoutineHead, ROUTINE_ICONS, routineCardTimes, routineDailyPlans, routineDraft, routineSourceFromPlan, routineSourceState, type DailyRoutineCardRecord, type RoutineCard, type RoutineDayMode } from "../../core/domain/daily-routine-cards.ts";
import type { DataSnapshot } from "../../core/domain/model.ts";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { requestPdfDocument } from "../documents/pdf-preview-model.ts";
import { DAILY_ROUTINE_CHANGED_EVENT, readDailyRoutineSnapshot, saveDailyRoutineCards, type SaveDailyRoutineInput } from "./daily-routine-cards-service.ts";
import { RoutineIconDrawing, routineIconLabels } from "./routine-icons.tsx";
import { dailyRoutinePdfRecipe } from "./daily-routine-cards-document.ts";
import "./daily-routine-cards.css";
export interface DailyRoutineCardsWorkspaceProps { store: LocalDataStore; refreshKey?: unknown; disabled?: boolean; onChanged?(): void }
const Input = ({ label, value, type = "text", maxLength = 200, onChange }: { label: string; value: string; type?: string; maxLength?: number; onChange(value: string): void }) => <label>{label}<KeyboardInput aria-label={label} type={type} value={value} maxLength={maxLength} onChange={e => onChange(e.target.value)} /></label>;
export function DailyRoutineCardsWorkspace(props: DailyRoutineCardsWorkspaceProps) {
  const [snapshot, setSnapshot] = useState<DataSnapshot | null>(null), [revision, setRevision] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [date, setDate] = useState(civilDateInIstanbul(new Date())), [mode, setMode] = useState<RoutineDayMode>("short"), [editorVersion, setEditorVersion] = useState(0);
  const openedScope = useRef<ActiveClassroomScope | null>(null), requestSequence = useRef(0), keyboard = useKeyboard();
  useEffect(() => { if (busy) return; let alive = true; const request = ++requestSequence.current; void readDailyRoutineSnapshot(props.store).then(s => { if (alive && request === requestSequence.current) setSnapshot(s); }).catch(() => { if (alive) setError("Rutin kartları okunamadı."); }); return () => { alive = false; }; }, [props.store, props.refreshKey, revision, busy]);
  useEffect(() => { const update = () => setRevision(v => v + 1); window.addEventListener(DAILY_ROUTINE_CHANGED_EVENT, update); window.addEventListener("focus", update); return () => { window.removeEventListener(DAILY_ROUTINE_CHANGED_EVENT, update); window.removeEventListener("focus", update); }; }, []);
  const currentScope = snapshot ? resolveActiveClassroomScope(snapshot) : null; if (currentScope && !openedScope.current) openedScope.current = { ...currentScope }; const scope = openedScope.current;
  const changed = Boolean(scope && (!currentScope || currentScope.academicYearId !== scope.academicYearId || currentScope.classroomId !== scope.classroomId));
  async function save(draft: SaveDailyRoutineInput["draft"], expectedEventId: string | null) {
    if (!scope || changed || busy || props.disabled) return; keyboard.hide(); setBusy(true); setError(""); setMessage("");
    try { await saveDailyRoutineCards(props.store, { scope, expectedEventId, draft }); const request = ++requestSequence.current, latest = await readDailyRoutineSnapshot(props.store); if (request === requestSequence.current) setSnapshot(latest); setEditorVersion(v => v + 1); setMessage("Rutin kartları yeni sürüm olarak bu cihaza kaydedildi."); props.onChanged?.(); }
    catch (e) { setError(e instanceof Error ? e.message : "Kartlar kaydedilemedi. Önceki sürüm korundu."); } finally { setBusy(false); }
  }
  async function pdf(record: DailyRoutineCardRecord) { keyboard.hide(); setError(""); try { await requestPdfDocument(dailyRoutinePdfRecipe(record, String(snapshot?.classrooms.find(c => c.id === scope?.classroomId)?.name ?? "Sınıf")), routineSourceState(snapshot!, record.workflow.source) === "changed" ? "Günlük akış daha sonra değişti. Bu PDF seçtiğiniz kayıtlı kart sürümünü gösterir." : undefined); } catch (e) { setError(e instanceof Error ? e.message : "Kart PDF hazırlanamadı."); } }
  if (!snapshot) return <p role="status">Görsel rutin kartları hazırlanıyor…{error}</p>;
  if (changed) return <p role="alert">Etkin sınıf veya eğitim yılı değişti. Eski kart taslağının başka sınıfa yazılmaması için bu alanı kapatıp yeniden açın.</p>;
  if (!scope) return <p>Rutin kartları için önce bir sınıf seçin.</p>;
  const head = dailyRoutineHead(snapshot, scope, date, mode), history = dailyRoutineCards(snapshot, scope).filter(r => r.workflow.routineOn === date && r.workflow.dayMode === mode);
  return <div className="routine-workspace" data-testid="daily-routine-cards-workspace"><h3>Görsel günlük rutin kartları</h3><p>Çocukların günün sırasını görmesi için büyük simgeli kartlar. Kısa ve tam gün sürümleri ayrı saklanır. Kart düzenlemek günlük planınızı değiştirmez.</p>
    <p className="routine-context">{String(snapshot.classrooms.find(c => c.id === scope.classroomId)?.name ?? "Sınıf")} · İstanbul saati</p>
    {error && <p role="alert" className="routine-error">{error}</p>}{message && <p role="status" className="routine-success">{message}</p>}
    <fieldset disabled={busy || props.disabled} className="routine-fieldset"><div className="routine-row"><Input label="Rutin kartlarının günü" value={date} type="date" onChange={v => { keyboard.hide(); setDate(v); setMessage(""); }} /><label>Gün düzeni<select aria-label="Gün düzeni" value={mode} onChange={e => { keyboard.hide(); setMode(e.target.value as RoutineDayMode); setMessage(""); }}><option value="short">Kısa gün</option><option value="full">Tam gün</option></select></label></div><p className="routine-context">Günü veya gün düzenini değiştirmek kaydedilmemiş taslağı kapatır.</p>
    <button type="button" onClick={() => setRevision(v => v + 1)}>Kart kaynaklarını yenile</button>
    <RoutineEditor key={`${date}:${mode}:${editorVersion}`} snapshot={snapshot} scope={scope} date={date} mode={mode} head={head} save={save} />
    {head && <><button type="button" className="sheet-primary" onClick={() => void pdf(head)}>Kayıtlı kartları PDF önizle</button><details><summary>Önceki kart sürümleri ({history.length})</summary><ol>{history.map((r, i) => <li key={r.id}><strong>Sürüm {i + 1} · {r.workflow.title}</strong><p>{new Date(r.createdAt).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul" })} · {r.workflow.cards.filter(c => c.visible).length} görünür kart · {r.workflow.source ? `Akış sürümü ${r.workflow.source.flowRevisionNumber}` : "Manuel kartlar"}</p><button type="button" onClick={() => void pdf(r)}>Sürüm {i + 1} PDF</button></li>)}</ol></details></>}
    </fieldset>{busy && <p role="status">Kartlar kaydediliyor…</p>}
  </div>;
}
function RoutineEditor({ snapshot, scope, date, mode, head, save }: { snapshot: DataSnapshot; scope: ActiveClassroomScope; date: string; mode: RoutineDayMode; head?: DailyRoutineCardRecord; save(draft: SaveDailyRoutineInput["draft"], expected: string | null): Promise<void> }) {
  const [expected] = useState(head?.id ?? null), [draft, setDraft] = useState<SaveDailyRoutineInput["draft"]>(() => head ? structuredClone(head.workflow) : { routineOn: date, dayMode: mode, title: "Günümüzün sırası", source: null, ...routineDraft(mode) }), [dirty, setDirty] = useState(!head), [planId, setPlanId] = useState("");
  const plans = routineDailyPlans(snapshot, scope, date), sourceState = routineSourceState(snapshot, draft.source), latest = dailyRoutineHead(snapshot, scope, date, mode), stale = (latest?.id ?? null) !== expected;
  function change(patch: Partial<typeof draft>) { setDirty(true); setDraft(d => ({ ...d, ...patch })); }
  function cardChange(id: string, patch: Partial<RoutineCard>) { change({ cards: draft.cards.map(c => c.id === id ? { ...c, ...patch } : c) }); }
  function move(index: number, direction: number) { const cards = [...draft.cards]; [cards[index], cards[index + direction]] = [cards[index + direction]!, cards[index]!]; change({ cards: cards.map((c, i) => ({ ...c, order: i + 1 })) }); }
  const times = routineCardTimes(draft);
  return <section aria-label="Rutin kartı düzenleyici"><p className={dirty ? "routine-warning" : "routine-success"} role="status">{dirty ? "TASLAK · Bu değişiklikler henüz kaydedilmedi" : "Kayıtlı kart sürümü"}</p>
    {stale && <p role="alert" className="routine-warning">Başka oturumda yeni kart sürümü kaydedildi. Bu alanı kapatıp güncel sürümü yeniden açın.</p>}
    {plans.length ? <div className="routine-source"><label>Kayıtlı günlük akış<select aria-label="Kayıtlı günlük akış" value={planId} onChange={e => setPlanId(e.target.value)}><option value="">Akış seçin</option>{plans.map(p => <option value={p.id} key={p.id}>{String(p.title ?? "Günlük akış")}</option>)}</select></label><button type="button" disabled={!planId} onClick={() => { const source = routineSourceFromPlan(plans.find(p => p.id === planId)!); change({ source, ...routineDraft(mode, source) }); }}>Günlük akıştan taslak hazırla</button><p>Bu seçim kart taslağını seçilen akışın bütün bölümleriyle yeniden kurar. Önceki kayıtlı sürümler korunur.</p></div> : <p className="routine-warning">Bu güne ait kayıtlı öğretmen günlük akışı yok. Görünen kartlar düzenlenebilir bir taslaktır; saat ve süre varsayılmaz.</p>}
    {draft.source && <p className={sourceState === "current" ? "routine-context" : "routine-warning"} role="status">{sourceState === "current" ? "Günlük akış kaynağı güncel" : "Günlük akış kaynağı değişti veya kaldırıldı. Kaynaktan yeni taslak hazırlayın."} · Kaynak sürümü {draft.source.flowRevisionNumber} · {new Date(draft.source.planUpdatedAt).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul" })}. Gizlenen veya akışta atlanan kartların süreleri kaynak zaman çizgisinde korunur.</p>}
    <Input label="Kart takımı başlığı" value={draft.title} maxLength={150} onChange={title => change({ title })} /><Input label="Başlangıç saati (isteğe bağlı)" value={draft.startTime ?? ""} type="time" onChange={v => change({ startTime: v || null })} /><p className="routine-context">Bilinmeyen süre boş kalır; sonraki kartlara tahminî saat yazılmaz.</p>
    <ol className="routine-card-list">{times.map(({ card, startTime, endTime }, index) => <li key={card.id} className={card.visible ? "routine-card" : "routine-card routine-card-hidden"} data-testid="routine-card"><div className="routine-card-preview"><span className="routine-number">{index + 1}</span><RoutineIconDrawing icon={card.icon} /><strong>{card.title || "Başlık girin"}</strong><span>{startTime && endTime ? `${startTime}–${endTime}` : card.durationMinutes ? `${card.durationMinutes} dakika` : "Saat belirtilmedi"}</span></div>
      <details><summary>{index + 1}. kartı düzenle</summary><Input label={`${index + 1}. kart başlığı`} value={card.title} onChange={title => cardChange(card.id, { title })} /><label>Simge<select aria-label={`${index + 1}. kart simgesi`} value={card.icon} onChange={e => cardChange(card.id, { icon: e.target.value as RoutineCard["icon"] })}>{ROUTINE_ICONS.map(icon => <option key={icon} value={icon}>{routineIconLabels[icon]}</option>)}</select></label><Input label={`${index + 1}. kart süresi (dakika)`} type="number" value={card.durationMinutes?.toString() ?? ""} onChange={v => cardChange(card.id, { durationMinutes: v === "" ? null : Number(v) })} /><label>Akış durumu<select aria-label={`${index + 1}. kart durumu`} value={card.status} onChange={e => cardChange(card.id, { status: e.target.value as RoutineCard["status"] })}><option value="planned">Planlı</option><option value="optional">İsteğe bağlı</option><option value="skipped">Akışta atlandı</option></select></label><button type="button" role="checkbox" aria-checked={card.visible} onClick={() => cardChange(card.id, { visible: !card.visible })}>{card.visible ? "Çıktıda görünür" : "Çıktıda gizli"}</button><div className="routine-row"><button type="button" aria-label={`${index + 1}. kartı yukarı taşı`} disabled={index === 0} onClick={() => move(index, -1)}>↑ Yukarı taşı</button><button type="button" aria-label={`${index + 1}. kartı aşağı taşı`} disabled={index === draft.cards.length - 1} onClick={() => move(index, 1)}>↓ Aşağı taşı</button></div></details></li>)}</ol>
    <button type="button" disabled={draft.cards.length >= 24} onClick={() => change({ cards: [...draft.cards, { id: crypto.randomUUID(), order: draft.cards.length + 1, title: "Yeni rutin kartı", icon: "circle", visible: true, status: "planned", durationMinutes: null, sourceBlockId: null }] })}>Bir kart ekle</button>
    <button type="button" className="sheet-primary" disabled={!dirty || stale || (sourceState !== "current" && sourceState !== "manual")} onClick={() => void save(draft, expected)}>Rutin kartlarını kaydet</button>
  </section>;
}
