import {test,expect} from "@playwright/test";
test.use({viewport:{width:320,height:844}});test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date("2026-09-12T09:00:00.000Z"));});
test("real feedback schedules exact child and meeting offline; retry, full agenda, restore and delete stay linked",async({page,context})=>{
 test.setTimeout(90000);await page.goto("/tests/family-response-board-fixture.html");const board=page.getByRole("region",{name:"Aile dönüş panosu",exact:true});await expect(board.getByText("Aile yanıtı henüz kaydedilmedi.",{exact:true})).toBeVisible();await board.getByRole("button",{name:"Bu aile yanıtıyla ilerle",exact:true}).click();const next=board.getByRole("region",{name:"Seçili aile yanıtının sonraki adımı",exact:true});await context.setOffline(true);
 const plan=next.getByRole("button",{name:"Kaynak etkinliği bu güne yeniden planla",exact:true});await page.evaluate(()=>(window as any).familyResponseTest.setDisabled(true));await expect(plan).toBeDisabled();await page.evaluate(()=>(window as any).familyResponseTest.setDisabled(false));await expect(plan).toBeEnabled();const readsBefore=await page.evaluate(()=>(window as any).familyResponseTest.readCount());await plan.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await expect(board.getByRole("button",{name:"Kayıtlı planı aç",exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).familyResponseTest.readCount())-readsBefore).toBe(1);await expect(next.getByLabel("Sonraki adım günü",{exact:true})).toHaveValue("2026-09-15");await next.getByLabel("Sonraki adım günü",{exact:true}).fill("2026-09-14");await expect(plan).toBeDisabled();await next.getByRole("button",{name:"2026-09-15 · Boş güne yerleştir",exact:true}).click();await expect(next.getByLabel("Sonraki adım günü",{exact:true})).toHaveValue("2026-09-15");
 await next.getByLabel("Görüşülecek kayıtlı yakın",{exact:true}).selectOption({label:"Kurgu Aile Bir · Anne"});await next.getByLabel("Yeni görüşmenin saati",{exact:true}).selectOption({index:1});await next.getByRole("button",{name:"Bu yanıtla veli görüşmesi oluştur",exact:true}).click();await expect(board.getByRole("button",{name:"Kayıtlı görüşmeyi aç",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await context.setOffline(false);await page.reload();await expect(board.getByRole("button",{name:"Kayıtlı planı aç",exact:true})).toBeVisible();
 const result=await page.evaluate(async()=>{const {store}=(window as any).familyResponseTest;const {homeGameCards}=await import("/src/features/home-game-cards/home-game-card-model.ts");const {familyMeetingFormModel}=await import("/src/features/family-engagement/family-meeting-form-service.ts");const {BackupService}=await import("/src/core/backup/backup-service.ts");const {IndexedDbDataStore}=await import("/src/core/repository/indexed-db.ts");const {previewPermanentStudentDeletion,permanentlyDeleteStudent}=await import("/src/features/students/student-lifecycle.ts");const snapshot=await store.readSnapshot(),actions=homeGameCards(snapshot).filter(r=>r.workflow.kind==="response-action"),planned=actions.find(r=>r.workflow.action==="plan"),meeting=actions.find(r=>r.workflow.action==="meeting"),activity=snapshot.activities.find(a=>a.id===planned.workflow.activityId),form=familyMeetingFormModel(snapshot,meeting.workflow.appointmentId,new Date("2026-09-12T09:00:00Z"));const now=new Date("2026-09-12T10:00:00Z");const backup=await new BackupService(store,{appVersion:"0.43.0",clock:()=>now}).exportBackup();const restored=new IndexedDbDataStore({databaseName:`response-restore-${crypto.randomUUID()}`});await new BackupService(restored,{appVersion:"0.43.0",clock:()=>now}).restoreBackup(backup,{mode:"replace",createRecoverySnapshot:false});const restoredCount=homeGameCards(await restored.readSnapshot()).length;const impact=previewPermanentStudentDeletion(await restored.readSnapshot(),planned.studentId);await permanentlyDeleteStudent(restored,{studentId:planned.studentId,confirmationName:impact.displayName,expectedFingerprint:impact.fingerprint,now});return{actions:actions.length,assigned:activity.studentIds,status:activity.status,student:planned.studentId,agenda:form.agenda,meeting:form.meeting,restoredCount,after:homeGameCards(await restored.readSnapshot()).map(r=>r.workflow.kind)};});
 expect(result.actions).toBe(2);expect(result.assigned).toEqual([result.student]);expect(result.status).toBe("planned");expect(result.agenda.join("\n")).toContain("Çocuğum resimlerin sırasını değiştirerek yeni bir hikâye anlattı.");expect(result.meeting).toBeNull();expect(result.restoredCount).toBe(5);expect(result.after).toEqual(["prepared"]);
});
test("empty board has an actionable card preparation button",async({page})=>{await page.goto("/tests/family-response-board-fixture.html?empty=1");await page.getByRole("button",{name:"Aile oyun kartı hazırla",exact:true}).click();await expect(page.getByLabel("Açılan sonuç")).toHaveText("prepare-card");});

test("stale, cross-child and injected final-write failure stay atomic; existing meeting keeps full long agenda",async({page})=>{
 await page.goto("/tests/family-response-board-fixture.html");const result=await page.evaluate(async()=>{
  const {familyResponseFixture}=await import("/tests/fixtures/family-response-fixture.mjs");const {applyFamilyResponse}=await import("/src/features/family-response-board/family-response-board-service.ts");const {familyResponseBoardModel}=await import("/src/features/family-response-board/family-response-board-model.ts");const {familyMeetingFormModel}=await import("/src/features/family-engagement/family-meeting-form-service.ts");const {saveHomeGameFeedback}=await import("/src/features/home-game-cards/home-game-card-service.ts");const {assertHomeGameCardRelationships}=await import("/src/features/home-game-cards/home-game-card-model.ts");const now=new Date("2026-09-12T09:00:00Z");const f=await familyResponseFixture(),before=await f.store.readSnapshot(),model=familyResponseBoardModel(before,undefined,now),request={feedbackId:f.feedback.id,action:"meeting",day:model.selectedDay,contactId:f.contactId,startTime:model.slots[0].startTime};
  let stale=false;try{await applyFamilyResponse(f.store,{request,expectedFingerprint:"stale",now});}catch{stale=true;}
  const original=f.store.transaction.bind(f.store);f.store.transaction=(mode,names,task)=>original(mode,names,t=>task({...t,putMany:async(name,rows)=>{if(rows.some(r=>r.workflow?.kind==="response-action"))throw new Error("Kurgu final disk hatası");return t.putMany(name,rows);}}));let failed=false;try{await applyFamilyResponse(f.store,{request,expectedFingerprint:model.fingerprint,now});}catch{failed=true;}const unchanged=JSON.stringify(before)===JSON.stringify(await f.store.readSnapshot());f.store.transaction=original;
  const receipt=await applyFamilyResponse(f.store,{request,expectedFingerprint:model.fingerprint,now});const retry=await applyFamilyResponse(f.store,{request,expectedFingerprint:model.fingerprint,now});
  const long="Tam gerçek aile yanıtı kesilmeden korunur. ".repeat(40);const feedback=(await saveHomeGameFeedback(f.store,{cardId:f.cards[0].id,receivedOn:"2026-09-12",source:"written",text:long,now}))[0];const newer=familyResponseBoardModel(await f.store.readSnapshot(),undefined,now);const second=await applyFamilyResponse(f.store,{request:{...request,feedbackId:feedback.id,appointmentId:receipt.workflow.appointmentId},expectedFingerprint:newer.fingerprint,now});const form=familyMeetingFormModel(await f.store.readSnapshot(),second.workflow.appointmentId,now);const malformed=await f.store.readSnapshot();malformed.settings.find(r=>r.id===second.id).studentId=f.otherStudentId;let crossRejected=false;try{assertHomeGameCardRelationships(malformed);}catch{crossRejected=true;}
  return{stale,failed,unchanged,reused:receipt.id===retry.id,sameMeeting:receipt.workflow.appointmentId===second.workflow.appointmentId,full:form.agenda.join("\n").includes(long),crossRejected,otherNameLeaked:form.agenda.join("\n").includes("Kurgu Aile İki")};
 });expect(result).toEqual({stale:true,failed:true,unchanged:true,reused:true,sameMeeting:true,full:true,crossRejected:true,otherNameLeaked:false});
});


test("missing contact offers the exact child's profile action",async({page})=>{await page.goto("/tests/family-response-board-fixture.html");await page.waitForFunction(()=>!!(window as any).familyResponseTest);const studentId=await page.evaluate(async()=>{const {store}=(window as any).familyResponseTest;const snapshot=await store.readSnapshot();const child=snapshot.students[0];await store.transaction("readwrite",["students"],async tx=>tx.putMany("students",[{...child,contacts:[]}]));return child.id;});await page.reload();await page.getByRole("button",{name:"Bu aile yanıtıyla ilerle",exact:true}).click();await page.getByRole("button",{name:"Yakın bilgilerini aç",exact:true}).click();await expect(page.getByLabel("Açılan sonuç")).toHaveText(`student:${studentId}`);});


