import { expect,test } from "@playwright/test";
import { mkdir,writeFile } from "node:fs/promises";
test("Veli formu gerçek sonuç görev ve kaynağı atomik kaydeder; tekrar ve sahte/eskimiş istek yazmaz",async({page})=>{
  test.setTimeout(90_000);await page.goto("/tests/runtime-fixture.html");
  const answer=await page.evaluate(async()=>{
    const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/family-meeting-form-fixture.mjs"),service=await import("/src/features/family-engagement/family-meeting-form-service.ts"),domain=await import("/src/core/domain/teacher-followup.ts");
    const store=new core.IndexedDbDataStore({databaseName:`meeting-atomic-${crypto.randomUUID()}`}),f=await fx.makeFamilyMeetingFixture(store),before=await store.readSnapshot();
    const rejected=[];for(const bad of [{...f.input,confirmedOccurred:false},{...f.input,observationIds:[crypto.randomUUID()]},{...f.input,actualAtUtc:"2026-09-22T13:00:00.000Z"},{...f.input,expectedFingerprint:"stale"}]){try{await service.saveFamilyMeetingForm(store,bad);rejected.push(false);}catch{rejected.push(true);}}
    let writes=0,rollback=false;const injected={readSnapshot:()=>store.readSnapshot(),close(){},transaction:(mode:any,names:any,task:any)=>store.transaction(mode,names,(tx:any)=>task({getAll:(name:any)=>tx.getAll(name),clear:(name:any)=>tx.clear(name),putMany:async(name:any,rows:any)=>{await tx.putMany(name,rows);if(++writes===3)throw new Error("Kurgu görev yazım kesintisi");}}))};
    try{await service.saveFamilyMeetingForm(injected,f.input);}catch{rollback=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot());}
    const saved=await service.saveFamilyMeetingForm(store,f.input),after=await store.readSnapshot(),repeat=await service.saveFamilyMeetingForm(store,f.input),unchanged=core.canonicalJson(after)===core.canonicalJson(await store.readSnapshot());
    const model=await service.loadFamilyMeetingForm(store,f.appointmentId,f.now);await service.completeFamilyMeetingTask(store,{appointmentId:f.appointmentId,taskId:model.tasks[0].id,expectedFingerprint:model.fingerprint,now:f.now});
    const reminders=domain.followupReminders(domain.teacherFollowups(await store.readSnapshot()),"2026-09-29");
    const answer={rejected,writes,rollback,taskCount:saved.taskIds.length,repeat:repeat.alreadyCompleted,unchanged,rawPreserved:core.canonicalJson(before.observations)===core.canonicalJson(after.observations),taskReminders:reminders.filter((r:any)=>model.tasks.some((t:any)=>t.id===r.id)).length,meetingReminder:reminders.some((r:any)=>r.id===saved.meetingId)};store.close();return answer;
  });expect(answer).toEqual({rejected:[true,true,true,true],writes:3,rollback:true,taskCount:2,repeat:true,unchanged:true,rawPreserved:true,taskReminders:1,meetingReminder:true});
});
test("Veli formu şifreli yedekten eksiksiz döner; kalıcı silme tüm görev/form kaynağını kaldırır",async({page})=>{
  test.setTimeout(90_000);await page.goto("/tests/runtime-fixture.html");const answer=await page.evaluate(async()=>{
    const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/family-meeting-form-fixture.mjs"),service=await import("/src/features/family-engagement/family-meeting-form-service.ts"),encryption=await import("/src/core/backup/encrypted-backup.ts"),lifecycle=await import("/src/features/students/student-lifecycle.ts");
    const store=new core.IndexedDbDataStore({databaseName:`meeting-backup-${crypto.randomUUID()}`}),f=await fx.makeFamilyMeetingFixture(store);await service.saveFamilyMeetingForm(store,f.input);
    const options={appVersion:"0.41.0",clock:()=>new Date("2026-09-23T07:00:00.000Z")},backup=new core.BackupService(store,options),envelope=await backup.exportBackup();await backup.parseAndVerifyBackup(envelope);const password="Kurgu-veli-formu-parolasi!",encrypted=backup.serializeEncryptedBackup(await encryption.encryptBackupText(core.canonicalJson(envelope),{appVersion:"0.41.0",createdAt:envelope.manifest.createdAt},password));
    const target=new core.IndexedDbDataStore({databaseName:`meeting-restore-${crypto.randomUUID()}`});await new core.BackupService(target,options).restoreEncryptedBackup(encrypted,password,{mode:"replace",createRecoverySnapshot:false});const roundtrip=core.canonicalJson(await store.readSnapshot())===core.canonicalJson(await target.readSnapshot());
    const preview=lifecycle.previewPermanentStudentDeletion(await target.readSnapshot(),f.studentId);await lifecycle.permanentlyDeleteStudent(target,{studentId:f.studentId,confirmationName:preview.displayName,expectedFingerprint:preview.fingerprint,now:new Date("2026-09-23T06:00:00.000Z")});const after=await target.readSnapshot();const restoredBackup=new core.BackupService(target,options);await restoredBackup.parseAndVerifyBackup(await restoredBackup.exportBackup());
    const answer={roundtrip,removed:!core.canonicalJson(after).includes(f.studentId),forms:after.settings.filter((r:any)=>["family-meeting-form","family-meeting-task","family-task-check"].includes(r.workflow?.kind)).length,other:after.students.some(s=>s.id===f.otherStudentId)};store.close();target.close();return answer;
  });expect(answer).toEqual({roundtrip:true,removed:true,forms:0,other:true});
});
test("Gerçek veli formu üreticileri düzenlenebilir Word ve görsel PDF üretir",async({page})=>{
  test.setTimeout(90_000);await page.goto("/tests/runtime-fixture.html");const files=await page.evaluate(async()=>{
    const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/family-meeting-form-fixture.mjs"),service=await import("/src/features/family-engagement/family-meeting-form-service.ts"),documents=await import("/src/features/family-engagement/family-meeting-form-document.ts");
    const store=new core.IndexedDbDataStore({databaseName:`meeting-artifacts-${crypto.randomUUID()}`}),f=await fx.makeFamilyMeetingFixture(store),prep=await service.loadFamilyMeetingForm(store,f.appointmentId,f.now);await service.saveFamilyMeetingForm(store,f.input);const model=await service.loadFamilyMeetingForm(store,f.appointmentId,f.now);
    const result=[];for(const [name,m]of[["hazirlik",prep],["sonuc",model]] as const){const pdf=await documents.createFamilyMeetingFormPdf(m),word=documents.createFamilyMeetingFormDocx(m);result.push({name,pdf:Array.from(pdf),word:Array.from(word)});}store.close();return result;
  });await mkdir("output/family-meeting-form-qa",{recursive:true});for(const file of files){expect(file.pdf.slice(0,5)).toEqual([37,80,68,70,45]);expect(file.word.slice(0,2)).toEqual([80,75]);await writeFile(`output/family-meeting-form-qa/veli-gorusmesi-${file.name}.pdf`,Buffer.from(file.pdf));await writeFile(`output/family-meeting-form-qa/veli-gorusmesi-${file.name}.docx`,Buffer.from(file.word));}
});
