import { useEffect, useRef, useState } from "react";
import { KeyboardInput, KeyboardTextarea, useKeyboard } from "../../mobile";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { familyLocalToUtc } from "../../core/domain/family-engagement.ts";
import { civilDateInIstanbul } from "../../core/domain/attendance.ts";
import { addDays } from "../action-center/action-center-model.ts";
import { requestPdfDocument } from "../documents/pdf-preview-model.ts";
import { familyMeetingFormRecipe } from "./family-meeting-form-document.ts";
import { completeFamilyMeetingTask, loadFamilyMeetingForm, saveFamilyMeetingForm, type FamilyMeetingFormModel, type FamilyMeetingTaskDraft } from "./family-meeting-form-service.ts";
import "./family-meeting-form.css";

export interface FamilyMeetingFormPanelProps { store: LocalDataStore; appointmentId: string; refreshKey?: unknown; disabled?: boolean; onChanged?: () => unknown | Promise<unknown>; onClose?: () => void }
export function FamilyMeetingFormPanel({ store, appointmentId, refreshKey, disabled = false, onChanged, onClose }: FamilyMeetingFormPanelProps) {
  const [model,setModel] = useState<FamilyMeetingFormModel | null>(null), [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [revision,setRevision] = useState(0), [error,setError] = useState(""), [message,setMessage] = useState("");
  const [participants,setParticipants] = useState(""), [discussion,setDiscussion] = useState(""), [decision,setDecision] = useState(""), [time,setTime] = useState(""), [followup,setFollowup] = useState(""), [observations,setObservations] = useState<string[]>([]), [tasks,setTasks] = useState<FamilyMeetingTaskDraft[]>([]);
  const generation = useRef(0), scopeGeneration = useRef(0), initialized = useRef(""), loadedEvent = useRef(""), lock = useRef(false), keyboard = useKeyboard();
  const current = useRef({ store, appointmentId, disabled }); current.current = { store, appointmentId, disabled };
  useEffect(() => { scopeGeneration.current++; initialized.current = ""; loadedEvent.current = ""; setMessage(""); setDiscussion(""); setDecision(""); setFollowup(""); setTasks([]);   return () => { scopeGeneration.current++; }; }, [store,appointmentId]);
  useEffect(() => { const version = ++generation.current; setLoading(true); setModel(null); void loadFamilyMeetingForm(store,appointmentId).then(value => { if (version !== generation.current) return; setModel(value); setLoading(false); setError(""); if (loadedEvent.current && loadedEvent.current !== value.appointmentEventId && !value.meeting) {   setTime(value.appointment.startTime); setError("Randevu değişti. Yeni tarih ve saati inceleyip gerçek görüşme bilgisini yeniden doğrulayın."); } loadedEvent.current = value.appointmentEventId; if (initialized.current !== appointmentId) { initialized.current = appointmentId; setParticipants(value.appointment.contact.name || value.appointment.contact.relationship); setTime(value.appointment.startTime); setObservations(value.observations.filter(o => o.selected).map(o => o.id)); } }).catch(cause => { if (version === generation.current) { setLoading(false); setError(cause instanceof Error ? cause.message : "Görüşme formu okunamadı."); } }); return () => { generation.current++; }; }, [store,appointmentId,refreshKey,revision]);
  const run = async (task: () => Promise<unknown>, success: string) => {
    if (disabled || lock.current || loading) return; lock.current = true; setBusy(true); setError(""); setMessage(""); keyboard.hide(); const scope = scopeGeneration.current; let committed = false;
    try { await task(); committed = true; if (scope === scopeGeneration.current) { setMessage(success); setLoading(true); setModel(null); } try { await onChanged?.(); } catch { if (scope === scopeGeneration.current) setError("Görüşme kaydedildi; üst görünüm henüz yenilenemedi."); } }
    catch(cause) { if (scope === scopeGeneration.current) setError(cause instanceof Error ? cause.message : "Kayıt tamamlanamadı."); }
    finally { lock.current = false; setBusy(false); if (scope === scopeGeneration.current && committed) setRevision(v => v+1); }
  };
  const blocked = disabled || busy || loading, today = civilDateInIstanbul(new Date());
  const save = () => { if (!model) return; void run(() => saveFamilyMeetingForm(store, { appointmentId, expectedFingerprint:model.fingerprint, actualAtUtc:familyLocalToUtc(model.appointment.scheduledOn,time), participants, discussion, decision, followupOn:followup || null, observationIds:observations, tasks, confirmedOccurred:true, tasksConfirmed:true }), "Görüşme sonucu, görevler ve takip tarihi birlikte kaydedildi."); };
  const output = async () => {
    if (disabled || lock.current || loading) return;
    lock.current = true; setBusy(true); keyboard.hide(); setError(""); const scope = scopeGeneration.current, read = generation.current;
    try {
      const recipe = await familyMeetingFormRecipe(store,appointmentId,observations);
      if (scope !== scopeGeneration.current || read !== generation.current || current.current.disabled || current.current.store !== store || current.current.appointmentId !== appointmentId) return;
      await requestPdfDocument(recipe);
    } catch(cause) { if (scope === scopeGeneration.current) setError(cause instanceof Error ? cause.message : "Belge hazırlanamadı."); }
    finally { lock.current = false; setBusy(false); }
  };
  const addTask = (owner: "teacher" | "family") => { setTasks(current => [...current, { owner, text:owner === "teacher" ? "Bir sonraki takipte kayıtlı destek kararını ve yeni gözlemleri birlikte incelemek." : "Evdeki oyun gözlemlerini bir sonraki görüşmede paylaşmak.", dueOn:followup || addDays(today,7) }]);  };
  return <section className="family-meeting-form" aria-label="Veli görüşmesi gündem ve sonuç formu"><header><h3>Veli görüşmesi gündem ve sonuç formu</h3>{onClose && <button type="button" onClick={() => { keyboard.hide(); onClose(); }}>Formu kapat</button>}</header>
    {loading && <p role="status">Kayıtlı görüşme ve kaynakları yükleniyor…</p>}{error && <div role="alert"><p>{error}</p><button type="button" disabled={busy} onClick={() => setRevision(v=>v+1)}>Güncel formu yeniden yükle</button></div>}{message && <p role="status" className="family-meeting-saved">{message}</p>}
    {model && <><p className="family-meeting-context"><strong>{model.studentName}</strong> · {model.classroomName}<br/>Planlanan: {model.appointment.scheduledOn} · {model.appointment.startTime}–{model.appointment.endTime} · {model.appointment.location}{model.meeting && <><br/>Gerçek görüşme: {new Intl.DateTimeFormat("tr-TR",{timeZone:"Europe/Istanbul",dateStyle:"short",timeStyle:"short"}).format(new Date(model.meeting.actualAtUtc))}</>}</p>
      <div className="family-meeting-columns"><section><h4>Kayıtlı gündem ve kaynak gözlemler</h4>{model.agenda.map((text,i)=><p key={i}>{text}</p>)}{model.observations.length === 0 && <p>Bu görüşme için seçilebilir kayıtlı gözlem yok.</p>}{model.observations.map(o=><label className="family-meeting-source" key={o.id}>{!model.meeting && <input type="checkbox" disabled={blocked} checked={observations.includes(o.id)} onChange={e=>setObservations(ids=>e.target.checked?[...ids,o.id]:ids.filter(id=>id!==o.id))}/>}<span><small>{o.civilDate}</small><span className="family-meeting-raw">{o.rawText}</span></span></label>)}</section>
      <section><h4>Öğretmenin gerçek görüşme notları</h4>{model.meeting ? <><p><b>Katılanlar:</b> {model.meeting.participants}</p><p className="family-meeting-raw">{model.meeting.discussion}</p><h4>Birlikte alınan karar</h4><p className="family-meeting-raw">{model.meeting.decision}</p></> : <fieldset disabled={blocked || !model.canRecord}><label>Gerçek görüşme saati<KeyboardInput type="time" aria-label="Gerçek görüşme saati" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Gerçek katılımcılar<KeyboardInput aria-label="Gerçek katılımcılar" value={participants} maxLength={500} onChange={e=>setParticipants(e.target.value)}/></label><label>Gerçekte görüşülenler<KeyboardTextarea aria-label="Gerçekte görüşülenler" value={discussion} maxLength={4000} onChange={e=>setDiscussion(e.target.value)}/></label><label>Birlikte alınan karar<KeyboardTextarea aria-label="Birlikte alınan karar" value={decision} maxLength={4000} onChange={e=>setDecision(e.target.value)}/></label></fieldset>}</section></div>
      <section><h4>Aile ve öğretmen görevleri</h4>{model.meeting ? <>{model.tasks.length===0 && <p>Bu görüşmede görev kaydı yok.</p>}{model.tasks.map(t=><article className="family-meeting-task" key={t.id}><strong>{t.owner === "family" ? "Aile" : "Öğretmen"} · {t.dueOn}</strong><p>{t.text}</p>{t.completed ? <p>Tamamlandığı öğretmen tarafından kaydedildi.</p> : <button type="button" disabled={blocked} onClick={()=>void run(()=>completeFamilyMeetingTask(store,{appointmentId,taskId:t.id,expectedFingerprint:model.fingerprint}),"Görevin tamamlandığı kaydedildi.")}>{t.owner === "family" ? "Aile görevini tamamlandı olarak kaydet" : "Öğretmen görevini tamamla"}</button>}</article>)}<p>Ortak takip: {model.meeting.followupOn || "Belirlenmedi"}</p></> : <fieldset disabled={blocked || !model.canRecord}><p>Aşağıdaki öneriyi ancak görüşmede kararlaştırıldıysa ekleyin; görev metnini düzenleyebilirsiniz.</p><div className="family-meeting-buttons"><button type="button" disabled={tasks.length>=20} onClick={()=>addTask("family")}>Ailenin gözlemlerini paylaşma görevini ekle</button><button type="button" disabled={tasks.length>=20} onClick={()=>addTask("teacher")}>Öğretmenin destek takibi görevini ekle</button></div>{tasks.map((task,i)=><div className="family-meeting-task" key={i}><label>Sorumlu<select aria-label={`Görev ${i+1} sorumlusu`} value={task.owner} onChange={e=>{setTasks(items=>items.map((t,j)=>j===i?{...t,owner:e.target.value as "family"|"teacher"}:t));}}><option value="family">Aile</option><option value="teacher">Öğretmen</option></select></label><label>Kararlaştırılan görev<KeyboardTextarea aria-label={`Görev ${i+1} metni`} value={task.text} maxLength={1000} onChange={e=>{setTasks(items=>items.map((t,j)=>j===i?{...t,text:e.target.value}:t));}}/></label><label>Görev takip tarihi<KeyboardInput type="date" aria-label={`Görev ${i+1} takip tarihi`} value={task.dueOn} min={today} onChange={e=>{setTasks(items=>items.map((t,j)=>j===i?{...t,dueOn:e.target.value}:t));}}/></label><button type="button" onClick={()=>{setTasks(items=>items.filter((_,j)=>j!==i));}}>Bu görevi çıkar</button></div>)}<label>Ortak takip tarihi<KeyboardInput type="date" aria-label="Ortak takip tarihi" value={followup} min={today} onChange={e=>setFollowup(e.target.value)}/></label><button type="button" className="family-meeting-primary" disabled={!participants.trim() || !discussion.trim() || !decision.trim() || !time || tasks.some(t=>!t.text.trim() || !t.dueOn)} onClick={save}>Görüşmeyi görevleri ve takibi birlikte kaydet</button></fieldset>}</section>
      {!model.meeting && !model.canRecord && <p>{model.status === "cancelled" ? "Bu yerel görüşme iptal edilmiş." : "Gerçek sonuç kaydı randevu saati geldiğinde açılır. Görüşme öncesi formu şimdi hazırlayabilirsiniz."}</p>}
      <button type="button" disabled={disabled || busy || loading || model.status === "cancelled"} onClick={()=>void output()}>{model.meeting ? "Kaydedilen formu PDF veya Word hazırla" : "Görüşme öncesi formu PDF veya Word hazırla"}</button>
    </>}
  </section>;
}

