export const WORK_PACKAGE_COPY = {
  title: "Hazır iş paketleri",
  intro: "MaarifOS yapılacak adımları hazırladı. İçeriği inceleyip seçtiğiniz paketi tek dokunuşla kaydedin.",
  details: "Paketin içeriğini düzenle",
  individual: "Adımları ayrı ayrı düzenle",
  applyOne: "Seçili paketi uygula",
  applyMany: "Seçili paketleri uygula",
  applying: "Paket kaydediliyor…",
  undo: "Bu işlemi geri al",
  undoing: "İşlem geri alınıyor…",
  undone: "Paketin yaptığı değişiklikler geri alındı.",
  select: "paketini seç",
  empty: "Bu kapsamda hazırlanacak yeni iş paketi yok.",
  loading: "Hazır seçenekler yükleniyor…",
  failedRead: "Hazır seçenekler yüklenemedi. Yenileyerek tekrar deneyebilirsiniz.",
  failedWrite: "Paket kaydedilemedi. Güncel seçenekleri inceleyerek tekrar deneyebilirsiniz.",
  refreshPending: "Paket kaydedildi. Güncel seçenekler henüz yüklenemedi.",
  refresh: "Seçenekleri yenile",
  result: "Bu seçimle yapılacaklar",
  reused: "Mevcut kayıt kullanılacak",
  remembered: "Önceki açık seçiminizle hazırlandı",
  choose: "Uygulanacak seçenek",
} as const;
