import {expect,test} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
test.setTimeout(90000);
test('Görev Excel dönüşü gerçek seçili farkı yazar; yabancı/eski/eksik/formüllü satır reddedilir, belge geçmişi guardı bozmaz',async({page})=>{
 await page.goto('/tests/runtime-fixture.html');const result=await page.evaluate(async()=>{
  const core=await import('/src/core/index.ts'),fx=await import('/tests/fixtures/class-duty-fixture.mjs'),doc=await import('/src/features/class-duty-schedule/class-duty-documents.ts'),mod=await import('/src/features/class-duty-schedule/class-duty-document-model.ts'),sheet=await import('/src/features/class-duty-schedule/class-duty-spreadsheet.ts'),svc=await import('/src/features/class-duty-schedule/class-duty-service.ts'),history=await import('/src/features/documents/document-history-service.ts'),x=fx;
  const store=new core.IndexedDbDataStore({databaseName:`duty-doc-${crypto.randomUUID()}`}),f=await fx.makeClassDutyFixture(store);await f.save();const model=mod.dutyDocumentModel(await store.readSnapshot(),f.request.scheduleId),xlsx=await sheet.createClassDutySpreadsheet(model),recipe=await doc.createClassDutyRecipe(store,f.request.scheduleId),pdf=await recipe.build(recipe.initial);await history.saveDocumentVersion({store,scope:model.scope},{title:recipe.title,file:pdf,selection:recipe.initial,now:f.now});await recipe.assertExportAllowed(recipe.initial);
  const book=x.read(xlsx.bytes,{type:'array'}),write=()=>new Uint8Array(x.write(book,{type:'array',bookType:'xlsx'}));const untouched=await sheet.readClassDutySpreadsheet(write(),model);book.Sheets.Veri.A2={t:'s',v:'2026-10-08'};const imported=await sheet.readClassDutySpreadsheet(write(),model);const request={kind:'changes' as const,scheduleId:f.request.scheduleId,operationId:crypto.randomUUID(),changes:imported.changes},p=await svc.previewClassDutySchedule(store,request,{now:f.now});await svc.applyClassDutySchedule(store,{request,expectedFingerprint:p.expectedFingerprint,now:f.now});let stale=false;try{await recipe.assertExportAllowed(recipe.initial);}catch{stale=true;}const next=mod.dutyDocumentModel(await store.readSnapshot(),f.request.scheduleId);let oldExcel=false;try{await sheet.readClassDutySpreadsheet(xlsx.bytes,next);}catch{oldExcel=true;}
  const bads=[];for(const mutate of [(b)=>b.Sheets.Veri.F2={t:'s',v:crypto.randomUUID()},(b)=>b.Sheets.Veri.A2={t:'s',v:''},(b)=>b.Sheets.Veri.A2={t:'n',v:1,f:'1+1'},(b)=>b.Sheets.Veri.F3=b.Sheets.Veri.F2]){const bad=x.read(xlsx.bytes,{type:'array'});mutate(bad);try{await sheet.readClassDutySpreadsheet(new Uint8Array(x.write(bad,{type:'array',bookType:'xlsx'})),model);bads.push(false);}catch{bads.push(true);}}
  const calendar=await doc.createClassDutyPdf(next,{template:'calendar'}),word=doc.createClassDutyWord(next),updated=await sheet.createClassDutySpreadsheet(next),board=await doc.createClassDutyBoardRecipe(store,'2026-10');const boardPdf=await board.build(board.initial);const files={list:pdf.bytes,calendar,word:word.bytes,excel:updated.bytes,board:boardPdf.bytes};store.close();return{untouched:untouched.changes.length,changes:imported.changes.length,date:next.rows[0].startOn,stale,oldExcel,bads,sheets:book.SheetNames,files:Object.fromEntries(Object.entries(files).map(([name,bytes])=>[name,Array.from(bytes)]))};
 });expect({...result,files:undefined}).toEqual({untouched:0,changes:1,date:'2026-10-08',stale:true,oldExcel:true,bads:[true,true,true,true],sheets:['Yazdırma','Veri','Kaynak','Çocuklar','Açıklamalar'],files:undefined});await mkdir('output/class-duty-qa',{recursive:true});for(const [name,bytes] of Object.entries(result.files))await writeFile(`output/class-duty-qa/${name}.${name==='word'?'docx':name==='excel'?'xlsx':'pdf'}`,Buffer.from(bytes));
});
test('20 çocuklu gerçek çizelge ve uzun adlar PDF, Word, Excel kaynaklarında eksiksiz kalır',async({page})=>{
 await page.goto('/tests/runtime-fixture.html');const files=await page.evaluate(async()=>{
  const core=await import('/src/core/index.ts'),fx=await import('/tests/fixtures/class-duty-fixture.mjs'),svc=await import('/src/features/class-duty-schedule/class-duty-service.ts'),mod=await import('/src/features/class-duty-schedule/class-duty-document-model.ts'),doc=await import('/src/features/class-duty-schedule/class-duty-documents.ts'),spread=await import('/src/features/class-duty-schedule/class-duty-spreadsheet.ts');
  const store=new core.IndexedDbDataStore({databaseName:`duty-long-${crypto.randomUUID()}`}),f=await fx.makeClassDutyFixture(store),snapshot=await store.readSnapshot(),base=snapshot.students[0],extra=Array.from({length:18},(_,i)=>({...base,id:crypto.randomUUID(),displayName:`Kurgu Öğrenci ${i+3} Uzun İsimli Kayıtlı Çocuk` }));await store.transaction('readwrite',['students'],tx=>tx.putMany('students',extra));const config={...f.request.config,studentIds:[...snapshot.students,...extra].map(s=>s.id),capacity:5},request={...f.request,config},p=await svc.previewClassDutySchedule(store,request,{now:f.now});await svc.applyClassDutySchedule(store,{request,expectedFingerprint:p.expectedFingerprint,now:f.now});const model=mod.dutyDocumentModel(await store.readSnapshot(),request.scheduleId);const word=doc.createClassDutyWord(model),excel=await spread.createClassDutySpreadsheet(model),pdf=await doc.createClassDutyPdf(model),calendar=await doc.createClassDutyPdf(model,{template:'calendar'});store.close();return{count:model.rows.length,children:new Set(model.rows.map(r=>r.studentId)).size,files:{'long-list.pdf':Array.from(pdf),'long-calendar.pdf':Array.from(calendar),'long-word.docx':Array.from(word.bytes),'long-excel.xlsx':Array.from(excel.bytes)}};
 });expect(files.count).toBe(20);expect(files.children).toBe(20);await mkdir('output/class-duty-qa',{recursive:true});for(const [name,bytes]of Object.entries(files.files))await writeFile(`output/class-duty-qa/${name}`,Buffer.from(bytes));
});

