import{expect,test}from"@playwright/test";
test("Var olan günlük plan ve etkinlikler atomik haftaya bağlanır; hata geri alınır, tekrar çoğaltmaz ve yedek doğrulanır",async({page})=>{
  await page.goto("/tests/runtime-fixture.html");const result=await page.evaluate(async()=>{
    const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/daily-plan-link-fixture.mjs"),steps=await import("/src/features/planning/plan-next-steps.ts");
    const store=new core.IndexedDbDataStore({databaseName:`daily-link-${crypto.randomUUID()}`}),f=await fx.makeDailyPlanLinkFixture(store),before=await store.readSnapshot();let stale=false;
    try{await steps.applyPlanNextStep(store,{...f.request,expectedFingerprint:"old"},{now:f.now});}catch{stale=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot());}
    let writes=0,rollback=false;const faulty={readSnapshot:()=>store.readSnapshot(),close(){},transaction:(mode:any,names:any,task:any)=>store.transaction(mode,names,(tx:any)=>task({...tx,getAll:(name:any)=>tx.getAll(name),putMany:async(name:any,rows:any)=>{await tx.putMany(name,rows);if(++writes===2)throw new Error("Kurgu ikinci yazım hatası");}}))};
    try{await steps.applyPlanNextStep(faulty,f.request,{now:f.now});}catch{rollback=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot());}
    const saved=await steps.applyPlanNextStep(store,f.request,{now:f.now}),after=await store.readSnapshot(),repeat=await steps.applyPlanNextStep(store,f.request,{now:f.now}),repeated=await store.readSnapshot();
    const backup=new core.BackupService(store,{appVersion:"0.41.0",clock:()=>new Date("2026-09-22T08:00:00.000Z")});const envelope=await backup.exportBackup();await backup.parseAndVerifyBackup(envelope);const target=new core.IndexedDbDataStore({databaseName:`daily-link-restore-${crypto.randomUUID()}`});await new core.BackupService(target,{appVersion:"0.41.0"}).restoreBackup(envelope,{mode:"replace",createRecoverySnapshot:false});
    const daily=after.plans.find(p=>p.id===f.request.dailyPlanId),activity=after.activities.find(a=>a.id===f.activity.activity.id);
    const result={kind:f.request.kind,status:f.model.status,stale,writes,rollback,planCount:before.plans.length===after.plans.length,activities:before.activities.length===after.activities.length,raw:core.canonicalJson(before.observations)===core.canonicalJson(after.observations),linked:daily.sourceWeeklyPlanId===f.request.weeklyPlanId&&activity.sourceWeeklyPlanId===f.request.weeklyPlanId,created:saved.createdPlanIds.length,repeat:saved.nextTarget.planId===repeat.nextTarget.planId&&core.canonicalJson(after)===core.canonicalJson(repeated),ready:(await steps.loadPlanNextSteps(store,{civilDate:f.day})).status,restore:core.canonicalJson(after)===core.canonicalJson(await target.readSnapshot())};store.close();target.close();return result;
  });expect(result).toEqual({kind:"link-existing-daily-plan",status:"action-required",stale:true,writes:2,rollback:true,planCount:true,activities:true,raw:true,linked:true,created:0,repeat:true,ready:"ready",restore:true});
});
