import {expect,test} from "@playwright/test";
import {mkdir,writeFile} from "node:fs/promises";
test.setTimeout(90000);
test("Bir günlük çıkış hazırlığı aynı hafta ve kaynakta yeniden kullanılır; ilgisiz aynı sözcük eşlenmez",async({page})=>{
  await page.goto("/tests/runtime-fixture.html");const result=await page.evaluate(async()=>{const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/material-box-fixture.mjs"),svc=await import("/src/features/material-box-labels/material-box-service.ts"),follow=await import("/src/features/teacher-followup/teacher-followup-service.ts");const store=new core.IndexedDbDataStore({databaseName:`box-day-reuse-${crypto.randomUUID()}`}),f=await fx.makeMaterialBoxFixture(store),now=new Date("2026-09-14T10:00:00.000Z"),need=f.model.needs[0];
    const unrelated=f.context.activity;await follow.appendTeacherFollowup(store,{studentId:null,now,workflow:{kind:"preparation-list",weekStart:f.day,weekEnd:f.day,sources:[{collection:"activities",id:unrelated.id,title:unrelated.title,updatedAt:unrelated.updatedAt}],items:[{id:crypto.randomUUID(),text:need.text,advance:false,dueOn:f.day,sourceIds:[unrelated.id]}]}});const afterUnrelated=await svc.loadMaterialBoxModel(store,f.day);
    await follow.appendTeacherFollowup(store,{studentId:null,now,workflow:{kind:"preparation-list",weekStart:f.day,weekEnd:f.day,sources:need.sources,items:[{id:crypto.randomUUID(),text:need.text,advance:false,dueOn:f.day,sourceIds:need.sources.map(s=>s.id)}]}});const afterDay=await svc.loadMaterialBoxModel(store,f.day),before=await store.readSnapshot(),reused=await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:afterDay.fingerprint,command:{kind:"add-materials",materialIds:[need.id]},now});const unchanged=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot());store.close();return{unrelatedListed:afterUnrelated.needs.find(n=>n.id===need.id).listed,dayListed:afterDay.needs.find(n=>n.id===need.id).listed,reused:reused.recordIds.length,unchanged};});expect(result).toEqual({unrelatedListed:false,dayListed:true,reused:0,unchanged:true});
});
test("Kaynak etkinliğin çocuk kapsamı PDF geçmişine geçer; ilgili silme belgeyi kaldırır, sınıf belgesi korunur",async({page})=>{
  await page.goto("/tests/runtime-fixture.html");const result=await page.evaluate(async()=>{const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/material-box-fixture.mjs"),docs=await import("/src/features/material-box-labels/material-box-document.ts"),history=await import("/src/features/documents/document-history-service.ts"),lifecycle=await import("/src/features/students/student-lifecycle.ts");const store=new core.IndexedDbDataStore({databaseName:`box-scope-${crypto.randomUUID()}`}),f=await fx.makeMaterialBoxFixture(store),recipe=await docs.createMaterialBoxRecipe(store,f.day,[f.model.boxes[0].id]),file=await recipe.build(recipe.initial),now=new Date("2026-09-14T10:00:00.000Z");let narrow=false;try{await recipe.assertExportAllowed({...recipe.initial,studentIds:[f.input.studentId]});}catch{narrow=true;}
    const saved=await history.saveDocumentVersion({store,scope:f.scope},{file,title:recipe.title,selection:recipe.initial,now});await recipe.assertExportAllowed(recipe.initial);const classOnly=structuredClone(f.model);classOnly.boxes[0].activities=[];classOnly.boxes[0].studentIds=[];classOnly.students=[];const generic=await history.saveDocumentVersion({store,scope:f.scope},{file:{bytes:await docs.createMaterialBoxPdf(classOnly,[classOnly.boxes[0].id]),mimeType:"application/pdf",fileName:"Kurgu_sinif_kutusu.pdf"},title:"Kurgu sınıf kutusu",selection:{fields:["labels"]},now});
    const data=await store.readSnapshot(),preview=lifecycle.previewPermanentStudentDeletion(data,f.input.studentId);await lifecycle.permanentlyDeleteStudent(store,{studentId:f.input.studentId,confirmationName:preview.displayName,expectedFingerprint:preview.fingerprint,now:new Date("2026-09-14T11:00:00.000Z")});const after=await store.readSnapshot();let stale=false;try{await recipe.assertExportAllowed(recipe.initial);}catch{stale=true;}const backup=new core.BackupService(store,{appVersion:"0.43.0",clock:()=>new Date("2026-09-14T12:00:00.000Z")});await backup.parseAndVerifyBackup(await backup.exportBackup());const answer={scope:recipe.initial.studentIds.length,narrow,removed:!after.settings.some(r=>r.id===saved.id),preserved:after.settings.some(r=>r.id===generic.id),stale};store.close();return answer;});expect(result).toEqual({scope:2,narrow:true,removed:true,preserved:true,stale:true});
});
test("Malzeme kutusu: gerçek IDB atomiklik, tekrar, eski kaynak, yetim merkez, yedek ve öğrenci silme",async({page})=>{
  await page.goto("/tests/runtime-fixture.html");const result=await page.evaluate(async()=>{
    const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/material-box-fixture.mjs"),svc=await import("/src/features/material-box-labels/material-box-service.ts"),domain=await import("/src/core/domain/learning-centers.ts"),enc=await import("/src/core/backup/encrypted-backup.ts"),lifecycle=await import("/src/features/students/student-lifecycle.ts");
    const store=new core.IndexedDbDataStore({databaseName:`box-core-${crypto.randomUUID()}`}),f=await fx.makeMaterialBoxFixture(store),now=new Date("2026-09-14T10:00:00.000Z"),before=await store.readSnapshot(),command={kind:"prepare-box" as const,boxId:f.model.boxes[0].id,prepared:true};
    const original=store.transaction.bind(store);store.transaction=async(mode,collections,task)=>original(mode,collections,async tx=>task({...tx,putMany:async(c,records)=>{await tx.putMany(c,records);throw Error("Kurgu diske yazım sonrası kesinti");}}));
    let failed=false;try{await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:f.model.fingerprint,command,now});}catch{failed=true;}store.transaction=original;const rollback=core.canonicalJson(before)===core.canonicalJson(await store.readSnapshot());
    const saved=await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:f.model.fingerprint,command,now});const repeat=await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:f.model.fingerprint,command,now});
    let stale=false;try{await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:f.model.fingerprint,command:{...command,boxId:f.model.boxes[1].id},now});}catch{stale=true;}
    const model=await svc.loadMaterialBoxModel(store,f.day),need=model.needs[0];if(!need)throw Error("Kurgu gerçek kaynak malzemesi yok");
    const prep=await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:model.fingerprint,command:{kind:"add-materials",materialIds:[need.id]},now});const prepRepeat=await svc.applyMaterialBoxAction(store,{day:f.day,expectedFingerprint:model.fingerprint,command:{kind:"add-materials",materialIds:[need.id]},now});
    const snapshot=await store.readSnapshot(),bad=structuredClone(snapshot),event=bad.settings.find(r=>r.id===saved.recordIds[0])!;event.workflow={...event.workflow,centerId:crypto.randomUUID()};let orphan=false;try{domain.assertLearningCenterRelationships(bad);}catch{orphan=true;}
    const backupOptions={appVersion:"0.43.0",clock:()=>new Date("2026-09-14T12:00:00.000Z")},backup=new core.BackupService(store,backupOptions),verified=await backup.parseAndVerifyBackup(await backup.exportBackup()),password="Kurgu-malzeme-yedegi!",encrypted=backup.serializeEncryptedBackup(await enc.encryptBackupText(core.canonicalJson(verified),{appVersion:"0.43.0",createdAt:verified.manifest.createdAt},password));
    const target=new core.IndexedDbDataStore({databaseName:`box-restored-${crypto.randomUUID()}`}),restorer=new core.BackupService(target,backupOptions);await restorer.restoreEncryptedBackup(encrypted,password,{mode:"replace",createRecoverySnapshot:false});const exact=core.canonicalJson(await target.readSnapshot())===core.canonicalJson(snapshot);
    const preview=lifecycle.previewPermanentStudentDeletion(snapshot,f.input.studentId);await lifecycle.permanentlyDeleteStudent(store,{studentId:f.input.studentId,confirmationName:preview.displayName,expectedFingerprint:preview.fingerprint,now:new Date("2026-09-14T11:00:00.000Z")});const after=await store.readSnapshot();domain.assertLearningCenterRelationships(after);await backup.parseAndVerifyBackup(await backup.exportBackup());
    const answer={failed,rollback,saved:saved.recordIds.length,repeat:repeat.recordIds.length,stale,prep:prep.recordIds.length,prepRepeat:prepRepeat.recordIds.length,orphan,exact,prepared:(await svc.loadMaterialBoxModel(store,f.day)).boxes[0].prepared,children:after.students.length,retained:after.settings.some(r=>r.id===saved.recordIds[0]),activityMatch:f.model.boxes.every(b=>b.activities.length===1)};store.close();target.close();return answer;
  });expect(result).toEqual({failed:true,rollback:true,saved:1,repeat:0,stale:true,prep:1,prepRepeat:0,orphan:true,exact:true,prepared:true,children:1,retained:true,activityMatch:true});
});
test("12 gerçek merkez etiketi A4 kesim düzeninde; uzun içerik devam etiketinde eksiksiz",async({page})=>{
  await page.goto("/tests/runtime-fixture.html");const files=await page.evaluate(async()=>{const core=await import("/src/core/index.ts"),fx=await import("/tests/fixtures/material-box-fixture.mjs"),doc=await import("/src/features/material-box-labels/material-box-document.ts");const store=new core.IndexedDbDataStore({databaseName:`box-pdf-${crypto.randomUUID()}`}),f=await fx.makeMaterialBoxFixture(store);const normal=await doc.createMaterialBoxPdf(f.model,f.model.boxes.map(b=>b.id));const long=structuredClone(f.model);long.boxes[0].contents=Array.from({length:25},(_,i)=>`Kurgu uzun içerik ${i+1}: Renkli ahşap parçalar ve kayıtlı düzenleme malzemeleri`);const extra=await doc.createMaterialBoxPdf(long,[long.boxes[0].id]);store.close();return{normal:Array.from(normal),long:Array.from(extra)};});await mkdir("output/material-box-labels-qa",{recursive:true});for(const [name,bytes] of Object.entries(files))await writeFile(`output/material-box-labels-qa/${name}.pdf`,Buffer.from(bytes));expect(new TextDecoder().decode(Uint8Array.from(files.normal)).match(/\/Type \/Page\b/gu)).toHaveLength(1);
});
