import {expect,test} from '@playwright/test';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-09-12T09:00:00Z'));await page.goto('/tests/runtime-fixture.html');});

test('independent three-way records merge; conflicting source requires actual choice; encrypted state rejects wrong key and tampering',async({page})=>{
 const result=await page.evaluate(async()=>{const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,cloudBaseline,previewCloudMerge,resolveCloudMerge,encryptCloudState,decryptCloudState}=await import('/src/features/cloud-account/cloud-sync.ts');const f=await makeDevelopmentReportFixture(),snapshot=await f.store.readSnapshot(),base=await cloudStateFromSnapshot(snapshot,'0.44.0');const local=structuredClone(snapshot),remote=structuredClone(snapshot);local.students[0].displayName='Kurgu yerel ad';remote.students[1].displayName='Kurgu uzak ad';const l=await cloudStateFromSnapshot(local,'0.44.0'),r=await cloudStateFromSnapshot(remote,'0.44.0'),preview=await previewCloudMerge(await cloudBaseline(base),l,r),merged=await resolveCloudMerge(preview,{},'0.44.0');remote.students[0].displayName='Kurgu çakışan ad';const conflicted=await previewCloudMerge(await cloudBaseline(base),l,await cloudStateFromSnapshot(remote,'0.44.0'));let needsChoice=false;try{await resolveCloudMerge(conflicted,{},'0.44.0');}catch{needsChoice=true;}const choices=Object.fromEntries(conflicted.conflicts.map(c=>[c.key,'remote'])),chosen=await resolveCloudMerge(conflicted,choices,'0.44.0');const key='Kurgu-yalniz-test-anahtari-123456789';const encrypted=await encryptCloudState(chosen,key);let wrong=false,tampered=false;try{await decryptCloudState(encrypted,key+'x','0.44.0');}catch{wrong=true;}const bad=structuredClone(encrypted);bad.ciphertext=(bad.ciphertext[0]==='A'?'B':'A')+bad.ciphertext.slice(1);try{await decryptCloudState(bad,key,'0.44.0');}catch{tampered=true;}const roundtrip=await decryptCloudState(encrypted,key,'0.44.0');return{conflicts:preview.conflicts.length,merged:merged.backup.payload.students.map(s=>s.displayName),needsChoice,chosen:chosen.backup.payload.students.find(s=>s.id===snapshot.students[0].id).displayName,wrong,tampered,equal:JSON.stringify(roundtrip.backup.payload)===JSON.stringify(chosen.backup.payload)};});
 expect(result).toEqual({conflicts:0,merged:['Kurgu yerel ad','Kurgu uzak ad'],needsChoice:true,chosen:'Kurgu çakışan ad',wrong:true,tampered:true,equal:true});
});

test('permanent deletion wins over an offline edit, preserves another child and stores hash-only tombstones',async({page})=>{
 const result=await page.evaluate(async()=>{const {IndexedDbDataStore}=await import('/src/core/repository/indexed-db.ts');const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,cloudBaseline,previewCloudMerge,resolveCloudMerge,applyCloudErasures}=await import('/src/features/cloud-account/cloud-sync.ts');const {previewPermanentStudentDeletion,permanentlyDeleteStudent}=await import('/src/features/students/student-lifecycle.ts');const {isStudentErasure}=await import('/src/core/domain/student-erasure.ts');const store=new IndexedDbDataStore({databaseName:crypto.randomUUID()});try{const f=await makeDevelopmentReportFixture(store),initial=await store.readSnapshot(),base=await cloudStateFromSnapshot(initial,'0.44.0'),remote=structuredClone(initial);remote.students[0].displayName='Eski cihazdaki kurgu değişiklik';const impact=previewPermanentStudentDeletion(initial,f.input.studentId);await permanentlyDeleteStudent(store,{studentId:f.input.studentId,confirmationName:impact.displayName,expectedFingerprint:impact.fingerprint});const local=await cloudStateFromSnapshot(await store.readSnapshot(),'0.44.0'),preview=await previewCloudMerge(await cloudBaseline(base),local,await cloudStateFromSnapshot(remote,'0.44.0'));const merged=await resolveCloudMerge(preview,Object.fromEntries(preview.conflicts.map(c=>[c.key,'remote'])),'0.44.0');const oldRestore=await applyCloudErasures(base.backup.payload,merged.erasedStudentHashes,'0.44.0');const markers=merged.backup.payload.settings.filter(isStudentErasure);return{deleted:!merged.backup.payload.students.some(s=>s.id===f.input.studentId),other:merged.backup.payload.students.some(s=>s.id===f.otherStudentId),noObservation:!merged.backup.payload.observations.some(o=>o.id===f.observationId),hashOnly:markers.length===1&&!JSON.stringify(markers).includes(f.input.studentId)&&merged.erasedStudentHashes.every(h=>/^[a-f0-9]{64}$/.test(h)),oldHeadProtected:!oldRestore.backup.payload.students.some(s=>s.id===f.input.studentId)};}finally{store.close();}});expect(result).toEqual({deleted:true,other:true,noObservation:true,hashOnly:true,oldHeadProtected:true});
});

test('restore service itself preserves a local permanent deletion when passed an old head',async({page})=>{
 const result=await page.evaluate(async()=>{const {IndexedDbDataStore}=await import('/src/core/repository/indexed-db.ts');const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,restoreCloudState}=await import('/src/features/cloud-account/cloud-sync.ts');const {canonicalJson}=await import('/src/core/backup/canonical-json.ts');const {previewPermanentStudentDeletion,permanentlyDeleteStudent}=await import('/src/features/students/student-lifecycle.ts');const store=new IndexedDbDataStore({databaseName:crypto.randomUUID()});try{const f=await makeDevelopmentReportFixture(store),before=await store.readSnapshot(),old=await cloudStateFromSnapshot(before,'0.44.0'),impact=previewPermanentStudentDeletion(before,f.input.studentId);await permanentlyDeleteStudent(store,{studentId:f.input.studentId,confirmationName:impact.displayName,expectedFingerprint:impact.fingerprint});const fingerprint=canonicalJson(await store.readSnapshot());let refused=false;try{await restoreCloudState(store,old,fingerprint,'0.44.0');}catch{refused=true;}const after=await store.readSnapshot();return{deleted:!after.students.some(s=>s.id===f.input.studentId),other:after.students.some(s=>s.id===f.otherStudentId),refused};}finally{store.close();}});expect(result.deleted).toBe(true);expect(result.other).toBe(true);
});

test('stale selection and a write-boundary edit both block restore without overwriting newer local data',async({page})=>{
 const result=await page.evaluate(async()=>{const {IndexedDbDataStore}=await import('/src/core/repository/indexed-db.ts');const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,restoreCloudState}=await import('/src/features/cloud-account/cloud-sync.ts');const {canonicalJson}=await import('/src/core/backup/canonical-json.ts');const store=new IndexedDbDataStore({databaseName:crypto.randomUUID()});try{await makeDevelopmentReportFixture(store);const before=await store.readSnapshot(),remote=await cloudStateFromSnapshot(before,'0.44.0'),changed={...before.students[1],displayName:'Yeni yerel kayıt'};await store.transaction('readwrite',['students'],t=>t.putMany('students',[changed]));let stale=false;try{await restoreCloudState(store,remote,canonicalJson(before),'0.44.0');}catch{stale=true;}const expected=canonicalJson(await store.readSnapshot());let injected=false;const racing=new Proxy(store,{get(target,property){if(property==='transaction')return async(mode,names,task)=>{if(mode==='readwrite'&&!injected){injected=true;await target.transaction('readwrite',['students'],t=>t.putMany('students',[{...changed,displayName:'Son anda kaydedilen yerel kayıt'}]));}return target.transaction(mode,names,task);};const value=Reflect.get(target,property,target);return typeof value==='function'?value.bind(target):value;}});let race=false;try{await restoreCloudState(racing,remote,expected,'0.44.0');}catch{race=true;}return{stale,race,injected,value:(await store.readSnapshot()).students.find(s=>s.id===changed.id).displayName};}finally{store.close();}});expect(result).toEqual({stale:true,race:true,injected:true,value:'Son anda kaydedilen yerel kayıt'});
});

test('local baseline stores only hashes and upgrading the old database physically removes encrypted child copies',async({page})=>{
 const result=await page.evaluate(async()=>{const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,cloudBaseline,encryptCloudState}=await import('/src/features/cloud-account/cloud-sync.ts');const {saveCloudAnchor,readCloudAnchor}=await import('/src/features/cloud-account/cloud-gateway.ts');const f=await makeDevelopmentReportFixture(),snapshot=await f.store.readSnapshot(),state=await cloudStateFromSnapshot(snapshot,'0.44.0'),envelope=await encryptCloudState(state,'Kurgu-anahtar-yirmiden-uzun-123456');await new Promise<void>((resolve,reject)=>{const open=indexedDB.open('maarifos-cloud-baselines',1);open.onupgradeneeded=()=>open.result.createObjectStore('encrypted');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('encrypted','readwrite');tx.objectStore('encrypted').put({subject:'fixture-account',headId:'old-head',envelope},'fixture-account');tx.oncomplete=()=>{db.close();resolve();};};});const previous=await readCloudAnchor('fixture-account');const baseline=await cloudBaseline(state);await saveCloudAnchor({subject:'fixture-account',headId:'new-head',baseline});const saved=await readCloudAnchor('fixture-account'),json=JSON.stringify(saved),stores=await new Promise<string[]>((resolve,reject)=>{const open=indexedDB.open('maarifos-cloud-baselines');open.onerror=()=>reject(open.error);open.onsuccess=()=>{resolve([...open.result.objectStoreNames]);open.result.close();};});return{removed:previous===null&&!stores.includes('encrypted'),noRawIds:snapshot.students.every(s=>!json.includes(s.id)),noText:snapshot.students.every(s=>!json.includes(String(s.displayName)))&&!json.includes(String(snapshot.observations[0].rawText)),noEnvelope:!json.includes('ciphertext')&&!json.includes('envelope'),hashes:Object.values(baseline.records).every(records=>Object.entries(records).every(([id,value])=>/^[a-f0-9]{64}$/.test(id)&&/^[a-f0-9]{64}$/.test(value))),saved:saved?.headId==='new-head'};});expect(result).toEqual({removed:true,noRawIds:true,noText:true,noEnvelope:true,hashes:true,saved:true});
});

test('missing student without an erasure marker preserves the existing record instead of inferring permanent deletion',async({page})=>{
 const result=await page.evaluate(async()=>{const {makeDevelopmentReportFixture}=await import('/tests/fixtures/development-report-fixture.mjs');const {cloudStateFromSnapshot,cloudBaseline,previewCloudMerge,resolveCloudMerge}=await import('/src/features/cloud-account/cloud-sync.ts');const f=await makeDevelopmentReportFixture(),snapshot=await f.store.readSnapshot(),base=await cloudBaseline(await cloudStateFromSnapshot(snapshot,'0.44.0')),local=structuredClone(snapshot),remote=structuredClone(snapshot);local.students=local.students.filter(s=>s.id!==f.otherStudentId);remote.students.find(s=>s.id===f.otherStudentId).displayName='Diğer cihazda yeni çocuk bilgisi';const preview=await previewCloudMerge(base,await cloudStateFromSnapshot(local,'0.44.0'),await cloudStateFromSnapshot(remote,'0.44.0')),resolved=await resolveCloudMerge(preview,Object.fromEntries(preview.conflicts.map(c=>[c.key,'remote'])),'0.44.0');return{erased:preview.erasedStudentIds.length,conflict:preview.conflicts.some(c=>c.id===f.otherStudentId),kept:resolved.backup.payload.students.find(s=>s.id===f.otherStudentId)?.displayName};});expect(result).toEqual({erased:0,conflict:false,kept:'Diğer cihazda yeni çocuk bilgisi'});
});
