import type { ObservationCategoryV2 } from "../../core/domain/observation-taxonomy.ts";

export const ACTION_CENTER_COPY = {
  title: "Birlikte tamamlayalım",
  metadata: "Tarihi ve gerçek kaynak bağlantılarını tamamla",
  intro: "MaarifOS seçenekleri hazırladı. Seçtiğiniz adım doğrudan kaydedilir.",
  categories: "1. Gözlemi yerleştir",
  categoryHelp: "Gözleme uygun başlığı seçin. Bu başlık kayıtları düzenler; gelişim değerlendirmesi yapmaz.",
  moreCategories: "Bütün başlıkları göster",
  support: "2. Sonraki adımı planla",
  supportHelp: "Uygulamak istediğiniz seçeneğin metnini inceleyip haftaya ekleyin.",
  addToPlan: "Seç ve haftalık plana ekle",
  planCreated: "Destek adımı haftalık plana eklendi. Kaynak gözlem ve değerlendirme tarihi bağlandı.",
  categorySaved: "Başlık kaydedildi. Şimdi sonraki adımı seçebilirsiniz.",
  assigned: "Yerleştirildiği başlık",
  alreadyDone: "Bu adım daha önce tamamlandı; aynı kayıt yeniden oluşturulmadı.",
  completed: "Sonraki destek adımı haftalık plana kaydedildi.",
  planOpen: "Kaydedilen planı aç",
  preparation: "Hazırlığını tamamla",
  preparationCreate: "Seçili kaynaklardan hazırlık listesi oluştur",
  preparationComplete: "Hazırladım, tamamla",
  preparationSaved: "Hazırlık listesi kaydedildi. Maddeleri hazırladıkça tamamlayabilirsiniz.",
  checked: "Hazırlık maddesi tamamlandı.",
  empty: "Şu anda bu kapsamda tamamlanacak bir yerleştirme yok.",
  busy: "Kaydediliyor…",
  error: "Adım kaydedilemedi. Yeniden deneyin.",
  refreshPending: "Adım kaydedildi. Görünüm henüz yenilenemedi; sayfayı yeniden açtığınızda kayıt görünecek.",
  stale: "Kaynak veya sınıf değişti. Güncel seçenekler yenilendi; yeniden seçin.",
  showMore: "Diğer işleri göster",
  noFuture: "Bu eğitim yılında ileri tarihli bir destek haftası kalmadı.",
  categoryLabels: {
    "language-communication": "Dil ve iletişim", "cognitive-learning": "Bilişsel öğrenme",
    "social-emotional": "Sosyal ve duygusal", "values-dispositions-participation": "Değerler ve katılım",
    "physical-motor-health": "Hareket ve sağlık", "self-care-daily-life": "Öz bakım ve günlük yaşam",
    "art-creativity": "Sanat ve yaratıcılık", "play-participation": "Oyun ve katılım",
    "interest-attention-curiosity": "İlgi, dikkat ve merak", other: "Diğer gözlemler",
  } satisfies Record<ObservationCategoryV2, string>,
  legacyCategoryLabels: { cognitive: "Bilişsel gelişim", "social-emotional-values": "Sosyal, duygusal gelişim ve değerler", "physical-health": "Hareket ve sağlık", "self-care": "Öz bakım" } as Record<string, string>,
  supportOptions: [
    { id: "observe-again" as const, title: "Aynı bağlamda yeniden gözle", text: "Benzer bir oyun fırsatı sunacağım. Çocuğun seçimini, yaptığı eylemi ve varsa kendi sözünü ayrı bir gözlem olarak kaydedeceğim." },
    { id: "small-group" as const, title: "Küçük grupta fırsat sun", text: "Gözlemdeki etkinliği küçük bir grupla yeniden sunacağım. Çocuğun katılımını ve akranlarıyla etkileşimini somut örneklerle kaydedeceğim." },
    { id: "adapt-environment" as const, title: "Ortamı düzenleyerek dene", text: "Gözlemdeki etkinlik için materyalleri erişilebilir hâle getirip sakin bir çalışma alanı sunacağım. Çocuğun seçtiği desteği ve yaptığı eylemi kaydedeceğim." },
  ],
  valueTrace: "Değer: saygı ve özen. Eylem: çocuğun seçimine alan açmak ve sözünü kesmeden dinlemek. Kanıt: çocuğun somut eylemi ve varsa kendi sözü. Yansıtma: hafta sonunda hangi koşulların katılımı desteklediğini incelemek. Sonraki plan: yeni gözleme göre devam etmek veya düzenlemek.",
  annualTitle: "Gözlemlerden sonraki adımlar",
  annualText: "Öğretmenin seçtiği gözlemlerden hareketle planladığı sonraki eğitim adımları bu plan zincirinde toplanır.",
  monthlyTitle: "Gözlemden planlama",
  weeklyTitle: "Gözlemden sonraki adımlar",
  sourceDate: "Kaynak gözlem tarihi",
  reviewDate: "Yeniden değerlendirme",
} as const;
