export const OBSERVATION_MANAGEMENT_COPY = {
  title: "Gözlemin tarihi ve bağlantıları", date: "Olayın gerçekleştiği tarih", today: "Bugün", yesterday: "Dün", pickDate: "Tarih seç",
  recorded: "Kayda giriş tarihi", current: "Kayıtlı etkinlik", noActivity: "Henüz planlı bir etkinliğe yerleştirilmedi.",
  explanation: "Gözlemin ne zaman gerçekleştiğini ve hangi etkinliğe ait olduğunu seçin. Yazdığınız metin ve ilk kayıt zamanı korunur.",
  choices: "Bu tarihe uygun kayıtlı etkinlikler", attach: "Bu etkinliğe yerleştir", attachTarget: "Etkinliğe ve bu hedefe bağla",
  keep: "Tarihi kaydet, bağlantıyı koru", spontaneous: "Bu tarihe al, planlı etkinlikten ayır", source: "Kayıtlı program hedefi",
  fallback: "Planlı etkinlik seçmeden bu tarihe kaydet", fallbackHelp: "Gözlem seçilen günün anlık gözlemlerine taşınır. Daha sonra uygun etkinliğe yerleştirebilirsiniz.",
  empty: "Bu gün için kayıtlı uygun etkinlik yok. Gözlemi günün anlık gözlemlerine kaydedebilirsiniz.",
  removeLinks: "Bu seçim eski etkinliğe ait program/değer bağlarını kaldırıp seçtiğiniz yeni bağı kurar.",
  saved: "Gözlemin tarihi ve bağlantıları kaydedildi.", duplicate: "Bu seçim zaten kaydedilmiş; yeniden kayıt oluşturulmadı.",
  stale: "Gözlem, seçilen etkinlik veya sınıf değişti. Güncel seçeneklerden yeniden seçin.",
  invalidDate: "Olay tarihi bugün veya geçmişte, çocuğun bu sınıfa kayıtlı olduğu bir gün olmalıdır.",
  missing: "Bu gözlem etkin sınıfta bulunamadı.", failed: "Değişiklik kaydedilemedi; gözlem korunuyor.", busy: "Kaydediliyor…",
  refresh: "Değişiklik kaydedildi. Görünüm yeniden açıldığında güncel kayıt gösterilecek.",
  readFailed: "Güncel gözlem seçenekleri yüklenemedi. Görünümü yeniden açarak kayıtları görebilirsiniz.",
  dependent: "Bu gözlem kayıtlı bir rapor, değerlendirme veya takipte kaynak olarak kullanılıyor. Seçilen değişiklik bu kaynağı geçersiz kıldığı için kaydedilmedi; mevcut kayıtlar korunuyor.",
  all: "Diğer uygun etkinlikleri göster", history: "Tarih ve etkinlik bağı öğretmenin seçimiyle düzeltildi",
  developmentTitle: "Gözleme uygun Maarif başlığını seç", developmentHelp: "Kaydettiğiniz davranışa uyan seçeneği seçin. Seçim, gözleme kaynaklı program bağı ekler; başarı veya gelişim düzeyi atamaz.",
  developmentAction: "Bu Maarif başlığına bağla", moreDevelopment: "Yaş bandındaki bütün Maarif başlıklarını göster", otherLinks: "Diğer program bağlantıları",
  noDevelopmentMatch: "Metinle doğrudan eşleşen hazır başlık bulunamadı. Aşağıdaki yaş bandı kataloğundan yalnız gözlediğiniz davranışa uyan başlığı seçebilirsiniz.",
  developmentMatch: "Metindeki sözcük ipuçlarıyla öne çıkan başlıklar önce gösteriliyor. Bağlamın ve kaynak hedefinin gözleminize uyduğunu kontrol ederek seçin.",
  shared: "Bu ortak gözlemin tarihi ve etkinliği bütün katılımcılar için değişir.", participants: "Katılımcılar",
  integrity: "Gözlemin kaynak ilişkileri doğrulanamadı. Hiçbir değişiklik kaydedilmedi; mevcut gözlem korunuyor.",
} as const;
