import { useEffect,useRef,useState } from "react";
import { flushSync } from "react-dom";
import { KeyboardInput } from "../../mobile";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { civilDateInIstanbul } from "../../core/domain/attendance.ts";
import { requestPdfDocument } from "../documents/pdf-preview-model.ts";
import { applyMaterialBoxAction,loadMaterialBoxModel,type MaterialBoxCommand,type MaterialBoxModel } from "./material-box-service.ts";
import { createMaterialBoxRecipe } from "./material-box-document.ts";
import "./material-box-labels.css";

export interface MaterialBoxLabelsPanelProps{store:LocalDataStore;refreshKey?:unknown;disabled?:boolean;onChanged?:()=>void;onOpenPlan?:(planId:string)=>void;onOpenCenters?:()=>void;onOpenPlanning?:(civilDate:string)=>void}
export function MaterialBoxLabelsPanel({store,refreshKey,disabled=false,onChanged,onOpenPlan,onOpenCenters,onOpenPlanning}:MaterialBoxLabelsPanelProps){
  const [day,setDay]=useState(civilDateInIstanbul(new Date())),[model,setModel]=useState<MaterialBoxModel|null>(null),[boxes,setBoxes]=useState<string[]>([]),[needs,setNeeds]=useState<string[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[revision,setRevision]=useState(0);
  const generation=useRef(0),locked=useRef(false),initialized=useRef(""),current=useRef({store,day,disabled});current.current={store,day,disabled};
  useEffect(()=>{const version=++generation.current;setLoading(true);setModel(null);setError("");void loadMaterialBoxModel(store,day).then(next=>{if(version!==generation.current)return;const key=`${next.scope?.classroomId}:${next.weekStart}`;setBoxes(old=>initialized.current===key?old.filter(id=>next.boxes.some(b=>b.id===id)):next.boxes.slice(0,12).map(b=>b.id));setNeeds(old=>old.filter(id=>next.needs.some(n=>n.id===id&&!n.listed)));initialized.current=key;setModel(next);setLoading(false);}).catch(reason=>{if(version===generation.current){setLoading(false);setError(reason instanceof Error?reason.message:"Malzeme kaynakları yüklenemedi.");}});return()=>{++generation.current;};},[store,day,refreshKey,revision]);
  async function act(command:MaterialBoxCommand){if(locked.current||current.current.disabled||loading||!model)return;locked.current=true;setBusy(true);setError("");setSuccess("");const scope=current.current;let committed=false;
    try{const result=await applyMaterialBoxAction(store,{day,expectedFingerprint:model.fingerprint,command});committed=true;if(current.current.store===scope.store&&current.current.day===scope.day){setSuccess(result.summary);flushSync(()=>{setRevision(v=>v+1);onChanged?.();});}}
    catch(reason){if(current.current.store===scope.store&&current.current.day===scope.day)setError(committed?"İşlem kaydedildi; görünüm henüz yenilenemedi.":reason instanceof Error?reason.message:"İşlem kaydedilemedi.");}
    finally{locked.current=false;setBusy(false);}
  }
  async function pdf(){if(locked.current||current.current.disabled||loading||!model)return;locked.current=true;setBusy(true);setError("");const version=generation.current;try{const recipe=await createMaterialBoxRecipe(store,day,boxes);if(version!==generation.current||current.current.disabled)return;await requestPdfDocument(recipe);}catch(reason){if(version===generation.current)setError(reason instanceof Error?reason.message:"Etiket hazırlanamadı.");}finally{locked.current=false;setBusy(false);}}
  const blocked=disabled||busy||loading;
  return <section className="material-box-labels" aria-label="Malzeme kutusu etiketleri"><h2>Malzeme kutusu etiketleri</h2><p>Kayıtlı merkezlerin malzemelerini etiketleyin; eksikleri haftanın hazırlığına ekleyip kutuları hazır olarak işaretleyin.</p>
    <label>Etiket haftası<KeyboardInput type="date" value={day} disabled={disabled||busy} onChange={e=>{if(e.target.value){setSuccess("");setDay(e.target.value);}}}/></label>
    {model&&<><fieldset disabled={blocked}><legend>Etikete alınacak merkez kutuları</legend>{model.boxes.length?model.boxes.map(box=><article key={box.id}><label className="material-box-choice"><input type="checkbox" checked={boxes.includes(box.id)} onChange={e=>setBoxes(old=>e.target.checked?[...old,box.id]:old.filter(id=>id!==box.id))}/><strong>{box.title}</strong></label><p>{box.contents.join(" · ")||"Bu merkeze henüz malzeme tahsis edilmedi."}</p><p>{box.activities.length?`Aynı malzemeyi kullanan etkinlikler: ${box.activities.map(a=>a.title).join(" · ")}`:"Bu hafta aynı malzemeyi kullanan kayıtlı etkinlik yok."}</p>{box.prepared?<p>Kutu hazır olarak kayıtlı.</p>:null}<button type="button" onClick={()=>void act({kind:"prepare-box",boxId:box.id,prepared:!box.prepared})}>{box.prepared?"Kutuyu yeniden hazırlığa aç":"Kutuyu hazır olarak kaydet"}</button>{onOpenPlan&&box.activities.map(a=><button type="button" key={a.id} onClick={()=>onOpenPlan(a.planId)}>{a.title} planını aç</button>)}</article>):<div><p>Bu hafta açık bir öğrenme merkezi düzeni bulunmuyor.</p>{onOpenCenters&&<button type="button" onClick={onOpenCenters}>Öğrenme merkezlerine malzeme ayır</button>}</div>}</fieldset>
    <button type="button" className="material-box-primary" disabled={blocked||!boxes.length} onClick={()=>void pdf()}>{boxes.length} kutunun A4 etiketlerini hazırla</button>
    <fieldset disabled={blocked}><legend>Eksik malzemeyi haftanın hazırlığına ekle</legend><p>Bu hafta etkinliklerde kayıtlı malzemeler. Eksik olanları siz seçin.</p>{model.needs.length?model.needs.map(need=><label className="material-box-choice" key={need.id}><input type="checkbox" disabled={need.listed} checked={needs.includes(need.id)} onChange={e=>setNeeds(old=>e.target.checked?[...old,need.id]:old.filter(id=>id!==need.id))}/><span>{need.text}{need.listed?(need.completed?" · Hazır olarak kayıtlı":" · Hazırlık listesinde"):""}<small>{need.sources.map(s=>s.title).join(" · ")}</small></span></label>):<div><p>Bu haftanın kayıtlı etkinliklerinde malzeme bilgisi bulunmuyor.</p>{onOpenPlanning&&<button type="button" onClick={()=>onOpenPlanning(model.weekStart)}>Haftanın planını ve malzemelerini hazırla</button>}</div>}</fieldset><button type="button" disabled={blocked||!needs.length} onClick={()=>void act({kind:"add-materials",materialIds:needs})}>{needs.length} eksik malzemeyi haftanın hazırlığına ekle</button></>}
    {loading&&<p role="status">Kayıtlı merkez ve malzemeler hazırlanıyor…</p>}{success&&<p role="status" className="material-box-success">{success}</p>}{error&&<div role="alert"><p>{error}</p><button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Aynı seçimlerle yenile</button></div>}
  </section>;
}
