export const ACTIVITY_TEACHER_GUIDE_COPY = {
  back: "Etkinlikler",
  heading: "Uygulama rehberi",
  openGuide: "Rehberi aç",
  openGuideLabel: (title: string) => `${title} rehberini aç`,
  duration: (minutes: number, ageLabel: string) => `${minutes} dakika · ${ageLabel}`,
  materials: "Yanına al",
  scenarioLabel: "Seçilen sınıf koşulu",
  steps: "Birlikte uygulayın",
  support: "Katılımı kolaylaştır",
  observation: "Neye bakalım?",
  observationHint: "Yalnız gördüğün davranışı yaz. Etkinlik bilgisi kayda taşınır.",
  openingObservation: "Gözlem açılıyor",
  addObservation: "Çocuğa gözlem ekle",
  tools: "Program bağlantısı ve araçlar",
  domains: "TYMM alanları",
  preparation: "Ortam ve hazırlık",
  preparationDetail: (environment: string, minutes: number) => `${environment} · ${minutes} dakika`,
  adaptation: "Canlı uyarlama",
  setup: "Ortamı kur",
  materialSwap: "Malzemeyi değiştir",
  facilitation: "Kolaylaştır",
  evidence: "Kanıtı yakala",
  family: "Aileye uzatma",
  safety: "Güvenlik",
  provenance: "MaarifOS özgün etkinliğidir; resmî MEB etkinliği veya değerlendirme aracı değildir.",
  adding: "Ekleniyor",
  addToPlan: "Planıma ekle",
  preparing: "Hazırlanıyor",
  print: "Yazdır",
  opening: "Açılıyor",
  childMode: "Çocuk Modunda uygula",
  childModeLabel: (title: string) => `${title} etkinliğini Çocuk Modunda uygula`,
  childModeNotice: "Çocuk Modu yetişkin eşliğindedir; dokunuşlar tek başına değerlendirme kaydı oluşturmaz.",
  observationUnavailable: "Bu ekrandan gözlem açma bağlantısı kullanılamıyor.",
  unsupportedAge: "Etkinlik seçilen TYMM yaş bandını desteklemiyor.",
  invalidApplication: "Etkinlik uygulama kimliği doğrulanamadı; gözlem açılmadı.",
} as const;
