import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {KeyboardInput} from '../../mobile';
import {civilDateInIstanbul} from '../../core/domain/attendance.ts';
import {resolveActiveClassroomScope} from '../../core/domain/classroom-scope.ts';
import {currentClassDutySchedules,type ClassDutyConfig,type ClassDutyKind,type ClassDutyRow} from '../../core/domain/class-duty-schedule.ts';
import type {DataSnapshot} from '../../core/domain/model.ts';
import type {LocalDataStore} from '../../core/repository/contracts.ts';
import {requestPdfDocument} from '../documents/pdf-preview-model.ts';
import {dutyAddDays,dutyDefaultConfig,dutyEligible,dutyKindLabel,dutyMonthPeriod,dutyTeachingDates,previewDutyRequest,type DutyChange,type DutyPreview,type DutyRequest} from './class-duty-model.ts';
import {applyClassDutySchedule} from './class-duty-service.ts';
import {dutyDocumentModel,dutyStatusLabel} from './class-duty-document-model.ts';
import {createClassDutyRecipe,createClassDutyBoardRecipe} from './class-duty-documents.ts';
import {readClassDutySpreadsheet} from './class-duty-spreadsheet.ts';
import './class-duty-schedule.css';

export interface ClassDutySchedulePanelProps{store:LocalDataStore;refreshKey?:unknown;disabled?:boolean;initialKind?:ClassDutyKind;initialScheduleId?:string;initialMonth?:string;onChanged?:()=>void;onOpenCalendar?:(civilDate:string)=>void}
const days=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma'];
const participation=['Sevdiği oyunu sınıfla paylaşma','Seçtiği kitabı birlikte inceleme','İlgi duyduğu bir nesneyi tanıtma','Sınıfla birlikte şarkı veya ritim seçme'];
const nextMonth=(value:string)=>{const d=new Date(`${value}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);return d.toISOString().slice(0,7);};
export function ClassDutySchedulePanel({store,refreshKey,disabled=false,initialKind='fruit',initialScheduleId,initialMonth,onChanged,onOpenCalendar}:ClassDutySchedulePanelProps){
 const today=civilDateInIstanbul(new Date()),[data,setData]=useState<DataSnapshot|null>(null),[kind,setKind]=useState<ClassDutyKind>(initialKind),[month,setMonth]=useState(initialMonth??today.slice(0,7)),[scheduleId,setScheduleId]=useState(initialScheduleId??''),[config,setConfig]=useState<ClassDutyConfig|null>(null),[preview,setPreview]=useState<DutyPreview|null>(null),[selected,setSelected]=useState<string[]>([]),[imports,setImports]=useState<DutyChange[]>([]),[importIds,setImportIds]=useState<string[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[shiftDays,setShiftDays]=useState(7);
 const generation=useRef(0),lock=useRef(false),intent=useRef(''),current=useRef({store,disabled,scheduleId,initialScheduleId,initialKind});current.current={store,disabled,scheduleId,initialScheduleId,initialKind};
 useEffect(()=>{setScheduleId(initialScheduleId??'');setKind(initialKind);intent.current='';setPreview(null);setImports([]);setSuccess('');},[store,initialScheduleId,initialKind]);
 useEffect(()=>{const version=++generation.current;setLoading(true);setData(null);setPreview(null);setError('');void store.readSnapshot().then(snapshot=>{if(version!==generation.current)return;const scope=resolveActiveClassroomScope(snapshot);if(!scope)throw Error('Görev çizelgesi için etkin sınıfı seçin.');const records=currentClassDutySchedules(snapshot,scope),record=records.find(r=>r.workflow.scheduleId===scheduleId);if(record&&record.workflow.config.kind!==kind)setKind(record.workflow.config.kind);const key=`${scope.classroomId}:${kind}:${month}:${scheduleId}`;if(intent.current!==key){setConfig(record?structuredClone(record.workflow.config):dutyDefaultConfig(snapshot,kind,month));intent.current=key;}setSelected(old=>old.filter(id=>record?.workflow.rows.some(r=>r.id===id)));setData(snapshot);setLoading(false);}).catch(e=>{if(version===generation.current){setError(e instanceof Error?e.message:'Çizelge kaynakları okunamadı.');setLoading(false);}});return()=>{++generation.current;};},[store,refreshKey,revision,kind,month,scheduleId]);
 const scope=data?resolveActiveClassroomScope(data):null,records=data?currentClassDutySchedules(data,scope??undefined):[],record=records.find(r=>r.workflow.scheduleId===scheduleId),blocked=disabled||busy||loading;
 const name=(id:string)=>String(data?.students.find(s=>s.id===id)?.displayName??'Kayıt bulunamadı');
 function reset(){setPreview(null);setImports([]);setImportIds([]);setSuccess('');}
 function chooseRecord(id:string){reset();intent.current='';setScheduleId(id);const found=records.find(r=>r.workflow.scheduleId===id);if(found){setKind(found.workflow.config.kind);setMonth(found.workflow.config.startOn.slice(0,7));}}
 function changeConfig(patch:Partial<ClassDutyConfig>){setPreview(null);setConfig(old=>old?{...old,...patch}:old);}
 function prepare(request:DutyRequest){if(!data||blocked)return;setError('');setSuccess('');try{setPreview(previewDutyRequest(data,request));}catch(e){setError(e instanceof Error?e.message:'Seçim hazırlanamadı.');}}
 function changesRequest(changes:DutyChange[]):DutyRequest{return{kind:'changes',scheduleId,operationId:crypto.randomUUID(),changes};}
 async function apply(p:DutyPreview){if(lock.current||current.current.disabled||loading)return;lock.current=true;setBusy(true);setError('');setSuccess('');const source=current.current;let committed=false;try{const result=await applyClassDutySchedule(store,{request:p.request,expectedFingerprint:p.expectedFingerprint});committed=true;if(current.current.store!==source.store||current.current.initialScheduleId!==source.initialScheduleId||current.current.initialKind!==source.initialKind)return;setSuccess(result.summary);setScheduleId(result.record.workflow.scheduleId);intent.current='';setImports([]);setPreview(null);flushSync(()=>{setRevision(v=>v+1);onChanged?.();});}catch(e){if(current.current.store===source.store)setError(committed?'Çizelge kaydedildi; görünüm henüz yenilenemedi.':e instanceof Error?e.message:'Çizelge kaydedilemedi.');}finally{lock.current=false;setBusy(false);}}
 function direct(changes:DutyChange[]){if(!data||blocked)return;try{void apply(previewDutyRequest(data,changesRequest(changes)));}catch(e){setError(e instanceof Error?e.message:'Görev seçimi hazırlanamadı.');}}
 async function document(board=false){if(lock.current||current.current.disabled||loading)return;lock.current=true;setBusy(true);setError('');const version=generation.current;try{const recipe=board?await createClassDutyBoardRecipe(store,month):await createClassDutyRecipe(store,scheduleId);if(version!==generation.current||current.current.disabled)return;await requestPdfDocument(recipe);}catch(e){if(version===generation.current)setError(e instanceof Error?e.message:'Belge hazırlanamadı.');}finally{lock.current=false;setBusy(false);}}
 async function readExcel(file:File){if(lock.current||blocked||!data||!record)return;lock.current=true;setBusy(true);setError('');const version=generation.current;try{const result=await readClassDutySpreadsheet(new Uint8Array(await file.arrayBuffer()),dutyDocumentModel(data,scheduleId));if(version!==generation.current||current.current.disabled)return;setImports(result.changes);setImportIds(result.changes.map(c=>c.rowId));setPreview(null);setSuccess(result.changes.length?`${result.changes.length} Excel farkı hazır.${result.ignoredNameEdits?' Ad hücresi değişiklikleri kimlik değiştirmez; kayıtlı adlar korunur.':''}`:'Excel dosyasında uygulanacak görev farkı yok.');}catch(e){if(version===generation.current)setError(e instanceof Error?e.message:'Excel okunamadı.');}finally{lock.current=false;setBusy(false);}}
 const newlyEligible=data&&config&&config.startOn<=config.endOn&&config.endOn>=today?data.students.filter(s=>!config.studentIds.includes(s.id)&&dutyTeachingDates(data,today>config.startOn?today:config.startOn,config.endOn).some(day=>dutyEligible(data,s.id,day))):[];
 const rowText=(row:ClassDutyRow|null)=>row?`${name(row.studentId)} · ${row.startOn}${row.endOn!==row.startOn?` – ${row.endOn}`:''} · ${dutyStatusLabel(row.status)}${row.locked?' · Sabit':''}`:'Görev yok';
 return <section className="class-duty" aria-label="Sınıf görev çizelgeleri"><h2>Meyve günü ve haftanın çocuğu</h2><p>Çocukları ve günleri seçin; MaarifOS önceki görevleri, kayıt dönemini ve okul takvimini kullanarak dağıtımı hazırlasın.</p>
  <fieldset disabled={blocked}><legend>Çizelge ve dönem</legend><label>Kayıtlı çizelge<select value={scheduleId} onChange={e=>chooseRecord(e.target.value)}><option value="">Yeni çizelge</option>{records.map(r=><option key={r.id} value={r.workflow.scheduleId}>{dutyKindLabel(r.workflow.config.kind)} · {r.workflow.config.startOn} – {r.workflow.config.endOn} · v{r.workflow.revision}</option>)}</select></label><label>Görev türü<select value={kind} disabled={!!record} onChange={e=>{reset();setKind(e.target.value as ClassDutyKind);}}><option value="fruit">Meyve günü</option><option value="child-of-week">Haftanın çocuğu</option></select></label><label>Ay<KeyboardInput type="month" value={month} disabled={!!record} onChange={e=>{if(e.target.value){reset();setMonth(e.target.value);}}}/></label>{record&&<button type="button" onClick={()=>{reset();setScheduleId('');setMonth(nextMonth(record.workflow.config.endOn.slice(0,7)));}}>Sonraki ayı önceki seçimlerle hazırla</button>}</fieldset>
  {config&&data&&<><details open={!record}><summary>Gün, çocuk ve kapasite seçimleri</summary><fieldset disabled={blocked}><legend>Dağıtım kapsamı</legend><label>Başlangıç<KeyboardInput type="date" value={config.startOn} onChange={e=>changeConfig({startOn:e.target.value})}/></label><label>Bitiş<KeyboardInput type="date" value={config.endOn} onChange={e=>changeConfig({endOn:e.target.value})}/></label><button type="button" onClick={()=>changeConfig({endOn:String(data.academicYears.find(y=>y.id===scope?.academicYearId)?.endDate??config.endOn)})}>Eğitim yılı sonuna kadar hazırla</button><div className="class-duty-options">{days.map((label,index)=><label key={label}><input type="checkbox" checked={config.weekdays.includes(index+1)} onChange={e=>changeConfig({weekdays:e.target.checked?[...config.weekdays,index+1].sort():config.weekdays.filter(d=>d!==index+1)})}/>{label}</label>)}</div><label>{kind==='fruit'?'Gün başına çocuk':'Hafta başına çocuk'}<KeyboardInput type="number" min={1} max={20} value={config.capacity} onChange={e=>changeConfig({capacity:Number(e.target.value)})}/></label><fieldset><legend>Seçilen çocuklar</legend>{data.students.filter(s=>s.classroomId===scope?.classroomId||config.studentIds.includes(s.id)).map(s=><label key={s.id} className="class-duty-choice"><input type="checkbox" checked={config.studentIds.includes(s.id)} onChange={e=>changeConfig({studentIds:e.target.checked?[...config.studentIds,s.id]:config.studentIds.filter(id=>id!==s.id)})}/>{String(s.displayName)}</label>)}</fieldset>{kind==='child-of-week'&&<><label className="class-duty-choice"><input type="checkbox" checked={config.avoidFruitWeek} onChange={e=>changeConfig({avoidFruitWeek:e.target.checked})}/>Aynı çocuğun meyve günü olan haftasını geç</label><fieldset><legend>Katılım kartına alınacak hazırlıklar</legend>{[...new Set([...participation,...config.participation])].map(text=><label className="class-duty-choice" key={text}><input type="checkbox" checked={config.participation.includes(text)} onChange={e=>changeConfig({participation:e.target.checked?[...config.participation,text]:config.participation.filter(t=>t!==text)})}/>{text}</label>)}</fieldset></>}</fieldset></details>
  <button type="button" className="class-duty-primary" disabled={blocked} onClick={()=>prepare({kind:record?'redistribute':'create',scheduleId:record?.workflow.scheduleId??crypto.randomUUID(),operationId:crypto.randomUUID(),config})}>{record?'Kalan günlerin değişikliklerini hazırla':'Adil dağıtımı hazırla'}</button>{record&&<button type="button" disabled={blocked} onClick={()=>{const next={...config,seed:config.seed+1};setConfig(next);prepare({kind:'redistribute',scheduleId,operationId:crypto.randomUUID(),config:next});}}>Yalnız gelecek görevleri yeniden dağıt</button>}
  </>}
  {preview&&<section className="class-duty-preview" aria-label="Hazırlanan çizelge farkları"><h3>{preview.rows.length} görev · {preview.diff.length} değişiklik · v{preview.revision}</h3><p>{preview.config.startOn} – {preview.config.endOn} · {preview.skippedDates} kapalı gün dağıtıma alınmadı.</p>{preview.unassignedStudentIds.length>0&&<div><p>Bu dönemde henüz sıra gelmeyen {preview.unassignedStudentIds.length} çocuk: {preview.unassignedStudentIds.map(name).join(' · ')}</p><button type="button" disabled={blocked||preview.config.capacity>=20||(preview.request.kind!=="create"&&preview.request.kind!=="redistribute")} onClick={()=>{const next={...preview.config,capacity:preview.config.capacity+1};setConfig(next);prepare({...preview.request,...((preview.request.kind==='create'||preview.request.kind==='redistribute')?{config:next}:{}),operationId:crypto.randomUUID()} as DutyRequest);}}>Kapasiteyi 1 artırarak yeniden hazırla</button>{(preview.request.kind==="create"||preview.request.kind==="redistribute")&&<><button type="button" disabled={blocked||preview.config.weekdays.length===5} onClick={()=>{const weekday=[1,2,3,4,5].find(d=>!preview.config.weekdays.includes(d));if(!weekday)return;const next={...preview.config,weekdays:[...preview.config.weekdays,weekday].sort()};setConfig(next);prepare({...preview.request,config:next,operationId:crypto.randomUUID()} as DutyRequest);}}>Bir öğretim günü daha ekle</button><button type="button" disabled={blocked} onClick={()=>{const yearEnd=String(data?.academicYears.find(y=>y.id===scope?.academicYearId)?.endDate??preview.config.endOn);const end=[dutyMonthPeriod(nextMonth(preview.config.endOn.slice(0,7))).endOn,yearEnd].sort()[0]!;const next={...preview.config,endOn:end};setConfig(next);prepare({...preview.request,config:next,operationId:crypto.randomUUID()} as DutyRequest);}}>Sonraki ay sonuna kadar yeniden hazırla</button></>}</div>}{preview.unfilled>0&&<p>Üyelik, çakışma veya seçili kapasite nedeniyle {preview.unfilled} alan boş kaldı. Seçimleri açarak gün veya çocuk ekleyebilirsiniz.</p>}<ol>{preview.diff.map(diff=><li key={diff.rowId}>{diff.before&&<p>Önce: {rowText(diff.before)}</p>}<p>Sonuç: {rowText(diff.after)}</p></li>)}</ol><button type="button" className="class-duty-primary" disabled={blocked} onClick={()=>void apply(preview)}>{preview.diff.length} değişikliği çizelgeye ve takvime kaydet</button></section>}
  {record&&data&&<><div className="class-duty-actions"><button type="button" disabled={blocked||!record.workflow.rows.length} onClick={()=>void document()}>Çizelgeyi PDF, Excel veya Word olarak hazırla</button><button type="button" disabled={blocked} onClick={()=>void document(true)}>Bu ayın sınıf panosu paketini hazırla</button><label>Excel değişikliklerini getir<input type="file" accept=".xlsx" disabled={blocked} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void readExcel(file);}}/></label></div>
  {imports.length>0&&<fieldset disabled={blocked}><legend>Excel farklarını seç</legend>{imports.map(change=><label className="class-duty-choice" key={change.rowId}><input type="checkbox" checked={importIds.includes(change.rowId)} onChange={e=>setImportIds(old=>e.target.checked?[...old,change.rowId]:old.filter(id=>id!==change.rowId))}/>{name(change.studentId??record.workflow.rows.find(r=>r.id===change.rowId)!.studentId)} · {change.startOn??record.workflow.rows.find(r=>r.id===change.rowId)!.startOn} · {change.status?dutyStatusLabel(change.status):'Görev düzenlemesi'}</label>)}<button type="button" disabled={!importIds.length} onClick={()=>prepare(changesRequest(imports.filter(c=>importIds.includes(c.rowId))))}>Seçilen Excel farklarını hazırla</button></fieldset>}
  <h3>Kayıtlı görevler · v{record.workflow.revision}</h3>{newlyEligible.length>0&&config&&<div><p>Bu dönemde göreve katılabilecek yeni çocuklar: {newlyEligible.map(s=>String(s.displayName)).join(" · ")}</p><button type="button" disabled={blocked} onClick={()=>{const next={...config,studentIds:[...config.studentIds,...newlyEligible.map(s=>s.id)]};setConfig(next);prepare({kind:"redistribute",scheduleId,operationId:crypto.randomUUID(),config:next});}}>Yeni çocukları kalan günlere dahil et</button></div>}<fieldset disabled={blocked}><legend>Seçili gelecek görevleri düzenle</legend><label>Kaydırılacak gün sayısı<KeyboardInput type="number" min={1} max={60} value={shiftDays} onChange={e=>setShiftDays(Number(e.target.value))}/></label><button type="button" disabled={!selected.length} onClick={()=>prepare({kind:'shift',scheduleId,operationId:crypto.randomUUID(),rowIds:selected,days:shiftDays})}>{selected.length} seçili görevi uygun güne kaydır</button><button type="button" disabled={selected.length!==2} onClick={()=>{const [a,b]=selected.map(id=>record.workflow.rows.find(r=>r.id===id)!);prepare(changesRequest([{rowId:a!.id,studentId:b!.studentId},{rowId:b!.id,studentId:a!.studentId}]));}}>İki çocuğun görevini karşılıklı değiştir</button></fieldset>
  {record.workflow.rows.map(row=><DutyRow key={`${record.id}:${row.id}`} row={row} childrenOptions={data.students.filter(s=>s.classroomId===scope?.classroomId).map(s=>({id:s.id,label:String(s.displayName)}))} name={name(row.studentId)} absent={data.attendanceRecords.some(a=>a.studentId===row.studentId&&a.civilDate===row.startOn&&a.status==="absent"&&!a.deletedAt)} today={today} disabled={blocked} selected={selected.includes(row.id)} onSelect={value=>setSelected(old=>value?[...old,row.id]:old.filter(id=>id!==row.id))} onPrepare={change=>prepare(changesRequest([change]))} onDirect={change=>direct([change])} onPostpone={()=>{const target=dutyTeachingDates(data,dutyAddDays(row.startOn,1),record.workflow.config.endOn)[0];if(target)prepare(changesRequest([{rowId:row.id,startOn:target}]));else setError('Dönem içinde yeni öğretim günü yok. Seçili görevi kaydırarak dönem sonunu uzatın.');}} onOpen={onOpenCalendar?()=>onOpenCalendar(row.startOn):undefined}/>)}
  </>}
  {loading&&<p role="status">Görev ve takvim kaynakları hazırlanıyor…</p>}{success&&<p className="class-duty-success" role="status">{success}</p>}{error&&<div role="alert"><p>{error}</p><button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Güncel kayıtlarla yeniden aç</button></div>}
 </section>;
}
function DutyRow({row,childrenOptions,name,absent,today,disabled,selected,onSelect,onPrepare,onDirect,onPostpone,onOpen}:{row:ClassDutyRow;childrenOptions:{id:string;label:string}[];name:string;absent:boolean;today:string;disabled:boolean;selected:boolean;onSelect:(v:boolean)=>void;onPrepare:(c:DutyChange)=>void;onDirect:(c:DutyChange)=>void;onPostpone:()=>void;onOpen?:(()=>void)|undefined}){
 const [date,setDate]=useState(row.startOn),[child,setChild]=useState(row.studentId),editable=row.startOn>=today&&row.status==='planned'&&!row.locked;
 return <article className="class-duty-row"><label className="class-duty-choice"><input type="checkbox" disabled={disabled||!editable||row.startOn===today} checked={selected} onChange={e=>onSelect(e.target.checked)}/><strong>{name}</strong></label><p>{row.startOn}{row.endOn!==row.startOn?` – ${row.endOn}`:''} · {dutyStatusLabel(row.status)}{row.locked?' · Sabit':''}</p><div className="class-duty-actions">{onOpen&&<button type="button" disabled={disabled} onClick={onOpen}>Takvimde aç</button>}<button type="button" disabled={disabled} onClick={()=>onDirect({rowId:row.id,locked:!row.locked})}>{row.locked?'Günün sabitliğini kaldır':'Bu günü sabitle'}</button>{row.status==='planned'&&row.startOn<=today&&<><button type="button" disabled={disabled} onClick={()=>onDirect({rowId:row.id,status:'completed'})}>Görevi gerçekleşti olarak kaydet</button><button type="button" disabled={disabled} onClick={()=>onDirect({rowId:row.id,status:'missed'})}>Gerçekleşmedi olarak kaydet</button></>}{row.status==='planned'&&<button type="button" disabled={disabled} onClick={()=>onDirect({rowId:row.id,status:'cancelled'})}>Bu görevi iptal et</button>}</div>{editable&&absent&&<div><p>Görev gününde kayıtlı devamsızlık var.</p><button type="button" disabled={disabled} onClick={onPostpone}>Devamsızlık nedeniyle uygun güne ertele</button></div>}{editable&&<details><summary>Çocuğu veya günü değiştir</summary><fieldset disabled={disabled}><label>Görev günü<KeyboardInput type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Görevi alacak çocuk<select value={child} onChange={e=>setChild(e.target.value)}>{childrenOptions.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><button type="button" onClick={()=>onPrepare({rowId:row.id,startOn:date,studentId:child})}>Bu satırın değişikliğini hazırla</button><button type="button" onClick={onPostpone}>Sonraki öğretim gününe ertele</button></fieldset></details>}</article>;
}







