import { useEffect, useState, type ReactNode } from "react";
import { KeyboardInput, KeyboardTextarea, useKeyboard } from "../../mobile";
import { civilDateInIstanbul } from "../../core/domain/attendance.ts";
import { resolveActiveClassroomScope, type ActiveClassroomScope } from "../../core/domain/classroom-scope.ts";
import { CONSENT_PURPOSES, consentTripEligibleStudents, consentTripRecords, latestTripCheck, resolveConsentForUse, tripState, type ConsentDecision, type ConsentDocument, type ConsentPurpose, type ConsentTripRecord, type TripStage } from "../../core/domain/consent-trips.ts";
import type { DataSnapshot, StoredRecord } from "../../core/domain/model.ts";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { requestPdfDocument } from "../documents/pdf-preview-model.ts";
import { consentTrackingPdfRecipe, tripCountingPdfRecipe } from "./consent-trip-document.ts";
import { CONSENT_TRIPS_CHANGED_EVENT, executeConsentTrip, readConsentTripSnapshot, type ConsentTripCommand } from "./consent-trip-service.ts";
import { consentClockLabel, consentDateLabel, consentPurposeLabels, consentSourceLabels, consentStateLabels, consentTripCopy, tripStageLabels } from "./consent-trip-copy.ts";
import "./consent-trips.css";

export interface ConsentTripsWorkspaceProps { store: LocalDataStore; initialStudentId?: string; initialSection?: "consents" | "trips"; refreshKey?: unknown; disabled?: boolean; onChanged?(): void }
type Save = (command: ConsentTripCommand) => Promise<ConsentTripRecord | null>;
const Field = ({ label, value, onChange, type = "text", maxLength = 500, min, max }: { label: string; value: string; onChange(value: string): void; type?: string; maxLength?: number; min?: string; max?: string }) => <label>{label}<KeyboardInput aria-label={label} value={value} onChange={e => onChange(e.target.value)} type={type} maxLength={maxLength} min={min} max={max} /></label>;
const Note = ({ label, value, onChange, maxLength = 2000 }: { label: string; value: string; onChange(value: string): void; maxLength?: number }) => <label>{label}<KeyboardTextarea aria-label={label} value={value} onChange={e => onChange(e.target.value)} maxLength={maxLength} /><small>{value.length.toLocaleString("tr-TR")} / {maxLength.toLocaleString("tr-TR")}</small></label>;
const Toggle = ({ checked, onClick, children, disabled }: { checked: boolean; onClick(): void; children: ReactNode; disabled?: boolean }) => <button type="button" className="consent-toggle" role="checkbox" aria-checked={checked} disabled={disabled} onClick={onClick}><span aria-hidden="true">{checked ? "✓" : "+"}</span>{children}</button>;

export function ConsentTripsWorkspace(props: ConsentTripsWorkspaceProps) {
  const [snapshot, setSnapshot] = useState<DataSnapshot | null>(null);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [revision, setRevision] = useState(0);
  const [busy, setBusy] = useState(false);
  const [section, setSection] = useState(props.initialSection ?? "consents");
  const keyboard = useKeyboard();
  const reload = () => setRevision(r => r + 1);
  useEffect(() => { const refresh = () => reload(); window.addEventListener(CONSENT_TRIPS_CHANGED_EVENT, refresh); window.addEventListener("focus", refresh); return () => { window.removeEventListener(CONSENT_TRIPS_CHANGED_EVENT, refresh); window.removeEventListener("focus", refresh); }; }, []);
  useEffect(() => { let alive = true; void readConsentTripSnapshot(props.store).then(s => { if (alive) setSnapshot(s); }).catch(() => { if (alive) setError("İzin ve gezi kayıtları okunamadı. Yeniden deneyin."); }); return () => { alive = false; }; }, [props.store, props.refreshKey, revision]);
  const scope = snapshot ? resolveActiveClassroomScope(snapshot) : null;
  const today = civilDateInIstanbul(new Date());
  const save: Save = async command => {
    if (!scope || busy || props.disabled) return null;
    setBusy(true); setMessage(""); setError(""); keyboard.hide();
    try { const result = await executeConsentTrip(props.store, { scope, command }); setSnapshot(await readConsentTripSnapshot(props.store)); props.onChanged?.(); setMessage(consentTripCopy.saved); return result; }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Kaydedilemedi. Önceki kayıtlar korundu."); return null; }
    finally { setBusy(false); }
  };
  const pdf = async (create: () => ReturnType<typeof consentTrackingPdfRecipe>) => {
    keyboard.hide(); setError("");
    try { await requestPdfDocument(create()); } catch (reason) { setError(reason instanceof Error ? reason.message : "PDF hazırlanamadı."); }
  };
  if (!snapshot) return <div role="status">İzin ve gezi kayıtları hazırlanıyor…{error ? <p role="alert">{error}<button onClick={reload}>Yeniden dene</button></p> : null}</div>;
  if (!scope) return <p>İzin ve gezi kayıtları için önce bir sınıf seçin.</p>;
  const records = consentTripRecords(snapshot).filter(r => r.classroomId === scope.classroomId && r.academicYearId === scope.academicYearId);
  const students = snapshot.students.filter(s => s.classroomId === scope.classroomId && s.academicYearId === scope.academicYearId && typeof s.deletedAt !== "string");
  return <div className="consent-trips" data-testid="consent-trips-workspace">
    <p>{consentTripCopy.scope}</p>
    <div className="consent-tabs" role="group" aria-label="İzin veya gezi alanı"><button type="button" aria-pressed={section === "consents"} onClick={() => { keyboard.hide(); setSection("consents"); }}>Veli izinleri</button><button type="button" aria-pressed={section === "trips"} onClick={() => { keyboard.hide(); setSection("trips"); }}>Gezi sayımı</button></div>
    {error ? <p className="consent-error" role="alert">{error}</p> : null}{message ? <p className="consent-success" role="status">{message}</p> : null}
    <button type="button" disabled={busy} onClick={reload}>{consentTripCopy.refresh}</button>
    <fieldset disabled={busy || props.disabled} className="consent-fieldset">
      <div hidden={section !== "consents"}><ConsentsPanel snapshot={snapshot} scope={scope} records={records} students={students} today={today} initialStudentId={props.initialStudentId} save={save} pdf={pdf} /></div>
      <div hidden={section !== "trips"}><TripsPanel snapshot={snapshot} scope={scope} records={records} students={students} today={today} save={save} pdf={pdf} /></div>
    </fieldset>
    {busy ? <p role="status">Cihaza kaydediliyor…</p> : null}
  </div>;
}
type PanelProps = { snapshot: DataSnapshot; scope: ActiveClassroomScope; records: ConsentTripRecord[]; students: StoredRecord[]; today: string; save: Save; pdf(create: () => ReturnType<typeof consentTrackingPdfRecipe>): Promise<void> };
function ConsentsPanel({ snapshot, scope, records, students, today, initialStudentId, save, pdf }: PanelProps & { initialStudentId?: string }) {
  const [documentId, setDocumentId] = useState("");
  const [studentId, setStudentId] = useState(initialStudentId ?? "");
  const [editor, setEditor] = useState<"new" | "revision" | null>(null);
  const documents = records.filter(r => r.workflow.kind === "consent-document");
  const selectedDocument = documents.find(r => r.id === documentId);
  const doc = selectedDocument?.workflow.kind === "consent-document" ? selectedDocument.workflow : null;
  const resolution = doc && studentId ? resolveConsentForUse(snapshot, { ...scope, studentId, purpose: doc.purpose, eventId: doc.eventId, documentId, civilDate: today }) : null;
  return <section aria-label="Belgeye bağlı veli izinleri">
    <h3>Belgeye bağlı veli izinleri</h3><p>{consentTripCopy.legacy}</p>
    <button type="button" onClick={() => setEditor("new")}>Yeni izin belgesi tanımla</button>
    {editor ? <DocumentEditor key={`${editor}:${documentId}`} previous={editor === "revision" ? selectedDocument : undefined} today={today} year={snapshot.academicYears.find(y => y.id === scope.academicYearId)!} save={save} onSaved={r => { setDocumentId(r.id); setEditor(null); }} onCancel={() => setEditor(null)} /> : null}
    <label>İzin belgesi<select aria-label="İzin belgesi" value={documentId} onChange={e => setDocumentId(e.target.value)}><option value="">Belge seçin</option>{documents.map(r => <option key={r.id} value={r.id}>{r.workflow.kind === "consent-document" ? `${r.workflow.title} · v${r.workflow.version}` : ""}</option>)}</select></label>
    {doc ? <article className="consent-card"><h4>{doc.title} · Sürüm {doc.version}</h4><p>{consentPurposeLabels[doc.purpose]}{doc.eventTitle ? ` · ${doc.eventTitle}` : ""}</p><p>{consentDateLabel(doc.validFrom)} – {consentDateLabel(doc.validUntil)}</p><details><summary>Belge metni ve sürüm bilgisi</summary><p className="consent-preserve">{doc.body || "Belge metni girilmedi. İzin kaydındaki kaynak açıklaması asıl belgeyi gösterir."}</p><p>Önceki sürüm: {doc.previousDocumentId ? documents.find(d => d.id === doc.previousDocumentId)?.workflow.kind === "consent-document" ? `Sürüm ${doc.version - 1}` : "Kaynak bulunamadı" : "İlk sürüm"}</p></details><div className="consent-actions"><button type="button" onClick={() => setEditor("revision")}>Yeni belge sürümü</button><button type="button" onClick={() => void pdf(() => consentTrackingPdfRecipe(snapshot, documentId, today))}>İzin çizelgesi PDF önizle</button></div></article> : <p>Her izin bir belge başlığına, sürümüne ve kullanım amacına bağlanır.</p>}
    <label>İzin çocuğu<select aria-label="İzin çocuğu" value={studentId} onChange={e => setStudentId(e.target.value)}><option value="">Çocuk seçin</option>{students.map(s => <option key={s.id} value={s.id}>{String(s.displayName)}{s.active === false ? " · arşiv" : ""}</option>)}</select></label>
    {doc && studentId && resolution ? <><p className={`consent-state consent-state-${resolution.state}`}><strong>{consentStateLabels[resolution.state]}</strong> · {resolution.reason}</p><DecisionEditor key={`${documentId}:${studentId}:${resolution.decision?.id ?? "empty"}`} documentId={documentId} doc={doc} studentId={studentId} previous={records.filter(r => r.studentId === studentId && r.workflow.kind === "consent-decision" && r.workflow.documentId === documentId).at(-1)} today={today} save={save} disabled={students.find(s => s.id === studentId)?.active === false || resolution.state === "superseded"} /><details><summary>İzin karar geçmişi</summary><ol className="consent-history">{records.filter(r => r.studentId === studentId && r.workflow.kind === "consent-decision" && r.workflow.documentId === documentId).map(r => r.workflow.kind === "consent-decision" ? <li key={r.id}><strong>{r.workflow.decision === "grant" ? "İzin kaydı" : "Geri çekme"}</strong> · {consentDateLabel(r.workflow.signedOn)}<p>{r.workflow.signatory} · {r.workflow.signatoryRole}</p><p>{consentSourceLabels[r.workflow.source]} · {r.workflow.sourceReference}</p>{r.workflow.note ? <p>{r.workflow.note}</p> : null}<small>Kayda giriş: {consentDateLabel(r.civilDate)} {consentClockLabel(r.createdAt)}</small></li> : null)}</ol></details></> : null}
  </section>;
}
function DocumentEditor({ previous, today, year, save, onSaved, onCancel }: { previous?: ConsentTripRecord; today: string; year: StoredRecord; save: Save; onSaved(r: ConsentTripRecord): void; onCancel(): void }) {
  const old = previous?.workflow.kind === "consent-document" ? previous.workflow : null;
  const [title, setTitle] = useState(old?.title ?? "");
  const [purpose, setPurpose] = useState<ConsentPurpose>(old?.purpose ?? "trip");
  const [eventTitle, setEventTitle] = useState(old?.eventTitle ?? "");
  const [body, setBody] = useState(old?.body ?? "");
  const [from, setFrom] = useState(old?.validFrom ?? (today < String(year.startDate) ? String(year.startDate) : today));
  const [until, setUntil] = useState(old?.validUntil ?? String(year.endDate));
  const ready = title.trim() && from && until && from <= until && (purpose !== "trip" || eventTitle.trim());
  return <div className="consent-card" aria-label="İzin belgesi formu"><h4>{old ? `Yeni sürüm ${old.version + 1}` : "Yeni izin belgesi"}</h4><Field label="Belge başlığı" value={title} onChange={setTitle} maxLength={300} /><label>İzin amacı<select aria-label="İzin amacı" value={purpose} disabled={!!old} onChange={e => setPurpose(e.target.value as ConsentPurpose)}>{CONSENT_PURPOSES.map(p => <option key={p} value={p}>{consentPurposeLabels[p]}</option>)}</select></label>{purpose === "trip" ? <Field label="İzin verilen gezi / etkinlik" value={eventTitle} onChange={setEventTitle} maxLength={300} /> : null}<Field label="Belge geçerlilik başlangıcı" type="date" value={from} onChange={setFrom} min={String(year.startDate)} max={String(year.endDate)} /><Field label="Belge geçerlilik sonu" type="date" value={until} onChange={setUntil} min={from} max={String(year.endDate)} /><Note label="Belge metni (isteğe bağlı)" value={body} onChange={setBody} maxLength={12000} /><p>Başlık ve metin kaydı dijital imza oluşturmaz. Yeni sürüm eski izinleri yeni metne otomatik taşımaz.</p><div className="consent-actions"><button type="button" onClick={onCancel}>Belge tanımından vazgeç</button><button type="button" className="consent-primary" disabled={!ready} onClick={() => void save({ action: "document", document: { previousDocumentId: previous?.id ?? null, title, purpose, eventTitle: purpose === "trip" ? eventTitle : "", body, validFrom: from, validUntil: until } }).then(r => { if (r) onSaved(r); })}>Belge tanımını kaydet</button></div>{!ready ? <small>Belge başlığı, geçerli tarihler ve gezi amacı için etkinlik adı gerekli.</small> : null}</div>;
}
function DecisionEditor({ documentId, doc, studentId, previous, today, save, disabled }: { documentId: string; doc: ConsentDocument; studentId: string; previous?: ConsentTripRecord; today: string; save: Save; disabled: boolean }) {
  const [decision, setDecision] = useState<"grant" | "revoke">("grant");
  const [signatory, setSignatory] = useState(""); const [role, setRole] = useState("");
  const [signedOn, setSignedOn] = useState(today); const [from, setFrom] = useState(doc.validFrom); const [until, setUntil] = useState(doc.validUntil);
  const [source, setSource] = useState<ConsentDecision["source"]>("signed-paper"); const [reference, setReference] = useState(""); const [note, setNote] = useState(""); const [acknowledged, setAcknowledged] = useState(false);
  const ready = !disabled && acknowledged && signatory.trim() && role.trim() && reference.trim() && signedOn <= today && from <= until && from >= doc.validFrom && until <= doc.validUntil && (decision !== "revoke" || (previous && note.trim()));
  return <div className="consent-card"><h4>Veli kararını kaydet</h4><label>Karar<select aria-label="Veli izin kararı" value={decision} onChange={e => setDecision(e.target.value as "grant" | "revoke")}><option value="grant">İzin verildi</option><option value="revoke" disabled={!previous}>İzin geri çekildi</option></select></label><Field label="İmzalayan / beyanda bulunan kişi" value={signatory} onChange={setSignatory} maxLength={200} /><Field label="Yakınlığı / belge üzerindeki sıfatı" value={role} onChange={setRole} maxLength={120} /><Field label="İmza / beyan tarihi" type="date" value={signedOn} onChange={setSignedOn} max={today} /><Field label="İzin başlangıcı" type="date" value={from} onChange={setFrom} min={doc.validFrom} max={doc.validUntil} /><Field label="İzin sonu" type="date" value={until} onChange={setUntil} min={from} max={doc.validUntil} /><label>Kararın kaynağı<select aria-label="Kararın kaynağı" value={source} onChange={e => setSource(e.target.value as ConsentDecision["source"])}>{Object.entries(consentSourceLabels).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label><Field label="Kaynak belge / dosya açıklaması" value={reference} onChange={setReference} /><Note label={decision === "revoke" ? "Geri çekme gerekçesi" : "Karar notu (isteğe bağlı)"} value={note} onChange={setNote} /><p>{consentTripCopy.signature}</p><Toggle checked={acknowledged} onClick={() => setAcknowledged(v => !v)}>Belge sürümünü ve veli kararının kaynağını kontrol ettim</Toggle><button type="button" className="consent-primary" disabled={!ready} onClick={() => void save({ action: "decision", studentId, decision: { documentId, previousDecisionId: previous?.id ?? null, decision, signedOn, validFrom: from, validUntil: until, signatory, signatoryRole: role, source, sourceReference: reference, note } })}>Veli kararını kaydet</button>{!ready ? <small>İmzalayan, sıfat, kaynak, geçerli tarihler ve kontrol onayı gerekli. Geri çekme için gerekçe yazın.</small> : null}</div>;
}
function TripsPanel(props: PanelProps) {
  const { snapshot, scope, records, students, today, save, pdf } = props;
  const [tripId, setTripId] = useState(""); const [creating, setCreating] = useState(false);
  const plans = records.filter(r => r.workflow.kind === "trip-plan");
  const selected = plans.find(r => r.id === tripId);
  return <section aria-label="Gezi çıkış ve dönüş sayımı"><h3>Gezi çıkış ve dönüş sayımı</h3><p>{consentTripCopy.missing}</p><button type="button" onClick={() => setCreating(true)}>Yeni gezi planla</button>{creating ? <TripEditor snapshot={snapshot} scope={scope} records={records} today={today} save={save} onCancel={() => setCreating(false)} onSaved={r => { setTripId(r.id); setCreating(false); }} /> : null}<label>Gezi<select aria-label="Gezi" value={tripId} onChange={e => setTripId(e.target.value)}><option value="">Gezi seçin</option>{plans.map(r => <option key={r.id} value={r.id}>{r.workflow.kind === "trip-plan" ? `${r.workflow.title} · ${consentDateLabel(r.workflow.plannedOn)}` : ""}</option>)}</select></label>{selected ? <TripCounter key={selected.id} plan={selected} snapshot={snapshot} scope={scope} records={records} students={students} today={today} save={save} pdf={pdf} /> : <p>Önce izin belgesini tanımlayın, geziyi belgeye bağlayın ve katılımcıların izinlerini tamamlayın.</p>}</section>;
}
function TripEditor({ snapshot, scope, records, today, save, onSaved, onCancel }: { snapshot: DataSnapshot; scope: ActiveClassroomScope; records: ConsentTripRecord[]; today: string; save: Save; onSaved(r: ConsentTripRecord): void; onCancel(): void }) {
  const [title, setTitle] = useState(""); const [date, setDate] = useState(today); const [destination, setDestination] = useState(""); const [responsible, setResponsible] = useState(""); const [documentId, setDocumentId] = useState(""); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const documents = records.filter(r => r.workflow.kind === "consent-document" && r.workflow.purpose === "trip");
  const eligible = consentTripEligibleStudents(snapshot, scope, date);
  const ready = title.trim() && date && destination.trim() && responsible.trim() && documentId && selectedIds.length > 0 && selectedIds.every(id => eligible.some(s => s.id === id));
  return <div className="consent-card" aria-label="Gezi planı formu"><h4>Gezi planı</h4><Field label="Gezi adı" value={title} onChange={setTitle} maxLength={300} /><Field label="Gezi tarihi" type="date" value={date} onChange={setDate} /><Field label="Gidilecek yer" value={destination} onChange={setDestination} /><Field label="Gezi sorumlusu" value={responsible} onChange={setResponsible} maxLength={200} /><label>Gezi izin belgesi<select aria-label="Gezi izin belgesi" value={documentId} onChange={e => setDocumentId(e.target.value)}><option value="">Etkinliğe ait belge seçin</option>{documents.map(r => <option key={r.id} value={r.id}>{r.workflow.kind === "consent-document" ? `${r.workflow.title} · v${r.workflow.version} · ${r.workflow.eventTitle}` : ""}</option>)}</select></label>{!documents.length ? <p>Veli izinleri alanında önce bu gezi için izin belgesi tanımlayın.</p> : null}<h4>Gezi gününde sınıf kapsamındaki çocuklar</h4><p>Seçilen: {selectedIds.length}. Geziye katılmayacak çocukları seçmeyin.</p>{eligible.map(s => <Toggle key={s.id} checked={selectedIds.includes(s.id)} onClick={() => setSelectedIds(ids => ids.includes(s.id) ? ids.filter(id => id !== s.id) : [...ids, s.id])}>{String(s.displayName)}</Toggle>)}{!eligible.length ? <p>Bu tarihte sınıf kapsamında çocuk bulunamadı.</p> : null}<div className="consent-actions"><button type="button" onClick={onCancel}>Gezi planından vazgeç</button><button type="button" className="consent-primary" disabled={!ready} onClick={() => void save({ action: "plan", plan: { title, plannedOn: date, destination, responsible, documentId, selectedStudentIds: selectedIds } }).then(r => { if (r) onSaved(r); })}>Gezi planını kaydet</button></div>{!ready ? <small>Ad, tarih, yer, sorumlu, izin belgesi ve en az bir uygun çocuk gerekli.</small> : null}</div>;
}
function TripCounter({ plan, snapshot, scope, records, students, today, save, pdf }: PanelProps & { plan: ConsentTripRecord }) {
  const [stage, setStage] = useState<TripStage>("departure"); const [reason, setReason] = useState("");
  const [correctionId, setCorrectionId] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [outcome, setOutcome] = useState<"seen" | "not-seen">("seen");
  const state = tripState(records, plan.id);
  if (plan.workflow.kind !== "trip-plan") return null;
  const p = plan.workflow; const document = records.find(r => r.id === p.documentId); const doc = document?.workflow.kind === "consent-document" ? document.workflow : null;
  const roster = state.start ? state.roster.map(r => r.studentId) : p.selectedStudentIds;
  const permissions = p.selectedStudentIds.map(studentId => ({ studentId, resolution: resolveConsentForUse(snapshot, { ...scope, studentId, documentId: p.documentId, purpose: "trip", eventId: doc?.eventId ?? null, civilDate: p.plannedOn }) }));
  const canStart = state.status === "planned" && today === p.plannedOn && permissions.every(p => p.resolution.allowed) && roster.length > 0;
  const mark = (studentId: string, marked: "seen" | "not-seen", correction = "") => { const previous = latestTripCheck(records, plan.id, studentId, stage); return save({ action: "check", tripId: plan.id, expectedEventId: state.latestEventId, studentId, stage, outcome: marked, actualAt: new Date().toISOString(), previousCheckId: previous?.id ?? null, correctionReason: previous ? correction : "", note: "" }); };
  return <article className="consent-card" aria-label="Gezi sayım durumu"><h4>{p.title}</h4><p>{consentDateLabel(p.plannedOn)} · {p.destination}</p><p>Sorumlu: {p.responsible}</p><p>Belge: {doc ? `${doc.title} · Sürüm ${doc.version}` : "Bulunamadı"}</p><strong>{({ planned: "Planlandı", active: "Sayım sürüyor", completed: "Bütün dönüşler tamamlandı", cancelled: "Gezi iptal edildi" })[state.status]}</strong>
    {state.status === "planned" ? <><ul className="consent-status-list">{permissions.map(r => <li key={r.studentId}><strong>{String(snapshot.students.find(s => s.id === r.studentId)?.displayName ?? "Çocuk")}</strong><span>{consentStateLabels[r.resolution.state]}</span></li>)}</ul><button type="button" className="consent-primary" disabled={!canStart} onClick={() => void save({ action: "start", tripId: plan.id, expectedEventId: state.latestEventId })}>Kadroyu kilitle ve geziyi başlat</button>{!canStart ? <p>Başlangıç için gezi günü gelmeli ve seçilen her çocuk için bu belge sürümüne ait geçerli izin bulunmalı.</p> : null}</> : null}
    {state.start ? <><p>{consentTripCopy.locked}</p><p className="consent-counts"><strong>{state.returned} / {state.roster.length}</strong> çocuğun dönüşü görüldü · {state.missing} sayım bekliyor / görülmedi</p>{state.redactedParticipantCount ? <p>{state.redactedParticipantCount} tarihsel katılımcının kimliği gizlilik silmesiyle kaldırıldı.</p> : null}<label>Sayım aşaması<select aria-label="Sayım aşaması" value={stage} onChange={e => { setStage(e.target.value as TripStage); setCorrectionId(""); }}>{Object.entries(tripStageLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><ul className="consent-roster">{roster.map(id => { const child = snapshot.students.find(s => s.id === id); const check = latestTripCheck(records, plan.id, id, stage); const w = check?.workflow.kind === "trip-check" ? check.workflow : null; return <li key={id}><strong>{String(child?.displayName ?? "Çocuk")}</strong><span>{w ? `${w.outcome === "seen" ? "Görüldü" : "Görülmedi"} · ${consentClockLabel(w.actualAt)}` : "Sayım bekliyor"}</span>{state.status === "active" ? <div className="consent-actions">{w ? <button type="button" onClick={() => { setCorrectionId(id); setCorrectionReason(""); setOutcome(w.outcome); }}>Sayımı düzelt</button> : <><button type="button" onClick={() => void mark(id, "seen")}>Görüldü</button><button type="button" onClick={() => void mark(id, "not-seen")}>Görülmedi</button></>}</div> : null}{correctionId === id ? <div><label>Düzeltilmiş sayım<select aria-label="Düzeltilmiş sayım" value={outcome} onChange={e => setOutcome(e.target.value as "seen" | "not-seen")}><option value="seen">Görüldü</option><option value="not-seen">Görülmedi</option></select></label><Note label="Sayım düzeltme gerekçesi" value={correctionReason} onChange={setCorrectionReason} /><p>Düzeltme anının gerçek saati eklenir; önceki sayım korunur.</p><button type="button" disabled={!correctionReason.trim()} onClick={() => void mark(id, outcome, correctionReason).then(r => { if (r) setCorrectionId(""); })}>Gerekçeli sayımı kaydet</button><button type="button" onClick={() => setCorrectionId("")}>Düzeltmeden vazgeç</button></div> : null}</li>; })}</ul>{state.status === "active" ? <><button type="button" className="consent-primary" disabled={state.missing > 0} onClick={() => void save({ action: "complete", tripId: plan.id, expectedEventId: state.latestEventId })}>Bütün dönüşleri tamamla</button>{state.missing > 0 ? <p role="status">{state.missing} çocuk için dönüş görülmeden tamamlanamaz.</p> : null}</> : null}</> : null}
    <div className="consent-actions"><button type="button" onClick={() => void pdf(() => tripCountingPdfRecipe(snapshot, plan.id))}>Gezi çizelgesi PDF önizle</button></div>
    {state.status !== "cancelled" ? <details><summary>{state.status === "completed" ? "Tamamlanmış sayımı gerekçeyle yeniden aç" : "Geziyi gerekçeyle iptal et"}</summary><Note label="Gezi işlem gerekçesi" value={reason} onChange={setReason} /><button type="button" disabled={!reason.trim() || (state.status === "active" && state.missing > 0)} onClick={() => void save({ action: state.status === "completed" ? "reopen" : "cancel", tripId: plan.id, expectedEventId: state.latestEventId, reason })}>{state.status === "completed" ? "Sayımı yeniden aç" : "Geziyi iptal et"}</button>{state.status === "active" && state.missing > 0 ? <p>İptal kaydından önce bütün çocukların dönüş sayımını tamamlayın.</p> : null}</details> : null}
    <details><summary>Değişmez sayım geçmişi ({state.events.length})</summary><ol className="consent-history">{state.events.map(r => <li key={r.id}><strong>{r.workflow.kind === "trip-check" ? `${String(snapshot.students.find(s => s.id === r.studentId)?.displayName ?? "Çocuk")} · ${tripStageLabels[r.workflow.stage]} · ${r.workflow.outcome === "seen" ? "Görüldü" : "Görülmedi"}` : ({ "trip-plan": "Gezi planı", "trip-start": "Kadronun kilitlenmesi", "trip-complete": "Dönüşlerin tamamlanması", "trip-cancel": "İptal", "trip-reopen": "Sayım yeniden açıldı" } as Record<string, string>)[r.workflow.kind]}</strong><small>{consentDateLabel(r.civilDate)} · {consentClockLabel(r.createdAt)}</small>{r.workflow.kind === "trip-check" && r.workflow.correctionReason ? <p>{r.workflow.correctionReason}</p> : "reason" in r.workflow ? <p>{r.workflow.reason}</p> : null}</li>)}</ol></details>
  </article>;
}
