import {isCivilDate,civilDateInIstanbul} from "./attendance.ts";
import type {DataSnapshot,StoredRecord} from "./model.ts";

export const CLASS_DUTY_SETTING_TYPE="class-duty-schedule-v1" as const;
export type ClassDutyKind="fruit"|"child-of-week";
export interface ClassDutyConfig{kind:ClassDutyKind;startOn:string;endOn:string;weekdays:number[];studentIds:string[];capacity:number;avoidFruitWeek:boolean;seed:number;participation:string[]}
export interface ClassDutyRow{id:string;calendarEntryId:string;studentId:string;startOn:string;endOn:string;locked:boolean;status:"planned"|"completed"|"missed"|"cancelled"}
export interface ClassDutyWorkflow{kind:"schedule-revision";scheduleId:string;operationId:string;operationHash:string;revision:number;previousRevisionId:string|null;effectiveOn:string;config:ClassDutyConfig;rows:ClassDutyRow[]}
export type ClassDutyRecord=StoredRecord&{schemaVersion:1;deletedAt:null;settingType:typeof CLASS_DUTY_SETTING_TYPE;academicYearId:string;classroomId:string;studentId:null;workflow:ClassDutyWorkflow};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const uuid=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(v);
const utc=(v:unknown):v is string=>typeof v==="string"&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
const strings=(v:unknown,max:number,check:(v:unknown)=>boolean):v is string[]=>Array.isArray(v)&&v.length<=max&&new Set(v).size===v.length&&v.every(check);
export function isClassDutyConfig(v:unknown):v is ClassDutyConfig{return object(v)&&exact(v,["kind","startOn","endOn","weekdays","studentIds","capacity","avoidFruitWeek","seed","participation"])&&["fruit","child-of-week"].includes(String(v.kind))&&isCivilDate(v.startOn)&&isCivilDate(v.endOn)&&v.startOn<=v.endOn&&Array.isArray(v.weekdays)&&v.weekdays.length>0&&v.weekdays.length<=5&&new Set(v.weekdays).size===v.weekdays.length&&v.weekdays.every(d=>Number.isInteger(d)&&d>=1&&d<=5)&&strings(v.studentIds,200,uuid)&&Number.isInteger(v.capacity)&&Number(v.capacity)>=1&&Number(v.capacity)<=20&&typeof v.avoidFruitWeek==="boolean"&&Number.isSafeInteger(v.seed)&&Number(v.seed)>=0&&strings(v.participation,8,t=>typeof t==="string"&&t.length>0&&t.length<=200&&t===t.normalize("NFC").trim());}
export function isClassDutyRow(v:unknown):v is ClassDutyRow{return object(v)&&exact(v,["id","calendarEntryId","studentId","startOn","endOn","locked","status"])&&uuid(v.id)&&uuid(v.calendarEntryId)&&uuid(v.studentId)&&isCivilDate(v.startOn)&&isCivilDate(v.endOn)&&v.startOn<=v.endOn&&typeof v.locked==="boolean"&&["planned","completed","missed","cancelled"].includes(String(v.status));}
export function isClassDutyRecord(v:unknown):v is ClassDutyRecord{
  if(!object(v)||!exact(v,["id","createdAt","updatedAt","civilDate","schemaVersion","deletedAt","settingType","academicYearId","classroomId","studentId","workflow"])||!uuid(v.id)||!utc(v.createdAt)||v.updatedAt!==v.createdAt||!isCivilDate(v.civilDate)||v.civilDate>civilDateInIstanbul(new Date(v.createdAt))||v.schemaVersion!==1||v.deletedAt!==null||v.settingType!==CLASS_DUTY_SETTING_TYPE||!uuid(v.academicYearId)||!uuid(v.classroomId)||v.studentId!==null||!object(v.workflow))return false;
  const w=v.workflow;return exact(w,["kind","scheduleId","operationId","operationHash","revision","previousRevisionId","effectiveOn","config","rows"])&&w.kind==="schedule-revision"&&uuid(w.scheduleId)&&uuid(w.operationId)&&typeof w.operationHash==="string"&&/^[a-f0-9]{64}$/u.test(w.operationHash)&&Number.isSafeInteger(w.revision)&&Number(w.revision)>=1&&(w.previousRevisionId===null||uuid(w.previousRevisionId))&&isCivilDate(w.effectiveOn)&&isClassDutyConfig(w.config)&&Array.isArray(w.rows)&&w.rows.length<=4000&&w.rows.every(isClassDutyRow)&&new Set(w.rows.map(r=>r.id)).size===w.rows.length&&new Set(w.rows.map(r=>r.calendarEntryId)).size===w.rows.length;
}
export function classDutyRecords(data:DataSnapshot,scope?:{academicYearId:string;classroomId:string}){return data.settings.filter(isClassDutyRecord).filter(r=>!scope||(r.academicYearId===scope.academicYearId&&r.classroomId===scope.classroomId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));}
export function currentClassDutySchedules(data:DataSnapshot,scope?:{academicYearId:string;classroomId:string}){const latest=new Map<string,ClassDutyRecord>();for(const r of classDutyRecords(data,scope)){const old=latest.get(r.workflow.scheduleId);if(!old||old.workflow.revision<r.workflow.revision)latest.set(r.workflow.scheduleId,r);}return[...latest.values()];}
export function assertClassDutyRelationships(data:DataSnapshot){
  const raw=data.settings.filter(r=>r.settingType===CLASS_DUTY_SETTING_TYPE);if(!raw.every(isClassDutyRecord))throw new Error("Sınıf görev çizelgesi sözleşmesi geçersiz.");const records=raw as ClassDutyRecord[],byId=new Map(records.map(r=>[r.id,r]));
  for(const record of records){const w=record.workflow,year=data.academicYears.find(y=>y.id===record.academicYearId),classroom=data.classrooms.find(c=>c.id===record.classroomId&&c.academicYearId===record.academicYearId);if(!year||!classroom||w.config.startOn<String(year.startDate)||w.config.endOn>String(year.endDate))throw new Error("Görev çizelgesinin sınıf veya dönem kaynağı geçersiz.");
    const prior=w.previousRevisionId?byId.get(w.previousRevisionId):undefined;if(w.revision===1?(!!prior||w.previousRevisionId!==null):(!prior||prior.workflow.scheduleId!==w.scheduleId||prior.workflow.revision!==w.revision-1||prior.createdAt>=record.createdAt||prior.academicYearId!==record.academicYearId||prior.classroomId!==record.classroomId))throw new Error("Görev çizelgesinin revizyon zinciri geçersiz.");if(records.some(other=>other.id!==record.id&&other.workflow.scheduleId===w.scheduleId&&other.workflow.revision===w.revision))throw new Error("Çizelge revizyonu yinelenemez.");
    for(const id of new Set([...w.config.studentIds,...w.rows.map(r=>r.studentId)])){const student=data.students.find(s=>s.id===id);if(!student||(student.classroomId!==record.classroomId&&!(Array.isArray(student.enrollments)&&student.enrollments.some(e=>object(e)&&e.classroomId===record.classroomId&&e.academicYearId===record.academicYearId))))throw new Error("Görevdeki çocuğun sınıf kaydı bulunamadı.");}
    for(const row of w.rows)if(row.startOn<w.config.startOn||row.endOn>w.config.endOn||(row.status!=="planned"&&row.status!=="cancelled"&&row.startOn>record.civilDate))throw new Error("Görev satırının dönemi, çocuğu veya gerçekleşme tarihi geçersiz.");
    for(const row of w.rows.filter(r=>r.status!=="cancelled")){if(w.rows.filter(r=>r.startOn===row.startOn&&r.status!=="cancelled").length>w.config.capacity||w.rows.some(r=>r.id!==row.id&&r.studentId===row.studentId&&r.status!=="cancelled"&&r.startOn<=row.endOn&&r.endOn>=row.startOn))throw new Error("Görev kapasitesi veya aynı çocuğun zaman çakışması geçersiz.");}
    if(prior)for(const old of prior.workflow.rows){const next=w.rows.find(r=>r.id===old.id);if(old.startOn<record.civilDate||old.locked||old.status!=="planned"){if(!next||next.studentId!==old.studentId||next.startOn!==old.startOn||next.endOn!==old.endOn)throw new Error("Geçmiş, gerçekleşmiş veya sabit görev revizyonda taşınamaz.");}}
  }
  const used=new Set<string>();for(const record of currentClassDutySchedules(data)){for(const row of record.workflow.rows){const entry=data.calendarEntries.find(e=>e.id===row.calendarEntryId);const status=row.status==="planned"?"planned":row.status==="completed"?"completed":"cancelled";if(!entry||typeof entry.deletedAt==="string"||entry.classroomId!==record.classroomId||entry.academicYearId!==record.academicYearId||entry.startDate!==row.startOn||entry.endDate!==row.endOn||entry.status!==status||entry.entryType!==(record.workflow.config.kind==="fruit"?"fruit_day":"general_note")||used.has(entry.id))throw new Error("Görev satırının gerçek takvim bağlantısı geçersiz.");used.add(entry.id);}}
}
/** Privacy deletion rewrites only this child's historical slot/config references. */
export function eraseClassDutyStudent(data:DataSnapshot,studentId:string){const current=currentClassDutySchedules(data),calendarIds=new Set(classDutyRecords(data).flatMap(r=>r.workflow.rows.filter(row=>row.studentId===studentId).map(row=>row.calendarEntryId)).filter(id=>!current.some(r=>r.workflow.rows.some(row=>row.calendarEntryId===id&&row.studentId!==studentId))));return{records:classDutyRecords(data).map(record=>({...record,workflow:{...record.workflow,config:{...record.workflow.config,studentIds:record.workflow.config.studentIds.filter(id=>id!==studentId)},rows:record.workflow.rows.filter(row=>row.studentId!==studentId)}})),calendarIds};}
