import type {DataSnapshot,StoredRecord} from './model.ts';
import {sha256Hex} from '../backup/crypto.ts';
import {civilDateInIstanbul,isCivilDate} from './attendance.ts';
export const STUDENT_ERASURE_TYPE='student-erasure-v1';
const erasureId=(hash:string)=>`${hash.slice(0,8)}-${hash.slice(8,12)}-8${hash.slice(13,16)}-a${hash.slice(17,20)}-${hash.slice(20,32)}`;
export function isStudentErasure(value:unknown):value is StoredRecord&{settingType:typeof STUDENT_ERASURE_TYPE;erasedStudentHash:string}{if(!value||typeof value!=='object'||Array.isArray(value))return false;const row=value as Record<string,unknown>;const keys=['id','createdAt','updatedAt','civilDate','schemaVersion','deletedAt','settingType','erasedStudentHash'];return Object.keys(row).length===keys.length&&keys.every(k=>Object.hasOwn(row,k))&&row.settingType===STUDENT_ERASURE_TYPE&&typeof row.erasedStudentHash==='string'&&/^[0-9a-f]{64}$/.test(row.erasedStudentHash)&&row.id===erasureId(row.erasedStudentHash)&&row.schemaVersion===1&&row.deletedAt===null&&typeof row.createdAt==='string'&&Number.isFinite(Date.parse(row.createdAt))&&new Date(row.createdAt).toISOString()===row.createdAt&&row.updatedAt===row.createdAt&&isCivilDate(row.civilDate);}
export async function createStudentErasure(studentId:string,now=new Date()){const erasedStudentHash=await sha256Hex(studentId);return{id:erasureId(erasedStudentHash),createdAt:now.toISOString(),updatedAt:now.toISOString(),civilDate:civilDateInIstanbul(now),schemaVersion:1,deletedAt:null,settingType:STUDENT_ERASURE_TYPE,erasedStudentHash};}
export function studentErasureHashes(snapshot:DataSnapshot){return snapshot.settings.filter(isStudentErasure).map(row=>row.erasedStudentHash);}
export async function assertStudentErasureIntegrity(snapshot:DataSnapshot){const erased=new Set(studentErasureHashes(snapshot));if(!erased.size)return;for(const student of snapshot.students)if(erased.has(await sha256Hex(student.id)))throw new Error('Kalıcı silinmiş bir çocuğun eski cihaz kaydı geri getirilemez. Güncel yedeği kullanın.');}
