import {useEffect,useRef,useState} from 'react';
import {KeyboardInput} from '../../mobile';
import type {LocalDataStore} from '../../core/repository/contracts.ts';
import type {EncryptedBackupEnvelope} from '../../core/backup/encrypted-backup.ts';
import {canonicalJson} from '../../core/backup/canonical-json.ts';
import {cloudStateFromSnapshot,decryptCloudState,encryptCloudState,previewCloudMerge,resolveCloudMerge,restoreCloudState,applyCloudErasures,cloudBaseline,type CloudBaseline,type CloudState,type SyncPreview,type SyncChoices} from './cloud-sync.ts';
import {readAccountStatus,beginGoogleConnection,listCloudFiles,downloadCloudFile,uploadCloudFile,cloudHead,readCloudAnchor,saveCloudAnchor,disconnectGoogleAccount,disconnectCloudDrive,type AccountStatus,type CloudFile} from './cloud-gateway.ts';
import {cloudSessionStatus,startCloudSession,stopCloudSession} from './cloud-session.ts';
import './cloud-account.css';
interface Prepared{mode:'merge'|'restore'|'local-restore';headId:string|null;localFingerprint:string;local:CloudState;remote:CloudState|null;merge:SyncPreview|null;}
const collectionLabels:Record<string,string>={students:'Çocuk',settings:'Ayar veya belge',observations:'Gözlem',plans:'Plan',calendarEntries:'Takvim kaydı',attendanceRecords:'Yoklama',evidenceAssets:'Gözlem eki',activities:'Etkinlik',classrooms:'Sınıf',academicYears:'Eğitim yılı'};
function recordLabel(record:Record<string,unknown>|null){if(!record)return 'Bu cihazda kaldırılmış';return String(record.displayName??record.title??record.fullName??record.name??record.civilDate??'Kayıt');}
const fieldLabels:Record<string,string>={displayName:'Ad soyad',fullName:'Ad soyad',name:'Ad',title:'Başlık',rawText:'Gözlem metni',description:'Açıklama',teacherAssessmentText:'Öğretmenin değerlendirmesi',civilDate:'Olay günü',observedAt:'Gözlem zamanı',dateOfBirth:'Doğum tarihi',birthDate:'Doğum tarihi',schoolNumber:'Okul numarası',phone:'Telefon',phoneNumber:'Telefon',address:'Adres',email:'E-posta',relationship:'Yakınlık',materials:'Malzemeler',steps:'Oyun adımları',text:'Metin',note:'Not',notes:'Notlar',nextDayNote:'Ertesi gün notu',teacherDecision:'Öğretmen kararı',teacherReflection:'Öğretmen yansıtması',nextStep:'Sonraki adım',implementation:'Uygulama',adaptation:'Uyarlama',feedback:'Aile geri bildirimi',suggestion:'Aile önerisi',purpose:'Amaç',narrative:'Değerlendirme metni',reviewOn:'Kontrol günü',receivedOn:'Yanıt günü',periodStart:'Dönem başlangıcı',periodEnd:'Dönem sonu',startDate:'Başlangıç günü',endDate:'Bitiş günü',teacherName:'Öğretmen',schoolName:'Okul',meetingNotes:'Görüşme notları'};
function readableFields(record:Record<string,unknown>|null):Map<string,{label:string;value:string}>{
 const result=new Map<string,{label:string;value:string}>();
 const statuses:Record<string,string>={planned:'Planlandı','in-progress':'Devam ediyor',completed:'Tamamlandı',cancelled:'İptal edildi',draft:'Taslak',ready:'Hazır','teacher-saved':'Öğretmen kaydetti','teacher-reviewed':'Öğretmen inceledi',present:'Geldi',absent:'Gelmedi',late:'Geç geldi',excused:'İzinli',complete:'Tamamlandı','carried-forward':'Ertesi güne aktarıldı',open:'Açık',resolved:'Çözüldü',deferred:'Ertelendi'};
 function visit(value:unknown,path:string,label:string){
  if(value===null||typeof value==='string'||typeof value==='number'||typeof value==='boolean'){result.set(path,{label,value:value===null||value===''?'Boş':String(value)});return;}
  if(Array.isArray(value)){value.forEach((item,i)=>visit(item,`${path}.${i}`,`${label} ${i+1}`));return;}
  if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){
   if(['status','closureStatus'].includes(key)&&typeof item==='string'&&statuses[item])visit(statuses[item],`${path}.${key}`,'Kayıt durumu');
   else if(key==='deletedAt')visit(item?'Kaldırılmış kayıt':'Etkin kayıt',`${path}.${key}`,'Kayıt durumu');
   else if(fieldLabels[key])visit(item,`${path}.${key}`,label?`${label} · ${fieldLabels[key]}`:fieldLabels[key]);
   else if(['workflow','contacts','familyContacts','children','program','teacher','teacherOwnedDailyFlow','blocks'].includes(key))visit(item,`${path}.${key}`,label);
  }
 }
 if(record)visit(record,'','');return result;
}
function ConflictValues({local,remote,side}:{local:Record<string,unknown>|null;remote:Record<string,unknown>|null;side:'local'|'remote'}){
 const left=readableFields(local),right=readableFields(remote),selected=side==='local'?left:right;
 const paths=[...new Set([...left.keys(),...right.keys()])].filter(path=>left.get(path)?.value!==right.get(path)?.value);
 if(!(side==='local'?local:remote))return <p>Bu tarafta kayıt bulunmuyor.</p>;
 return paths.length?<dl style={{margin:'8px 0',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{paths.map(path=><div key={path}><dt><strong>{(left.get(path)??right.get(path))!.label}</strong></dt><dd style={{margin:'2px 0 12px'}}>{selected.get(path)?.value??'Bu alanda kayıt yok'}</dd></div>)}</dl>:<p>Görünen metin alanları aynı; kaydın bağlantısı veya kayıt durumu değişmiş.</p>;
}
function downloadLocal(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export interface CloudAccountPanelProps{store:LocalDataStore;version:string;disabled?:boolean;canWrite?:()=>boolean;onChanged?:()=>void;}
export function CloudAccountPanel({store,version,disabled=false,canWrite,onChanged}:CloudAccountPanelProps){
 const [status,setStatus]=useState<AccountStatus|null>(null),[password,setPassword]=useState(''),[savedKey,setSavedKey]=useState(false),[showKey,setShowKey]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[files,setFiles]=useState<CloudFile[]>([]),[selectedFile,setSelectedFile]=useState(''),[prepared,setPrepared]=useState<Prepared|null>(null),[choices,setChoices]=useState<SyncChoices>({}),[session,setSession]=useState(()=>cloudSessionStatus(store));
 const guard=useRef(false),disabledRef=useRef(disabled),alive=useRef(true),commit=useRef<{key:string;envelope:EncryptedBackupEnvelope;requestId:string}|null>(null);disabledRef.current=disabled;
 useEffect(()=>{alive.current=true;void readAccountStatus().then(value=>{if(alive.current)setStatus(value);}).catch(e=>{if(alive.current)setError(e.message);});const listener=()=>setSession(cloudSessionStatus(store));window.addEventListener('maarifos-cloud-session',listener);return()=>{alive.current=false;window.removeEventListener('maarifos-cloud-session',listener);};},[store]);
 async function run(task:()=>Promise<void>){if(guard.current||disabledRef.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{await task();}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı. Yeniden deneyin.');}finally{guard.current=false;if(alive.current)setBusy(false);}}
 const keyReady=password.length>=20&&savedKey,connected=status?.status==='connected',drive=connected&&status.driveConnected,locked=busy||disabled;
 function changeKey(value:string){stopCloudSession(store);setPassword(value);setSavedKey(false);setPrepared(null);commit.current=null;}
 async function prepare(mode:'merge'|'restore'){
  if(!keyReady||!connected||!drive)return;stopCloudSession(store);
  const currentStatus=await readAccountStatus();if(currentStatus.status!=='connected'||currentStatus.user.subject!==status.user.subject)throw new Error('Google hesabı değişti. Bağlantıyı denetleyip yeniden deneyin.');
  const latest=await cloudHead(),local=await cloudStateFromSnapshot(await store.readSnapshot(),version);let remote:CloudState|null=null,base:CloudBaseline|null=null;
  const latestState=latest?await decryptCloudState(await downloadCloudFile(latest.id),password,version):null;
  if(mode==='restore'){if(!selectedFile)throw new Error('Önce geri getirilecek yedeği seçin.');const chosen=selectedFile===latest?.id?latestState:await decryptCloudState(await downloadCloudFile(selectedFile),password,version);if(!chosen)throw new Error('Seçili yedek bulunamadı.');remote=await applyCloudErasures(chosen.backup.payload,[...chosen.erasedStudentHashes,...local.erasedStudentHashes,...(latestState?.erasedStudentHashes??[])],version);}
  else{remote=latestState;const anchor=await readCloudAnchor(status.user.subject);if(anchor)base=anchor.baseline;}
  if(disabledRef.current)throw new Error('Cihaz kilitlendi. Kilidi açıp farkları yeniden hazırlayın.');
  setPrepared({mode,headId:latest?.id??null,localFingerprint:canonicalJson(local.backup.payload),local,remote,merge:mode==='merge'&&remote?await previewCloudMerge(base,local,remote):null});setChoices({});commit.current=null;
 }
 async function apply(){
  if(!prepared||!keyReady)return;
  const state=prepared.mode!=='merge'?prepared.remote!:prepared.merge?await resolveCloudMerge(prepared.merge,choices,version):prepared.local;
  if(canonicalJson(await store.readSnapshot())!==prepared.localFingerprint)throw new Error('Bu cihazda yeni kayıt var. Son yedekle karşılaştır düğmesiyle seçimleri yenileyin.');
  if(disabledRef.current||canWrite?.()===false)throw new Error('Yazma kapalı. Kilidi açıp yeniden deneyin.');
  if(prepared.mode==='local-restore'){await restoreCloudState(store,state,prepared.localFingerprint,version);setPrepared(null);setMessage('Şifreli dosya doğrulandı ve bu cihaza geri getirildi.');onChanged?.();return;}
  if(!connected)throw new Error('Google hesabını yeniden bağlayın.');
  const key=canonicalJson({payload:state.backup.payload,hashes:state.erasedStudentHashes,head:prepared.headId});
  if(commit.current?.key!==key)commit.current={key,envelope:await encryptCloudState(state,password),requestId:crypto.randomUUID()};
  const pending=commit.current;
  // Upload is idempotent and rejects a changed cloud head. Local replace separately guards its exact preimage.
  const file=await uploadCloudFile(pending.envelope,prepared.headId,status.user.subject,pending.requestId);
  if(canonicalJson(state.backup.payload)!==prepared.localFingerprint){try{await restoreCloudState(store,state,prepared.localFingerprint,version);}catch(e){throw new Error(`Şifreli yedek Drive'a kaydedildi; bu cihaz değiştirilemedi. Son yedekle yeniden karşılaştırın. ${e instanceof Error?e.message:''}`);}}
  await saveCloudAnchor({subject:status.user.subject,headId:file.id,baseline:await cloudBaseline(state)});setPrepared(null);commit.current=null;setMessage('Kayıtlar doğrulandı. Bu cihaz ve şifreli Drive yedeği aynı içerikte.');onChanged?.();
 }
 const localCount=prepared?.local.backup.payload.students.filter(s=>!s.deletedAt).length??0,remoteCount=prepared?.remote?.backup.payload.students.filter(s=>!s.deletedAt).length??0;
 return <section className="cloud-account" aria-label="Google hesabı ve şifreli yedek"><h3>Hesap ve cihazlarım</h3><p>Google hesabıyla giriş yapın; sınıf yedeğini ayrıca Google Drive’a bağlayın. Sınıf içeriği bu cihazda şifrelenir.</p>
 <div className="cloud-account-actions">{!connected?<button type="button" disabled={locked||!status?.available} onClick={()=>void run(async()=>beginGoogleConnection('login'))}>Google ile giriş yap</button>:<><p><strong>{status.user.displayName}</strong> · Google hesabı bağlı</p>{!drive&&<button type="button" disabled={locked} onClick={()=>void run(async()=>beginGoogleConnection('backup'))}>Şifreli Drive yedeğini bağla</button>}<button type="button" disabled={locked} onClick={()=>void run(async()=>{stopCloudSession(store);await disconnectGoogleAccount();setStatus(await readAccountStatus());setPassword('');setSavedKey(false);setPrepared(null);setMessage('Bu cihazdaki Google oturumu kapatıldı. Sınıf kayıtları bu cihazda duruyor.');})}>Hesaptan çık</button></>}</div>
 {(!status?.available)&&<details className="cloud-account-setup"><summary>Google bağlantısını etkinleştirme</summary><p>Bu adreste Google hesap sunucusu henüz etkin değil. Uygulama yöneticisi Google Cloud projesindeki web istemcisini, dönüş adresini ve sunucu anahtarını kurmalıdır.</p><p>Kurulum hazır olunca Bağlantıyı denetle düğmesi giriş seçeneğini açar. Bu sırada aşağıdan şifreli dosya yedeği alabilirsiniz.</p></details>}
 <button type="button" disabled={locked} onClick={()=>void run(async()=>{setStatus(await readAccountStatus());setMessage('Hesap bağlantısı denetlendi.');})}>Bağlantıyı denetle</button>
 <details open={drive||undefined}><summary>Yedek anahtarım</summary><p>İlk cihazda anahtar oluşturun. Başka cihazda aynı anahtarı girin. Anahtar sunucuya gönderilmez; uygulama kapanınca bellekten çıkar.</p><div className="cloud-account-actions"><button type="button" disabled={locked||!!prepared} onClick={()=>{const bytes=crypto.getRandomValues(new Uint8Array(24));changeKey(Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join(''));setShowKey(true);}}>Yeni anahtar oluştur</button><button type="button" disabled={locked||password.length<20} onClick={()=>{downloadLocal(`MaarifOS şifreli yedek anahtarı\n${password}\n\nBu dosyayı özel ve güvenli bir yerde saklayın.\n`,'MaarifOS-yedek-anahtari.txt','text/plain;charset=utf-8');setMessage('Anahtar dosyası hazırlandı. Güvenli yere kaydettiğinizde aşağıdaki kutuyu seçin.');}}>Anahtarı dosya olarak indir</button></div><label>Yedek anahtarı<KeyboardInput type={showKey?'text':'password'} autoComplete="off" spellCheck={false} value={password} disabled={locked||!!prepared} onChange={e=>changeKey(e.target.value.trim())}/></label><label className="cloud-account-check"><input type="checkbox" checked={showKey} onChange={e=>setShowKey(e.target.checked)}/>Anahtarı göster</label><label className="cloud-account-check"><input type="checkbox" checked={savedKey} disabled={locked||password.length<20} onChange={e=>setSavedKey(e.target.checked)}/>Bu anahtarı güvenli yerde sakladım veya mevcut anahtarımı girdim.</label><button type="button" disabled={locked||!keyReady} onClick={()=>void run(async()=>{const state=await cloudStateFromSnapshot(await store.readSnapshot(),version);downloadLocal(canonicalJson(await encryptCloudState(state,password)),`MaarifOS-sifreli-yedek-${state.backup.manifest.createdAt.slice(0,10)}.json`,'application/json');setMessage('Şifreli sınıf yedeği indirildi.');})}>Şifreli dosya yedeği indir</button></details>
 <label>Şifreli dosya yedeğini bu cihaza getir<KeyboardInput type="file" accept="application/json,.json" disabled={locked||!keyReady} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void run(async()=>{stopCloudSession(store);if(file.size>96*1024*1024)throw new Error('Yedek 96 MiB sınırını aşıyor.');const remote=await decryptCloudState(await file.text(),password,version),local=await cloudStateFromSnapshot(await store.readSnapshot(),version);setPrepared({mode:'local-restore',headId:null,localFingerprint:canonicalJson(local.backup.payload),local,remote:await applyCloudErasures(remote.backup.payload,[...remote.erasedStudentHashes,...local.erasedStudentHashes],version),merge:null});});}}/></label>
 {drive&&<><div className="cloud-account-actions"><button type="button" disabled={locked||!keyReady} onClick={()=>void run(()=>prepare('merge'))}>Son yedekle karşılaştır</button><button type="button" disabled={locked} onClick={()=>void run(async()=>{const result=await listCloudFiles();setFiles(result.files);setSelectedFile(result.head?.id??result.files[0]?.id??'');setMessage(`${result.files.length} şifreli yedek bulundu.`);})}>Kayıtlı yedekleri göster</button></div>{files.length>0&&<><label>Geri getirilecek yedek<select value={selectedFile} disabled={locked} onChange={e=>{setSelectedFile(e.target.value);setPrepared(null);}}>{files.map(file=><option key={file.id} value={file.id}>{new Date(file.createdAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})} · {Math.ceil(file.bytes/1024)} KB</option>)}</select></label><button type="button" disabled={locked||!keyReady||!selectedFile} onClick={()=>void run(()=>prepare('restore'))}>Seçili yedeğin içeriğini getir</button></>}
 <label className="cloud-account-check"><input type="checkbox" checked={session.active} disabled={locked||!keyReady||!!prepared} onChange={e=>{if(e.target.checked)startCloudSession({store,subject:status.user.subject,password,version,canWrite:()=>!disabledRef.current&&canWrite?.()!==false});else stopCloudSession(store);}}/>Bu oturumda otomatik şifreli yedekle</label>{session.message&&<p role="status">{session.message}</p>}<details><summary>Drive bağlantısı</summary><button type="button" disabled={locked} onClick={()=>void run(async()=>{stopCloudSession(store);await disconnectCloudDrive();setStatus(await readAccountStatus());setPrepared(null);setMessage('Drive yetkisi kaldırıldı. Var olan yedek dosyaları Drive’da duruyor.');})}>Drive yedek yetkisini kaldır</button></details></>}
 {prepared&&<section className="cloud-account-preview" aria-label="Cihaz farkları"><h4>{prepared.mode!=='merge'?'Yedeği bu cihaza getir':'Eşitlemeyi tamamla'}</h4><p>Bu cihaz: {localCount} çocuk · {prepared.remote?`Yedek: ${remoteCount} çocuk`:'İlk Drive yedeği hazırlanacak.'}</p>{prepared.mode!=='merge'&&<p>Seçtiğiniz yedek bu cihazdaki mevcut kayıtların yerine geçer. Önce otomatik kurtarma noktası alınır. Kalıcı silmeler korunur.</p>}<p>{prepared.merge?.conflicts.length??0} kayıt için seçim · {prepared.merge?.erasedStudentIds.length??0} kalıcı silme uygulanacak</p>{prepared.merge?.conflicts.map(conflict=><fieldset key={conflict.key}><legend>{collectionLabels[conflict.collection]??'Kayıt'} · {recordLabel(conflict.local??conflict.remote)}</legend>{(['local','remote'] as const).map(side=><div key={side}><label className="cloud-account-check"><input type="radio" name={conflict.key} checked={choices[conflict.key]===side} disabled={locked} onChange={()=>{setChoices(c=>({...c,[conflict.key]:side}));commit.current=null;}}/>{side==='local'?'Bu cihaz':'Diğer cihaz'} · {recordLabel(conflict[side])} · {conflict[side]?.updatedAt?new Date(String(conflict[side]?.updatedAt)).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}):'Kaldırılmış'}</label><ConflictValues local={conflict.local} remote={conflict.remote} side={side}/></div>)}</fieldset>)}<div className="cloud-account-actions"><button type="button" disabled={locked||!!prepared.merge?.conflicts.some(c=>!choices[c.key])} onClick={()=>void run(apply)}>{prepared.mode!=='merge'?'Yedeği bu cihaza uygula':'Seçimlerimle eşitle ve yedekle'}</button><button type="button" disabled={locked} onClick={()=>{setPrepared(null);commit.current=null;}}>Seçimi kapat</button></div></section>}
 {busy&&<p role="status">Şifreleme ve kayıt denetimi sürüyor…</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
