import {test,expect,type Page} from "@playwright/test";
import {mkdir,readFile} from "node:fs/promises";
const production = process.env.CLASSROOM_ADMIN_PRODUCTION === "1";
const output=`output/new-workflows-2026-09-08/classroom-admin/${production ? "production" : "development"}`;
test.use({viewport:{width:390,height:844},actionTimeout:12000});
test.describe.configure({timeout:120000});
const runtimeProblems = new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const problems:string[]=[];runtimeProblems.set(page,problems);page.on("pageerror",error=>problems.push(error.name));if(production)page.on("request",request=>{if(new URL(request.url()).pathname.startsWith("/src/"))problems.push("Production source import");});});
test.afterEach(async({page})=>{expect(runtimeProblems.get(page)??[]).toEqual([]);});
async function setup(page:Page){
 await mkdir(output,{recursive:true});await page.clock.install({time:new Date("2026-09-14T09:00:00.000Z")});await page.goto("/classroom?native=1");
 const dialog=page.getByRole("dialog",{name:"Sınıfını hazırla",exact:true});await dialog.getByLabel("Okul adı").fill("Kurgu Anaokulu");await dialog.getByLabel("Öğretmen adı soyadı").fill("Kurgu Öğretmen");await dialog.getByLabel("Sınıf adı").fill("Kurgu Defter Sınıfı");await dialog.getByLabel("Maarif Modeli yaş grubu",{exact:true}).selectOption({label:"60–72 ay"});await dialog.getByRole("button",{name:"Sınıfımı hazırla",exact:true}).click();await expect(dialog).toBeHidden();
 await page.getByRole("button",{name:"Çocuk ekle",exact:true}).click();const add=page.getByRole("dialog",{name:"Çocuk ekle",exact:true});await add.getByLabel("Çocuğun adı",{exact:true}).fill("Kurgu Emanet Çocuğu");await add.getByRole("button",{name:"Kaydet ve kapat",exact:true}).click();await expect(add).toBeHidden();
 if(production){await expect.poll(()=>page.evaluate(()=>(window as any).__maarifosPwaStatus?.offlineReady??false),{timeout:90000}).toBe(true);await page.context().setOffline(true);await page.reload();await expect(page.getByRole("main",{name:"Sınıfım",exact:true})).toBeVisible();}
}
async function open(page:Page,section="inventory"){
 await page.getByRole("region",{name:"Sınıf yönetimi işleri",exact:true}).getByRole("button").first().click();const dialog=page.getByRole("dialog",{name:"Sınıf yönetimi",exact:true});await dialog.getByLabel("Sınıf yönetimi alanı").selectOption(section);return dialog;
}
// Physical append count works against production ciphertext without importing development sources.
async function records(page:Page){return page.evaluate(()=>new Promise<string[]>((resolve,reject)=>{const request=indexedDB.open("maarifos-local");request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result;const transaction=database.transaction("settings","readonly");const rows=transaction.objectStore("settings").getAllKeys();rows.onerror=()=>reject(rows.error);transaction.oncomplete=()=>{database.close();resolve(rows.result.map(String));};transaction.onabort=()=>{database.close();reject(transaction.error);};};}))}
async function clickSave(page:Page,dialog:ReturnType<Page["getByRole"]>,name:string){const count=(await records(page)).length;await dialog.getByRole("button",{name,exact:true}).click();await expect.poll(async()=>(await records(page)).length).toBe(count+1)}
async function pdf(page:Page,dialog:ReturnType<Page["getByRole"]>,button:string,file:string){await dialog.getByRole("button",{name:button,exact:true}).click();const preview=page.getByRole("dialog",{name:"PDF önizlemesi",exact:true});await expect(preview.locator("canvas[data-pdf-rendered=true]").first()).toBeVisible({timeout:30000});const event=page.waitForEvent("download");await preview.getByRole("button",{name:"Bu PDF'yi indir",exact:true}).click();await(await event).saveAs(`${output}/${file}.pdf`);expect((await readFile(`${output}/${file}.pdf`)).byteLength).toBeGreaterThan(10000);await page.screenshot({path:`${output}/${file}-preview.png`});await preview.getByRole("button",{name:"PDF önizlemesini kapat",exact:true}).click();await expect(preview).toBeHidden();}
async function material(page:Page){const d=await open(page);await d.getByText("Yeni malzeme ekle",{exact:true}).click();await d.getByLabel("Malzeme adı",{exact:true}).fill("Kurgu Hikâye Kitabı");await d.getByLabel("Başlangıç miktarı",{exact:true}).fill("10");await clickSave(page,d,"Malzemeyi kaydet");await d.getByRole("combobox",{name:"Malzeme seç",exact:true}).selectOption({label:"Kurgu Hikâye Kitabı · 10 adet kullanılabilir"});return d;}
test("MR100 320px gerçek IDB stok, kısmi iade, negatif stok engeli ve yeniden açma",async({page})=>{
 await page.setViewportSize({width:320,height:844});await setup(page);let d=await material(page);
 await d.getByLabel("Miktar (adet)",{exact:true}).fill("4");await d.getByRole("combobox",{name:"Emanet alan",exact:true}).selectOption({label:"Kurgu Emanet Çocuğu"});await d.getByLabel("Beklenen iade tarihi",{exact:true}).fill("2026-09-15");await clickSave(page,d,"Hareketi kaydet");
 await expect(d.locator(".admin-stock-grid")).toContainText("4Emanet");await d.getByRole("button",{name:"İade hazırla",exact:true}).click();await d.getByLabel("Miktar (adet)",{exact:true}).fill("2");await clickSave(page,d,"Hareketi kaydet");
 await d.getByRole("combobox",{name:"İşlem",exact:true}).selectOption("consume");await d.getByLabel("Miktar (adet)",{exact:true}).fill("9");const count=(await records(page)).length;await d.getByRole("button",{name:"Hareketi kaydet",exact:true}).click();await expect(d.getByRole("alert")).toContainText("stok");expect((await records(page)).length).toBe(count);
 expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:`${output}/inventory-320.png`});await page.reload();d=await open(page);await d.getByRole("combobox",{name:"Malzeme seç",exact:true}).selectOption({label:"Kurgu Hikâye Kitabı · 8 adet kullanılabilir"});await expect(d.locator(".admin-stock-grid")).toContainText("2Emanet");
 await pdf(page,d,"Malzeme defteri · PDF","inventory-mobile");
});
test("MR101 gerçek devir listesi kontrol, kapanış, geçmiş ve yeniden açma",async({page})=>{
 await setup(page);const d=await open(page,"handover");await d.getByText("Devir listesi oluştur",{exact:true}).click();await d.getByLabel("Teslim alacak kişi / görev",{exact:true}).fill("Kurgu Yeni Öğretmen");await clickSave(page,d,"Devir listesini kaydet");await d.getByRole("combobox",{name:"Devir listesi",exact:true}).selectOption({label:"Dönem sonu sınıf devri · açık"});await expect(d.getByRole("button",{name:"Devir kaydını tamamla",exact:true})).toBeDisabled();
 const checks=d.locator(".admin-check input");for(let i=0;i<await checks.count();i++){const n=(await records(page)).length;await checks.nth(i).click();await expect.poll(async()=>(await records(page)).length).toBe(n+1);await expect(checks.nth(i)).toBeChecked()}await clickSave(page,d,"Devir kaydını tamamla");await expect(d.getByText("Devir kaydı 2026-09-14 tarihinde tamamlandı.",{exact:true})).toBeVisible();await expect(checks.first()).toBeDisabled();await pdf(page,d,"Devir tutanağı · PDF","handover-mobile");await d.getByRole("textbox",{name:"Yeniden açma gerekçesi",exact:true}).fill("Kurgu dosya yeniden kontrol edilecek");await clickSave(page,d,"Gerekçeyle yeniden aç");await expect(checks.first()).toBeEnabled();expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:`${output}/handover-390.png`});
});
test("MR100/101 gerçek PDF önizlemesi, indirme ve uzun tablo sayfalama",async({page})=>{
 test.skip(production,"Uzun tablo kaynak fixture'ı geliştirme ortamına aittir; üretimde iki gerçek UI akışı PDF'yi çevrimdışı indirir.");
 await setup(page);await material(page);await page.evaluate(async()=>{const {IndexedDbDataStore}=await import("/src/core/index.ts");const {appendClassroomAdmin}=await import("/src/features/classroom-admin/classroom-admin-service.ts");const {adminLedgerHead,classroomAdminRecords}=await import("/src/core/domain/classroom-admin.ts");const store=new IndexedDbDataStore();try{for(let i=0;i<35;i++){const s=await store.readSnapshot();await appendClassroomAdmin(store,{expectedScope:{academicYearId:s.classrooms[0].academicYearId,classroomId:s.classrooms[0].id},expectedHead:adminLedgerHead(classroomAdminRecords(s)),workflow:{kind:"inventory-item",name:`Kurgu Uzun Malzeme Adı Çok Parçalı Eğitim Seti ${i+1}`,category:"Duyusal Oyun ve Sanat Materyalleri",unit:"set",initialQuantity:i+1,note:""}})}}finally{store.close()}});
 await page.reload();const d=await open(page);await pdf(page,d,"Malzeme defteri · PDF","inventory-long");
 await d.getByLabel("Sınıf yönetimi alanı").selectOption("handover");await d.getByText("Devir listesi oluştur",{exact:true}).click();await d.getByLabel("Teslim alacak kişi / görev",{exact:true}).fill("Kurgu Yeni Öğretmen");await d.getByRole("textbox",{name:"Ek kontrol maddeleri · her satıra bir madde",exact:true}).fill(Array.from({length:36},(_,i)=>`Kurgu Devir Maddesi ${String(i+1).padStart(2,"0")} · Uzun başlıklı eğitim materyalleri, sınıf dosyaları ve takip çizelgelerinin eksiksiz teslim kontrolü`).join("\n"));await clickSave(page,d,"Devir listesini kaydet");await d.getByRole("combobox",{name:"Devir listesi",exact:true}).selectOption({label:"Dönem sonu sınıf devri · açık"});await pdf(page,d,"Devir tutanağı · PDF","handover-long");
});
