import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
test.use({viewport:{width:320,height:844}});
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-09-12T09:00:00Z'));});
test('conflicting observation shows full changed values without technical identifiers and applies the chosen content',async({page})=>{
 const password='Kurgu-anahtar-12345678901234567890';let remoteEnvelope:unknown;
 await page.route('**/api/account/status',route=>route.fulfill({json:{available:true,status:'connected',user:{subject:'fixture-account',displayName:'Kurgu Öğretmen'},driveConnected:true}}));
 await page.route('**/api/account/head',route=>route.fulfill({json:{head:{id:'fixture_old_head',digest:'test',bytes:100,createdAt:'2026-09-12T09:00:00Z'}}}));
 await page.route('**/api/account/backups/fixture_old_head',route=>route.fulfill({json:remoteEnvelope}));
 await page.route('**/api/account/backups',route=>route.fulfill({status:201,json:{id:'fixture_new_head',digest:'test',bytes:100,createdAt:'2026-09-12T09:00:00Z'}}));
 await page.goto('/tests/cloud-account-fixture.html');await page.waitForFunction(()=>!!(window as any).cloudTest);
 const values=await page.evaluate(async(password)=>{
  const store=(window as any).cloudTest.store,snapshot=await store.readSnapshot();const {cloudStateFromSnapshot,cloudBaseline,encryptCloudState}=await import('/src/features/cloud-account/cloud-sync.ts');const {saveCloudAnchor}=await import('/src/features/cloud-account/cloud-gateway.ts');
  await saveCloudAnchor({subject:'fixture-account',headId:'fixture_base_head',baseline:await cloudBaseline(await cloudStateFromSnapshot(snapshot,'0.44.0'))});
  const localText='Bu cihazda: çocuk iki parçayı sırayla yerleştirdi. '+ 'Öğretmenin tam gözlem metni korunur. '.repeat(12),remoteText='Diğer cihazda: çocuk üç parçayı arkadaşına gösterdi. '+ 'Kaynak cümlesi kesilmeden görünür. '.repeat(12);
  const observation=snapshot.observations[0];await store.transaction('readwrite',['observations'],tx=>tx.putMany('observations',[{...observation,rawText:localText}]));snapshot.observations[0]={...observation,rawText:remoteText};return {localText,remoteText,id:observation.id,envelope:await encryptCloudState(await cloudStateFromSnapshot(snapshot,'0.44.0'),password)};
 },password);remoteEnvelope=values.envelope;
 await page.getByLabel('Yedek anahtarı',{exact:true}).fill(password);await page.getByRole('checkbox',{name:'Bu anahtarı güvenli yerde sakladım veya mevcut anahtarımı girdim.'}).check();await page.getByRole('button',{name:'Son yedekle karşılaştır',exact:true}).click();
 const preview=page.getByRole('region',{name:'Cihaz farkları'});await expect(preview.getByText(values.localText,{exact:true})).toBeVisible();await expect(preview.getByText(values.remoteText,{exact:true})).toBeVisible();await expect(preview.getByText('Gözlem metni',{exact:true})).toHaveCount(2);expect(await preview.innerText()).not.toContain(values.id);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await preview.getByRole('radio',{name:/Diğer cihaz/}).check();await preview.getByRole('button',{name:'Seçimlerimle eşitle ve yedekle',exact:true}).click();await expect(page.getByLabel('Kaydedilen eşitleme')).toHaveText('1');expect(await page.evaluate(async(id)=>(await (window as any).cloudTest.store.readSnapshot()).observations.find(o=>o.id===id).rawText,values.id)).toBe(values.remoteText);expect(await page.evaluate(()=>(window as any).cloudTest.lastChange)).toEqual({localChanged:true});
});
test('unconfigured account clearly stays local; encrypted file restores through the real IndexedDB service',async({page})=>{
 await page.route('**/api/account/status',route=>route.fulfill({json:{available:false,status:'not_configured'}}));await page.goto('/tests/cloud-account-fixture.html');
 await expect(page.getByRole('button',{name:'Google ile giriş yap',exact:true})).toBeDisabled();await page.getByText('Yedek anahtarım',{exact:true}).click();await page.getByRole('button',{name:'Yeni anahtar oluştur',exact:true}).click();await expect(page.getByLabel('Yedek anahtarı',{exact:true})).toHaveValue(/^[a-f0-9]{48}$/);await page.getByRole('checkbox',{name:'Bu anahtarı güvenli yerde sakladım veya mevcut anahtarımı girdim.'}).check();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Şifreli dosya yedeği indir',exact:true}).click();const file=await download,path=await file.path();expect(path).toBeTruthy();
 await page.evaluate(async()=>{const store=(window as any).cloudTest.store,s=await store.readSnapshot();await store.transaction('readwrite',['students'],tx=>tx.putMany('students',[{...s.students[1],displayName:'Yerel geçici değişiklik'}]));});
 await page.getByLabel('Şifreli dosya yedeğini bu cihaza getir',{exact:true}).setInputFiles(path!);await expect(page.getByRole('button',{name:'Yedeği bu cihaza uygula',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Yedeği bu cihaza uygula',exact:true}).click();await expect(page.getByLabel('Kaydedilen eşitleme')).toHaveText('1');
 expect(await page.evaluate(async()=>(await (window as any).cloudTest.store.readSnapshot()).students[1].displayName)).toBe('Kurgu Çocuk 2');expect(await page.evaluate(()=>(window as any).cloudTest.lastChange)).toEqual({localChanged:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('output/cumulative-2026-09-12',{recursive:true});await page.screenshot({path:'output/cumulative-2026-09-12/cloud-local-320.png',fullPage:true});
});
test('first Drive backup binds expected account and stores only hashes; changed account yields an actionable retry',async({page})=>{
 let uploads=0;await page.route('**/api/account/status',route=>route.fulfill({json:{available:true,status:'connected',user:{subject:'fixture-account',displayName:'Kurgu Öğretmen'},driveConnected:true}}));await page.route('**/api/account/head',route=>route.fulfill({json:{head:null}}));await page.route('**/api/account/backups',async route=>{const body=route.request().postDataJSON();expect(body.expectedSubject).toBe('fixture-account');expect(body.expectedHead).toBe(null);expect(JSON.stringify(body)).not.toContain('Kurgu Çocuk');uploads++;await route.fulfill({status:uploads===1?201:409,json:uploads===1?{id:'fixture_cloud_head',digest:'test',bytes:100,createdAt:'2026-09-12T09:00:00Z'}:{error:'Google hesabı değişti. Bağlantıyı denetleyip yeniden karşılaştırın.'}});});
 await page.goto('/tests/cloud-account-fixture.html');await page.getByLabel('Yedek anahtarı',{exact:true}).fill('Kurgu-anahtar-12345678901234567890');await page.getByRole('checkbox',{name:'Bu anahtarı güvenli yerde sakladım veya mevcut anahtarımı girdim.'}).check();await page.getByRole('button',{name:'Son yedekle karşılaştır',exact:true}).click();await page.getByRole('button',{name:'Seçimlerimle eşitle ve yedekle',exact:true}).click();await expect(page.getByLabel('Kaydedilen eşitleme')).toHaveText('1');
 expect(await page.evaluate(async()=>{const {readCloudAnchor}=await import('/src/features/cloud-account/cloud-gateway.ts');const anchor=await readCloudAnchor('fixture-account');return anchor?.headId==='fixture_cloud_head'&&!JSON.stringify(anchor).includes('ciphertext')&&!JSON.stringify(anchor).includes('Kurgu');})).toBe(true);
 await page.getByRole('button',{name:'Son yedekle karşılaştır',exact:true}).click();await page.getByRole('button',{name:'Seçimlerimle eşitle ve yedekle',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('Google hesabı değişti. Bağlantıyı denetleyip yeniden karşılaştırın.');await expect(page.getByLabel('Kaydedilen eşitleme')).toHaveText('1');expect(uploads).toBe(2);expect(await page.evaluate(()=>(window as any).cloudTest.lastChange)).toEqual({localChanged:false});
});
