import {expect,test} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {setup} from './helpers/development-workspace-ui';
test.use({viewport:{width:390,height:844}});
test('actual app connects class duties, purpose reports, family tools, calendar and account without runtime errors',async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.name));await page.route('**/api/account/status',route=>route.fulfill({json:{available:false,status:'not_configured'}}));await setup(page);
 await page.getByRole('button',{name:/^Meyve günü ve haftanın çocuğu/}).click();const duties=page.getByRole('dialog',{name:'Sınıf görev çizelgeleri',exact:true});await expect(duties.getByRole('button',{name:'Meyve günü',exact:true})).toBeVisible();expect(await duties.evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);await page.keyboard.press('Escape');await expect(duties).toBeHidden();
 await page.getByRole('button',{name:'Bugün',exact:true}).click();await expect(page.getByRole('button',{name:'Hızlı gözlem',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Çocuk ekle',exact:true})).toHaveCount(0);await mkdir('output/cumulative-2026-09-12',{recursive:true});await page.screenshot({path:'output/cumulative-2026-09-12/home390.png'});
 await page.getByRole('button',{name:'Belgeler',exact:true}).click();await page.getByRole('button',{name:/İdareye sun/}).click();const reports=page.getByRole('region',{name:'İdare ve öğretmen dosyası',exact:true});await expect(reports.getByRole('button',{name:'Seçili kayıtlarla dosyayı aç',exact:true})).toBeEnabled();await page.screenshot({path:'output/cumulative-2026-09-12/report390.png'});await reports.getByRole('button',{name:'Seçili kayıtlarla dosyayı aç',exact:true}).click();const preview=page.getByRole('dialog',{name:'PDF önizlemesi',exact:true});await expect(preview.getByRole('button',{name:'Bu PDF\'yi indir',exact:true})).toBeEnabled({timeout:30000});await preview.getByRole('button',{name:'PDF önizlemesini kapat',exact:true}).click();await page.getByRole('button',{name:/Aileye ver/}).click();await expect(page.getByRole('button',{name:/Aileye ev oyunu/})).toBeVisible();await expect(reports).toHaveCount(0);
 await page.getByRole('button',{name:'Bugün',exact:true}).click();await page.getByRole('button',{name:'Ayarları aç',exact:true}).click();const account=page.getByRole('region',{name:'Google hesabı ve şifreli yedek',exact:true});await expect(account.getByRole('button',{name:'Google ile giriş yap',exact:true})).toBeDisabled();await expect(account.getByRole('button',{name:'Bağlantıyı denetle',exact:true})).toBeEnabled();expect(errors).toEqual([]);
});
