import { test, expect, type Page, type Locator } from "@playwright/test";
import { mkdir, readFile } from "node:fs/promises";
const production = process.env.FAMILY_ENGAGEMENT_PRODUCTION === "1", output = `output/family-engagement-2026-09-08/${production ? "production" : "dev"}`;
const childName = "Kurgu Randevu Çocuğu", parentName = "Kurgu Randevu Annesi";
async function setup(page: Page) {
  await mkdir(output, { recursive: true }); await page.clock.install({ time: new Date("2026-09-18T09:00:00.000Z") }); await page.goto("/classroom?native=1");
  const dialog = page.getByRole("dialog", { name: "Sınıfını hazırla", exact: true }); await dialog.getByLabel("Okul adı").fill("Kurgu Anaokulu"); await dialog.getByLabel("Öğretmen adı soyadı").fill("Kurgu Öğretmen"); await dialog.getByLabel("Sınıf adı").fill("Kurgu Randevu Sınıfı"); await dialog.getByLabel("Maarif Modeli yaş grubu", { exact: true }).selectOption({ label: "60–72 ay" }); await dialog.getByRole("button", { name: "Sınıfımı hazırla", exact: true }).click(); await expect(dialog).toBeHidden();
  await page.getByRole("button", { name: "Çocuk ekle", exact: true }).click(); const add = page.getByRole("dialog", { name: "Çocuk ekle", exact: true }); await add.getByLabel("Çocuğun adı", { exact: true }).fill(childName); await add.getByText("İsteğe bağlı çocuk ve veli bilgileri", { exact: true }).click(); await add.locator("#new-student-guardian-name").fill(parentName); await add.locator("#new-student-guardian-relationship").fill("Anne"); await add.getByRole("button", { name: "Kaydet ve kapat", exact: true }).click(); await expect(add).toBeHidden();
  if (production) { await expect.poll(() => page.evaluate(() => Boolean((window as Window & { __maarifosPwaStatus?: { offlineReady?: boolean } }).__maarifosPwaStatus?.offlineReady)), { timeout: 60000 }).toBe(true); await page.context().setOffline(true); await page.reload({ waitUntil: "domcontentloaded" }); }
}
async function open(page: Page, section: "communication" | "appointments") {
  await page.getByRole("region", { name: "Sınıf yönetimi işleri", exact: true }).getByRole("button").first().click();
  const dialog = page.getByRole("dialog", { name: "Sınıf yönetimi", exact: true }); await dialog.getByLabel("Sınıf yönetimi alanı").selectOption(section); await expect(dialog.getByTestId("family-engagement-workspace")).toBeVisible(); return dialog;
}
async function chooseContact(panel: Locator) { await panel.getByLabel("Aile katılımı çocuğu").selectOption({ label: childName }); await panel.getByLabel("Aile katılımı yakını").selectOption({ label: `${parentName} · Anne` }); }
async function availability(panel: Locator) { await panel.getByRole("button", { name: "Uygun saat aralığı aç", exact: true }).click(); await panel.getByRole("button", { name: "Uygun saatleri kaydet", exact: true }).click(); await expect(panel.getByText("14:00–14:20 · Uygun", { exact: true })).toBeVisible(); }
async function book(panel: Locator) {
  await panel.getByRole("button", { name: "Yeni veli randevusu", exact: true }).click(); const editor = panel.locator(".family-card").filter({ hasText: "Yeni veli randevusu" }); await chooseContact(editor); await editor.getByLabel("Randevu saati", { exact: true }).selectOption({ label: "14:00–14:20" }); await editor.getByLabel("Görüşme yeri / yöntemi").fill("Kurgu görüşme odası"); await editor.getByLabel("Görüşme amacı").fill("Uyum sürecini birlikte değerlendirme"); await editor.getByRole("button", { name: "Randevuyu kaydet", exact: true }).click(); await expect(panel.locator(".family-appointment-status")).toHaveText("Randevu planlandı");
}
async function savePdf(page: Page, label: string, file: string) {
  await page.getByRole("button", { name: label, exact: true }).click(); const preview = page.getByRole("dialog", { name: "PDF önizlemesi", exact: true }); const canvas = preview.locator("canvas").first(); await expect(canvas).toHaveAttribute("data-pdf-rendered", "true"); const download = page.waitForEvent("download"); await preview.getByRole("button", { name: "Bu PDF'yi indir", exact: true }).click(); const doc = await download; await doc.saveAs(`${output}/${file}.pdf`); expect((await readFile(`${output}/${file}.pdf`)).subarray(0, 5).toString()).toBe("%PDF-"); await canvas.scrollIntoViewIfNeeded(); await canvas.screenshot({ path: `${output}/${file}.png` }); await preview.getByRole("button", { name: "PDF önizlemesini kapat", exact: true }).click(); await expect(preview).toBeHidden();
}
test("390px: açık tercih, randevu/değişiklik, gerçek görüşme, özel davet ve ortak PDF/reload", async ({ page }) => {
  await setup(page); let dialog = await open(page, "communication"); const communication = dialog.getByRole("region", { name: "Yakına özel iletişim tercihleri" }); await chooseContact(communication); await expect(communication.locator(".family-preference-state")).toHaveText("Tercih bildirilmemiş");
  await communication.getByRole("checkbox", { name: "Telefon araması", exact: true }).click(); await communication.getByRole("checkbox", { name: "Büyük yazı", exact: true }).click(); await communication.getByLabel("Bildirilen iletişim dili (isteğe bağlı)").fill("Türkçe"); await communication.getByLabel("Uygun saat başlangıcı").fill("14:00"); await communication.getByLabel("Uygun saat bitişi").fill("16:00"); await communication.getByLabel("Bildirim kaynağı").selectOption("oral"); await communication.getByRole("checkbox", { name: "Bu tercihleri seçilen yakın açıkça bildirdi", exact: true }).click(); await communication.getByRole("button", { name: "İletişim tercihini kaydet", exact: true }).click(); await expect(communication.locator(".family-preference-state")).toHaveText("Yakının bildirdiği tercih kayıtlı");
  await dialog.getByRole("button", { name: "Veli randevuları", exact: true }).click(); const panel = dialog.getByRole("region", { name: "Veli randevu planlayıcısı" }); await availability(panel); await book(panel); await savePdf(page, "Yalnız bu veliye davet PDF", "private-invitation"); await savePdf(page, "İsimsiz ortak saat çizelgesi PDF", "anonymous-schedule");
  await panel.getByRole("button", { name: "Randevuyu değiştir", exact: true }).click(); const editor = panel.locator(".family-card").filter({ hasText: "Randevu tarihini / saatini değiştir" }); await editor.getByLabel("Randevu saati", { exact: true }).selectOption({ label: "14:20–14:40" }); await editor.getByLabel("Randevu değişiklik gerekçesi").fill("Yakın yirmi dakika sonrasını bildirdi."); await expect(editor).toHaveCount(1); await editor.getByRole("button", { name: "Randevuyu kaydet", exact: true }).click(); await expect(panel.getByRole("article", { name: "Seçilen randevu" }).getByRole("heading")).toContainText("14:20–14:40");
  await page.clock.setFixedTime(new Date("2026-09-18T12:00:00.000Z")); await panel.getByRole("button", { name: "Son kayıtları yenile", exact: true }).count().then(async n => { if (n) await panel.getByRole("button", { name: "Son kayıtları yenile", exact: true }).click(); else await dialog.getByRole("button", { name: "Son kayıtları yenile", exact: true }).click(); });
  await panel.getByRole("button", { name: "Görüşme sonucunu kaydet", exact: true }).click(); await panel.getByLabel("Gerçek görüşme saati").fill("14:20"); await panel.getByLabel("Görüşülen konular").fill("Çocuğun uyum süreci değerlendirildi."); await panel.getByLabel("Birlikte alınan karar").fill("Bir hafta sonra yeniden gözden geçirilecek."); await panel.getByLabel("Sonraki takip günü (isteğe bağlı)").fill("2026-09-25"); await panel.getByRole("button", { name: "Görüşmeyi ve takibini kaydet", exact: true }).click(); await expect(panel.locator(".family-appointment-status")).toHaveText("Görüşme gerçek veli takip kaydına bağlandı");
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true); await panel.locator(".family-appointment-status").scrollIntoViewIfNeeded(); await page.screenshot({ path: `${output}/completed-meeting-390.png` }); await page.reload(); dialog = await open(page, "appointments"); await dialog.getByLabel("Randevu kaydı", { exact: true }).selectOption({ label: `18.09.2026 14:20 · ${childName} · Görüşüldü` }); await expect(dialog.locator(".family-appointment-status")).toContainText("gerçek veli takip"); await dialog.getByRole("button", { name: "İletişim tercihleri", exact: true }).click(); const pref = dialog.getByRole("region", { name: "Yakına özel iletişim tercihleri" }); await chooseContact(pref); await expect(pref.locator(".family-preference-state")).toHaveText("Yakının bildirdiği tercih kayıtlı"); await expect(pref.getByRole("checkbox", { name: "Büyük yazı", exact: true })).toHaveAttribute("aria-checked", "true");
});
test("IDB: açık uygun saat taslağı sınıf değişince başka sınıfa taşınamaz", async ({ page }) => {
  test.skip(production, "Sınıf değişimi fixture'ı geliştirme modül API'siyle kurulur.");
  await setup(page); const dialog = await open(page, "appointments");
  await dialog.getByRole("button", { name: "Uygun saat aralığı aç", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Uygun saatleri kaydet", exact: true })).toBeVisible();
  await page.evaluate(async () => {
    const { IndexedDbDataStore } = await import("/src/core/index.ts"); const store = new IndexedDbDataStore();
    try { await store.transaction("readwrite", ["classrooms", "settings"], async tx => { const classrooms = await tx.getAll("classrooms"), settings = await tx.getAll("settings"); const selection = settings.find(r => r.settingType === "active-classroom-selection")!, source = classrooms.find(r => r.id === selection.classroomId)!; const id = crypto.randomUUID(); await tx.putMany("classrooms", [{ ...source, id, name: "Kurgu diğer sınıf" }]); await tx.putMany("settings", [{ ...selection, classroomId: id, updatedAt: new Date().toISOString() }]); }); } finally { store.close(); }
  });
  await dialog.getByRole("button", { name: "Son kayıtları yenile", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("Eski taslağın başka sınıfa yazılmasını önlemek");
  await expect(dialog.getByRole("button", { name: "Uygun saatleri kaydet", exact: true })).toHaveCount(0);
  const count = await page.evaluate(async () => { const { IndexedDbDataStore } = await import("/src/core/index.ts"); const store = new IndexedDbDataStore(); try { return (await store.readSnapshot()).settings.filter(r => r.settingType === "family-engagement-v1").length; } finally { store.close(); } });
  expect(count).toBe(0);
});
test("IDB iki sekme: dolu saate çift kayıt engellenir; iptal geçmişi reload ile kalır", async ({ page, context }) => {
  await setup(page); const dialog = await open(page, "appointments"); const panel = dialog.getByRole("region", { name: "Veli randevu planlayıcısı" }); await availability(panel);
  if (production) await book(panel);
  else {
  const other = await context.newPage(); await other.goto("/classroom?native=1");
  const bookFromTab = (p: Page) => p.evaluate(async () => {
    const { IndexedDbDataStore } = await import("/src/core/index.ts"); const { executeFamilyEngagement } = await import("/src/features/family-engagement/family-engagement-service.ts"); const { familyContactSnapshot } = await import("/src/core/domain/family-engagement.ts"); const store = new IndexedDbDataStore();
    try { const s = await store.readSnapshot(), a = s.settings.find(r => r.settingType === "family-engagement-v1" && r.workflow.kind === "availability")!, child = s.students[0]; await executeFamilyEngagement(store, { scope: { academicYearId: a.academicYearId, classroomId: a.classroomId }, now: new Date("2026-09-18T09:05:00.000Z"), command: { action: "appointment", studentId: child.id, appointment: { previousEventId: null, availabilityId: a.id, contact: familyContactSnapshot(child.contacts[0]), scheduledOn: "2026-09-18", startTime: "14:00", endTime: "14:20", location: "Kurgu oda", purpose: "Kurgu görüşme", reason: "", calendarNote: "" } } }); return "saved"; } catch (e) { return e instanceof Error ? e.message : "failed"; } finally { store.close(); }
  });
  const results = await Promise.all([bookFromTab(page), bookFromTab(other)]); expect(results.filter(r => r === "saved")).toHaveLength(1); expect(results.find(r => r !== "saved")).toContain("başka bir sınıf veya yılda"); await other.close();
  }
  await page.clock.setFixedTime(new Date("2026-09-18T09:06:00.000Z")); await dialog.getByRole("button", { name: "Son kayıtları yenile", exact: true }).click(); await panel.getByLabel("Randevu kaydı", { exact: true }).selectOption({ label: `18.09.2026 14:00 · ${childName} · Planlı` }); await panel.getByRole("button", { name: "Randevuyu iptal et", exact: true }).click(); await panel.getByLabel("Randevu iptal gerekçesi").fill("Veli yeni gün belirlemek istedi."); await panel.getByRole("button", { name: "Gerekçeli iptali kaydet", exact: true }).click(); await expect(panel.locator(".family-appointment-status")).toHaveText("Randevu iptal edildi"); await page.reload(); const reloaded = await open(page, "appointments"); await reloaded.getByLabel("Randevu kaydı", { exact: true }).selectOption({ label: `18.09.2026 14:00 · ${childName} · İptal` }); await expect(reloaded.locator(".family-appointment-status")).toHaveText("Randevu iptal edildi");
});
