import { test, expect, type Page } from "@playwright/test";
import { mkdir } from "node:fs/promises";
const production = process.env.LEARNING_PRODUCTION === "1", output = `output/learning-centers-2026-09-08/${production ? "production" : "development"}`;
test("MR104 gerçek mobil merkez/stok işlemi, çifte ayırma engeli, iade, geçmiş ve PDF", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.name)); if (production) page.on("request", r => { if (new URL(r.url()).pathname.startsWith("/src/")) errors.push("Production source import"); });
  await mkdir(output, { recursive: true }); await page.clock.install({ time: new Date("2026-09-14T09:00:00.000Z") }); await page.goto("/classroom?native=1");
  const setup = page.getByRole("dialog", { name: "Sınıfını hazırla", exact: true }); await setup.getByLabel("Okul adı").fill("Kurgu Anaokulu"); await setup.getByLabel("Öğretmen adı soyadı").fill("Kurgu Öğretmen"); await setup.getByLabel("Sınıf adı").fill("Kurgu Merkez Sınıfı"); await setup.getByLabel("Maarif Modeli yaş grubu", { exact: true }).selectOption({ label: "60–72 ay" }); await setup.getByRole("button", { name: "Sınıfımı hazırla", exact: true }).click(); await expect(setup).toBeHidden();
  if (production) { await expect.poll(() => page.evaluate(() => (window as any).__maarifosPwaStatus?.offlineReady ?? false), { timeout: 90000 }).toBe(true); await page.context().setOffline(true); await page.reload(); }
  await page.getByRole("region", { name: "Sınıf yönetimi işleri", exact: true }).getByRole("button").first().click(); let d = page.getByRole("dialog", { name: "Sınıf yönetimi", exact: true });
  await d.getByLabel("Sınıf yönetimi alanı").selectOption("inventory"); await d.getByText("Yeni malzeme ekle", { exact: true }).click(); await d.getByLabel("Malzeme adı", { exact: true }).fill("Kurgu Ahşap Blok Seti"); await d.getByLabel("Başlangıç miktarı", { exact: true }).fill("5"); await d.getByRole("button", { name: "Malzemeyi kaydet", exact: true }).click(); await expect(d.getByRole("status")).toContainText("kaydedildi");
  await d.getByLabel("Sınıf yönetimi alanı").selectOption("centers"); await d.getByText("Yeni merkez düzeni oluştur", { exact: true }).click(); await d.getByLabel("Düzen başlığı", { exact: true }).fill("Kurgu Birinci Hafta"); await d.getByLabel("Bitiş / gözden geçirme tarihi", { exact: true }).fill("2026-09-18"); await d.getByLabel("1. merkez adı", { exact: true }).fill("Blok merkezi"); await d.getByLabel("Malzeme", { exact: true }).selectOption({ label: "Kurgu Ahşap Blok Seti · 5 adet kullanılabilir" }); await d.getByLabel("Miktar", { exact: true }).fill("3"); await d.getByRole("button", { name: "Malzemeyi merkeze ekle", exact: true }).click(); await d.getByRole("button", { name: "Düzeni kaydet ve malzemeyi ayır", exact: true }).click(); await expect(d.getByRole("status")).toContainText("kaydedildi"); await expect(d.getByText("Kurgu Ahşap Blok Seti: 3 / 3 merkezde", { exact: true })).toBeVisible();
  await d.getByRole("button", { name: "Düzeni kaydet ve malzemeyi ayır", exact: true }).click(); await expect(d.getByRole("alert")).toContainText("stok");
  await d.getByText("Yeni gözlem ve düzenleme kararı", { exact: true }).click(); await d.getByLabel("Blok merkezi ortam gözlemi", { exact: true }).fill("Kurgu: raf önü dar kaldı."); await d.getByLabel("Blok merkezi sonraki adımı", { exact: true }).fill("Rafı duvar kenarına al."); await d.getByRole("button", { name: "Gözlem ve kararı kaydet", exact: true }).click(); await expect(d.getByText("Sonraki adım: Rafı duvar kenarına al.", { exact: true })).toBeVisible();
  await d.getByRole("button", { name: "Merkez düzeni PDF", exact: true }).click(); const pdf = page.getByRole("dialog", { name: "PDF önizlemesi", exact: true }); await expect(pdf.locator("canvas[data-pdf-rendered=true]").first()).toBeVisible({ timeout: 30000 }); const download = page.waitForEvent("download"); await pdf.getByRole("button", { name: "Bu PDF'yi indir", exact: true }).click(); await (await download).saveAs(`${output}/merkez-duzeni.pdf`); await page.screenshot({ path: `${output}/pdf-preview.png` }); await pdf.getByRole("button", { name: "PDF önizlemesini kapat", exact: true }).click();
  await d.getByText("Düzeni kapat ve malzemeleri iade et", { exact: true }).click(); await d.getByLabel("Kapanış / değişiklik gerekçesi", { exact: true }).fill("Kurgu yeni hafta için raf değişti."); await d.getByRole("button", { name: "Kapat ve iade et", exact: true }).click(); await expect(d.getByRole("status")).toContainText("stoka iade");
  await page.reload(); await page.getByRole("region", { name: "Sınıf yönetimi işleri", exact: true }).getByRole("button").first().click(); d = page.getByRole("dialog", { name: "Sınıf yönetimi", exact: true }); await d.getByLabel("Sınıf yönetimi alanı").selectOption("centers"); await d.getByLabel("Kayıtlı düzen", { exact: true }).selectOption({ label: "14.09.2026 · Kurgu Birinci Hafta · Kapalı" }); await expect(d.getByText("Kurgu Ahşap Blok Seti: 0 / 3 merkezde", { exact: true })).toBeVisible(); expect(await d.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true); await page.screenshot({ path: `${output}/center-390.png` }); await d.getByLabel("Sınıf yönetimi alanı").selectOption("inventory"); await d.getByRole("combobox", { name: "Malzeme seç", exact: true }).selectOption({ label: "Kurgu Ahşap Blok Seti · 5 adet kullanılabilir" }); expect(errors).toEqual([]);
});
