import {expect,test} from "@playwright/test";
import {mkdir,readFile} from "node:fs/promises";
test.setTimeout(90000);
test("320px kutu hazırlığı ve gerçek eksik malzeme seçimi; çevrimdışı iki PDF indirme kendi geçmişiyle geçerli",async({page,context})=>{
  await page.setViewportSize({width:320,height:900});await page.clock.setFixedTime(new Date("2026-09-14T10:00:00.000Z"));await page.goto("/tests/runtime-fixture.html");await page.evaluate(async()=>{const fx=await import("/tests/fixtures/material-box-mount.tsx");Object.assign(window,{materialBoxes:await fx.mountMaterialBoxes()});});
  const panel=page.getByRole("region",{name:"Malzeme kutusu etiketleri",exact:true}),preview=page.getByRole("dialog",{name:"PDF önizlemesi",exact:true});await expect(panel.getByRole("button",{name:"12 kutunun A4 etiketlerini hazırla",exact:true})).toBeEnabled();
  await panel.getByRole("button",{name:"Kutuyu hazır olarak kaydet",exact:true}).first().click();await expect(panel.locator(".material-box-success")).toHaveText("Kutu hazır olarak kaydedildi.");
  const needs=panel.getByRole("group",{name:"Eksik malzemeyi haftanın hazırlığına ekle",exact:true});await needs.getByRole("checkbox").first().check();await panel.getByRole("button",{name:"1 eksik malzemeyi haftanın hazırlığına ekle",exact:true}).click();await expect(panel.locator(".material-box-success")).toHaveText("Seçilen malzemeler haftanın hazırlık listesine eklendi.");
  await panel.getByRole("button",{name:/planını aç/u}).first().click();expect(await page.evaluate(()=>(window as any).materialBoxes.opened)).toHaveLength(1);
  await panel.getByRole("button",{name:"12 kutunun A4 etiketlerini hazırla",exact:true}).click();await expect(preview.locator("canvas[data-pdf-rendered=true]").first()).toBeVisible({timeout:30000});await context.setOffline(true);await mkdir("output/material-box-labels-qa",{recursive:true});
  for(const name of ["ui-first","ui-second"]){const event=page.waitForEvent("download",{timeout:15000});await preview.getByRole("button",{name:"Bu PDF'yi indir",exact:true}).click();await(await event).saveAs(`output/material-box-labels-qa/${name}.pdf`);await expect(preview.getByText("Önizlemedeki PDF indirildi.",{exact:true})).toBeVisible();await expect(preview.getByRole("button",{name:"Bu PDF'yi indir",exact:true})).toBeEnabled();}
  expect(await readFile("output/material-box-labels-qa/ui-first.pdf")).toEqual(await readFile("output/material-box-labels-qa/ui-second.pdf"));await expect(preview.getByRole("alert")).toHaveCount(0);await page.screenshot({path:"output/material-box-labels-qa/320px-preview.png"});await preview.getByRole("button",{name:"PDF önizlemesini kapat",exact:true}).click();
  await panel.getByRole("button",{name:"Kutuyu yeniden hazırlığa aç",exact:true}).click();await expect(panel.locator(".material-box-success")).toHaveText("Kutu yeniden hazırlığa açıldı.");const stored=await page.evaluate(async()=>{const f=(window as any).materialBoxes;return{model:await f.readModel(),snapshot:await f.store.readSnapshot()};});expect(stored.model.boxes[0].prepared).toBe(false);expect(stored.model.needs.filter(n=>n.listed)).toHaveLength(1);expect(stored.snapshot.settings.filter(r=>r.settingType==="document-version")).toHaveLength(1);expect(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);
  await panel.getByLabel("Etiket haftası",{exact:true}).fill("2026-09-21");await panel.getByRole("button",{name:"Öğrenme merkezlerine malzeme ayır",exact:true}).click();await panel.getByRole("button",{name:"Haftanın planını ve malzemelerini hazırla",exact:true}).click();expect((await page.evaluate(()=>(window as any).materialBoxes.opened)).slice(-2)).toEqual(["centers","2026-09-21"]);
});
