import {test,expect,type Page} from "@playwright/test";
import {mkdir,readFile} from "node:fs/promises";
import {PDFDocument} from "pdf-lib";
import {rolldown} from "rolldown";

let readerBundle:string|undefined;
async function records(page:Page,name:string):Promise<any[]>{
  if(!await page.evaluate(()=>Boolean((window as any).__printAcceptanceRead))){
    if(!readerBundle){const bundle=await rolldown({input:"src/core/repository/indexed-db.ts"});try{const generated=await bundle.generate({format:"iife",name:"PrintAcceptanceCore",inlineDynamicImports:true});readerBundle=generated.output.filter(o=>o.type==="chunk").map(o=>o.code).join("\n")+'\nwindow.__printAcceptanceRead=async function(name){const store=new PrintAcceptanceCore.IndexedDbDataStore();try{return(await store.readSnapshot())[name];}finally{store.close();}};';}finally{await bundle.close();}}
    await page.addScriptTag({content:readerBundle});
  }
  return page.evaluate(name=>(window as any).__printAcceptanceRead(name),name);
}

test("Derlenmiş uygulamada dört belge, küçük grup ve aile yanıtı çevrimdışı tamamlanır",async({page,context})=>{
  const output="output/print-workshop-production/offline";await mkdir(output,{recursive:true});
  await page.clock.setFixedTime(new Date("2026-09-17T09:00:00.000Z"));await page.goto("/classroom?native=1");
  const setup=page.getByRole("dialog",{name:"Sınıfını hazırla",exact:true});await setup.getByLabel("Okul adı").fill("Kurgu Belge Anaokulu");await setup.getByLabel("Öğretmen adı soyadı").fill("Kurgu Öğretmen");await setup.getByLabel("Sınıf adı").fill("Kurgu Çiçekler");await setup.getByLabel("Maarif Modeli yaş grubu",{exact:true}).selectOption({label:"60–72 ay"});await setup.getByRole("button",{name:"Sınıfımı hazırla",exact:true}).click();await expect(setup).toBeHidden();
  await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__maarifosPwaStatus?.offlineReady)),{timeout:60000}).toBe(true);await context.setOffline(true);await page.reload({waitUntil:"domcontentloaded"});
  for(const name of ["Kurgu Deniz Çınar","Kurgu Ada Yaprak"]){await page.getByRole("button",{name:"Çocuk ekle",exact:true}).click();const add=page.getByRole("dialog",{name:"Çocuk ekle",exact:true});await add.getByLabel("Çocuğun adı",{exact:true}).fill(name);await add.getByRole("button",{name:"Kaydet ve kapat",exact:true}).click();await expect(add).toBeHidden();}
  await page.clock.setFixedTime(new Date("2026-09-17T09:01:00.000Z"));await page.getByRole("button",{name:"Belgeler",exact:true}).click();
  const desk=page.getByRole("region",{name:"Öğretmenin masa belgeleri",exact:true});await desk.getByRole("button",{name:/17 Eylül 2026.*Etkinlik yerleştir/u}).click();const selectedDay=desk.getByRole("region",{name:"Seçilen gün",exact:true});await selectedDay.locator(".work-package-apply").click();await expect(selectedDay.getByRole("button",{name:"Planı aç",exact:true}).first()).toBeVisible({timeout:30000});
  const daily=(await records(page,"plans")).find(p=>p.planType==="daily"&&p.civilDate==="2026-09-17");expect(daily?.sourceWeeklyPlanId).toBeTruthy();
  const workshop=page.getByRole("region",{name:"Sınıfta kullanılacak belgeler",exact:true});await workshop.getByRole("button",{name:/Küçük grup kartları/u}).click();
  const groups=page.getByRole("region",{name:"Küçük grup kartları",exact:true});await groups.getByRole("checkbox",{name:"Kurgu Deniz Çınar küçük gruba seç",exact:true}).check();await groups.getByRole("checkbox",{name:"Kurgu Ada Yaprak küçük gruba seç",exact:true}).check();await page.clock.setFixedTime(new Date("2026-09-17T09:02:00.000Z"));await groups.getByRole("button",{name:"Seçili grubu günlük plana yerleştir",exact:true}).click();await expect(groups.locator(".small-group-cards__success")).toContainText("küçük grubu günlük plana yerleştirildi");
  const assigned=(await records(page,"plans")).find(p=>p.id===daily.id);expect(assigned.assignmentMode).toBe("selected-students");expect(assigned.studentIds).toHaveLength(2);expect((await records(page,"activities")).find(a=>a.planId===daily.id).studentIds).toEqual(assigned.studentIds);
  const preview=page.getByRole("dialog",{name:"PDF önizlemesi",exact:true});
  async function downloadPdf(name:string,landscape:boolean){
    await expect(preview.locator("canvas[data-pdf-rendered=true]").first()).toBeVisible({timeout:30000});
    const button=preview.getByRole("button",{name:"Bu PDF'yi indir",exact:true});
    const pending=page.waitForEvent("download",{timeout:15000});await button.click();await(await pending).saveAs(`${output}/${name}.pdf`);
    const firstBytes=await readFile(`${output}/${name}.pdf`);const pdf=await PDFDocument.load(firstBytes);
    expect(pdf.getPageCount()).toBeGreaterThan(0);expect(pdf.getPages().every(p=>landscape?p.getWidth()>p.getHeight():p.getHeight()>p.getWidth())).toBe(true);
    await expect(preview.getByText("Önizlemedeki PDF indirildi.",{exact:true})).toBeVisible();
    await page.screenshot({path:`${output}/${name}.png`});
    // Its own version-history write must leave this same reviewed artifact usable.
    await expect(button).toBeEnabled();
    const repeated=page.waitForEvent("download",{timeout:15000});await button.click();await(await repeated).saveAs(`${output}/${name}-repeat.pdf`);
    expect(await readFile(`${output}/${name}-repeat.pdf`)).toEqual(firstBytes);
    await expect(preview.getByText("Belgenin kaynak kayıtları değişti. Eski dosyanın indirilmesi durduruldu.",{exact:true})).toHaveCount(0);
  }
  async function closePreview(){await preview.getByRole("button",{name:"PDF önizlemesini kapat",exact:true}).click();await expect(preview).toHaveCount(0);}
  await groups.getByRole("button",{name:"Seçili kartları A4 PDF önizle",exact:true}).click();await downloadPdf("small-group",false);await closePreview();
  await groups.getByRole("button",{name:"Günlük planı aç",exact:true}).click();const actualDay=page.getByRole("dialog",{name:"Gün planı",exact:true});await expect(actualDay).toBeVisible();await expect(actualDay).toContainText("17 Eylül 2026");const actualActivity=(await records(page,"activities")).find(a=>a.planId===daily.id);await expect(actualDay.getByRole("button").filter({hasText:actualActivity.title}).first()).toBeVisible();await actualDay.getByRole("button",{name:"Gün planı ekranını kapat",exact:true}).click();await expect(actualDay).toBeHidden();
  await workshop.getByRole("button",{name:/Teslim çizelgesi ve klasör/u}).click();const kit=page.getByRole("region",{name:"Teslim çizelgesi ve klasör seti",exact:true});await kit.getByRole("button",{name:"Günlük teslim çizelgesini hazırla",exact:true}).click();await downloadPdf("pickup",true);await closePreview();
  // Refresh the saved-document inventory by changing month and returning; only
  // the downloaded current-month version is explicitly selected for this kit.
  await kit.getByLabel("Klasör ayı",{exact:true}).fill("2026-10");await kit.getByLabel("Klasör ayı",{exact:true}).fill("2026-09");const choices=kit.getByRole("group",{name:"Klasöre alınacak belgeler",exact:true});await expect(choices.getByRole("checkbox").first()).toBeVisible();const pickupChoice=choices.getByRole("checkbox",{name:/Saklanan sürüm: Günlük teslim çizelgesi/u});await expect(pickupChoice).toBeVisible();for(const choice of await choices.getByRole("checkbox").all())await choice.uncheck();await pickupChoice.check();
  await kit.getByRole("button",{name:"1 belgeyle klasör setini hazırla",exact:true}).click();await downloadPdf("binder",false);await preview.locator(".pdf-preview-secondary-actions > summary").click();const zip=page.waitForEvent("download");await preview.getByRole("button",{name:"Klasör setini seçilen belgelerle indir",exact:true}).click();await(await zip).saveAs(`${output}/binder.zip`);expect((await readFile(`${output}/binder.zip`)).subarray(0,2).toString()).toBe("PK");await closePreview();
  await workshop.getByRole("button",{name:/Aileye ev oyunu/u}).click();const family=page.getByRole("region",{name:"Aileye ev oyunu kartı",exact:true});await family.getByRole("checkbox",{name:"Kurgu Deniz Çınar",exact:true}).check();await family.getByRole("checkbox",{name:"Kurgu Ada Yaprak",exact:true}).check();const activity=(await records(page,"activities")).find(a=>a.planId===daily.id);await family.getByLabel("Kaynak etkinlik",{exact:true}).selectOption(activity.id);
  if(!(await family.getByLabel("Malzemeler",{exact:true}).inputValue()).trim())await family.getByRole("button",{name:"Bu oyun malzeme gerektirmez",exact:true}).click();if(!(await family.getByLabel("Evde oyun adımları",{exact:true}).inputValue()).trim())await family.getByLabel("Evde oyun adımları",{exact:true}).fill("Kurgu öğretmen hazırlığı: Çocuğunuzla sırayla bir hareket seçip birbirinizi taklit edin. İstediğinizde ara verin.");await page.clock.setFixedTime(new Date("2026-09-17T09:03:00.000Z"));await family.getByRole("button",{name:"Kartları kaydet ve PDF'yi aç",exact:true}).click();await downloadPdf("home-game",false);await closePreview();
  const feedback="Kurgu aile yanıtı: Sırayla iki hareket seçtik; çocuk oyuna ara vermek istediğini söyledi.";await family.getByLabel("Ailenin gerçek geri bildirimi",{exact:true}).fill(feedback);await page.clock.setFixedTime(new Date("2026-09-17T09:04:00.000Z"));await family.getByRole("button",{name:"Gelen aile yanıtını kaydet",exact:true}).click();await expect(family.getByRole("status")).toHaveText("Aile yanıtı aynı çocuk ve etkinliğe kaydedildi.");await expect(family.locator("blockquote")).toContainText(feedback);
  const savedCards=(await records(page,"settings")).filter(r=>r.settingType==="home-game-card-v1");expect(savedCards.filter(r=>r.workflow.kind==="prepared")).toHaveLength(2);expect(savedCards.filter(r=>r.workflow.kind==="feedback")).toHaveLength(1);const cardId=savedCards.find(r=>r.workflow.kind==="feedback").workflow.cardId;
  await workshop.getByRole("button",{name:/Aile dönüş panosu/u}).click();const responseBoard=page.getByRole("region",{name:"Aile dönüş panosu",exact:true});await responseBoard.getByRole("button",{name:"Bu aile yanıtıyla ilerle",exact:true}).click();const responseStart=performance.now();await responseBoard.getByRole("button",{name:"Kaynak etkinliği bu güne yeniden planla",exact:true}).click();await expect(responseBoard.getByRole("button",{name:"Kayıtlı planı aç",exact:true})).toBeVisible({timeout:30000});console.log(`Family response click-to-result: ${Math.round(performance.now()-responseStart)} ms`);const responseAction=(await records(page,"settings")).find(r=>r.settingType==="home-game-card-v1"&&r.workflow.kind==="response-action"&&r.workflow.action==="plan");expect(responseAction).toBeTruthy();const repeated=(await records(page,"activities")).find(a=>a.id===responseAction.workflow.activityId);expect(repeated.studentIds).toEqual([responseAction.studentId]);expect(repeated.status).toBe("planned");expect(repeated.title).toBe(activity.title);await responseBoard.getByRole("button",{name:"Kayıtlı planı aç",exact:true}).click();const responseDay=page.getByRole("dialog",{name:"Seçili günün planı",exact:true});await expect(responseDay).toBeVisible();await expect(responseDay).toContainText(responseAction.workflow.targetDate.slice(8));await responseDay.getByRole("button",{name:"Seçili günün planı ekranını kapat",exact:true}).click();await expect(responseDay).toBeHidden();await expect(responseBoard.getByRole("button",{name:"Kayıtlı planı aç",exact:true})).toBeVisible({timeout:30000});
  await page.reload({waitUntil:"domcontentloaded"});await page.getByRole("button",{name:"Belgeler",exact:true}).click();await workshop.getByRole("button",{name:/Aileye ev oyunu/u}).click();await family.getByLabel("Kayıtlı kart",{exact:true}).selectOption(cardId);await expect(family.getByText(feedback,{exact:false})).toBeVisible();expect((await records(page,"plans")).find(p=>p.id===daily.id).studentIds).toEqual(assigned.studentIds);expect(await page.evaluate(()=>navigator.onLine)).toBe(false);expect(await family.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.screenshot({path:`${output}/feedback-restored.png`});
});


