import {test,expect} from "@playwright/test";
import {mkdir,writeFile} from "node:fs/promises";
test.use({viewport:{width:320,height:844}});test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date("2026-09-12T09:00:00Z"));});

test("weekly Word orientation and teacher footer; annual summary counts full sources and class-only actual closure note",async({page})=>{
 await page.goto('/tests/teacher-report-center-fixture.html');await page.waitForFunction(()=>!!(window as any).reportTest);
 const result=await page.evaluate(async()=>{
  const {store}=(window as any).reportTest;
  const {closeTeacherDay}=await import('/src/features/day-closure/teacher-day-closure.ts');
  const {teacherReportModel,reportExecutiveSummary}=await import('/src/features/teacher-report-center/teacher-report-model.ts');
  const {createTeacherReportRecipe,reportNodes}=await import('/src/features/teacher-report-center/teacher-report-document.ts');
  const note='Ertesi gün gerçek kaynak notu: çocukların seçtiği oyunu yeniden hazırlayacağım.';
  const closure=await closeTeacherDay(store,{civilDate:'2026-09-11',nextDayNote:note,now:new Date('2026-09-12T09:00:00Z')});
  const snapshot=await store.readSnapshot(),annual=teacherReportModel(snapshot,{period:'year',day:'2026-09-12'}),narrow=teacherReportModel(snapshot,{period:'year',day:'2026-09-12',studentIds:[snapshot.students[0].id]});
  const nodes=reportNodes(annual,annual.rows),texts=nodes.filter(n=>'text' in n).map(n=>n.text).join('\n');
  const weekly=await createTeacherReportRecipe(store,{period:'week',day:'2026-09-12'}),year=await createTeacherReportRecipe(store,annual.input);
  const files=await Promise.all([weekly.exportActions!.find(a=>a.id==='word')!.build(weekly.initial),year.build(year.initial),year.exportActions!.find(a=>a.id==='word')!.build(year.initial),year.exportActions!.find(a=>a.id==='excel')!.build(year.initial)]);
  return {teacher:annual.teacherName,count:annual.rows.length,summary:reportExecutiveSummary(annual.rows)[0],full:annual.rows.every(r=>texts.includes(r.text)),numbered:annual.rows.every((_,i)=>texts.includes(`${i+1}. `)),closure:annual.rows.filter(r=>r.sourceId===closure.id).map(r=>({category:r.category,text:r.text})),narrow:narrow.rows.some(r=>r.sourceId===closure.id),files:files.map(f=>({name:f.fileName,bytes:Array.from(f.bytes)}))};
 });
 expect(result.summary).toBe(`Seçilen kaynak kaydı: ${result.count}`);expect(result.full).toBe(true);expect(result.numbered).toBe(true);expect(result.narrow).toBe(false);expect(result.closure).toEqual([{category:'supports',text:'Ertesi gün gerçek kaynak notu: çocukların seçtiği oyunu yeniden hazırlayacağım.'}]);
 const output='output/teacher-report-center/final';await mkdir(output,{recursive:true});for(const file of result.files)await writeFile(`${output}/${file.name}`,Buffer.from(file.bytes));await writeFile(`${output}/proof.json`,JSON.stringify({...result,files:result.files.map(f=>f.name)},null,2));
 await page.getByText('Hazır tamamlama ve resmî kaynaklar',{exact:true}).click();await page.getByRole('button',{name:'Gün kapanışı ve ertesi gün notu',exact:true}).click();await expect(page.getByLabel('Açılan işlem')).toHaveText('assessment:2026-09-12');
});
test("teacher report confirms actual draft once, exports same four formats offline and preserves narrowed refreshed source",async({page,context})=>{
 test.setTimeout(90000);await page.goto("/tests/teacher-report-center-fixture.html");const panel=page.getByRole("region",{name:"İdare ve öğretmen dosyası",exact:true});await expect(panel.getByRole("button",{name:"Seçili kayıtlarla dosyayı aç",exact:true})).toBeEnabled();
 const check=panel.getByRole("group",{name:"Kendi yazdığım değerlendirmeyi kaydet"}).getByRole("checkbox");await check.check();const save=panel.getByRole("button",{name:"Seçili değerlendirmelerimi kaydet",exact:true});await save.evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect(check).toHaveCount(0);expect(await page.evaluate(async()=>(await (window as any).reportTest.store.readSnapshot()).reportDrafts.filter(r=>r.status==="teacher-saved").length)).toBe(1);
 await panel.locator("details").filter({has:page.locator("summary",{hasText:"Çocuk kapsamı"})}).locator("summary").click();await panel.getByRole("checkbox",{name:"Kurgu Çocuk 2",exact:true}).uncheck();await panel.getByRole("button",{name:"Seçili kayıtlarla dosyayı aç",exact:true}).click();const preview=page.getByRole("dialog",{name:"PDF önizlemesi",exact:true});const pdf=preview.getByRole("button",{name:"Bu PDF'yi indir",exact:true});await expect(pdf).toBeEnabled({timeout:30000});
 await page.evaluate(async()=>{await import("/src/features/teacher-report-center/teacher-report-word.ts");await import("/src/features/teacher-report-center/teacher-report-spreadsheet.ts");});
 const output="output/teacher-report-center";await mkdir(output,{recursive:true});let event=page.waitForEvent("download");await pdf.click();await(await event).saveAs(`${output}/report.pdf`);await expect(pdf).toBeEnabled();await preview.locator(".pdf-preview-secondary-actions > summary").click();for(const offline of [false,true]){await context.setOffline(offline);for(const [label,extension] of [["Word indir","docx"],["Excel indir","xlsx"],["Seçili eklerle dosya paketini indir","zip"]]){event=page.waitForEvent("download");await preview.getByRole("button",{name:label,exact:true}).click();await(await event).saveAs(`${output}/report.${extension}`);}}
 await page.evaluate(async()=>{const {store,bump}=(window as any).reportTest;const s=await store.readSnapshot(),o=s.observations[0];await store.transaction("readwrite",["observations"],tx=>tx.putMany("observations",[{...o,rawText:"Yenilenen gerçek gözlem. "+"Uzun kaynak eksiksiz korunmalı. ".repeat(100)}]));bump();});await expect(pdf).toBeDisabled();await preview.getByRole("button",{name:"Aynı seçimlerle güncelle",exact:true}).click();await expect(pdf).toBeEnabled({timeout:30000});event=page.waitForEvent("download");await pdf.click();await(await event).saveAs(`${output}/long-report.pdf`);for(const [label,extension] of [["Word indir","docx"],["Excel indir","xlsx"]]){event=page.waitForEvent("download");await preview.getByRole("button",{name:label,exact:true}).click();await(await event).saveAs(`${output}/long-report.${extension}`);}
 const persisted=await page.evaluate(async()=>{const s=await (window as any).reportTest.store.readSnapshot();return s.settings.filter(r=>r.settingType==="document-version").map(r=>r.studentIds);});expect(persisted.length).toBeGreaterThan(0);expect(persisted.every(ids=>ids.length===1)).toBe(true);await preview.getByRole("button",{name:"PDF önizlemesini kapat",exact:true}).click();await context.setOffline(true);await panel.getByRole("button",{name:"Günlük",exact:true}).click();await expect(panel.getByRole("button",{name:"Aylık",exact:true})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${output}/panel320.png`});
});
test("one snapshot projection keeps boundaries, scopes, state counts, empty actions and source guards",async({page})=>{
 await page.goto("/tests/teacher-report-center-fixture.html");await page.waitForFunction(()=>!!(window as any).reportTest);const result=await page.evaluate(async()=>{const {store}=(window as any).reportTest;const {teacherReportModel,reportPeriodBounds}=await import("/src/features/teacher-report-center/teacher-report-model.ts");const {createTeacherReportRecipe}=await import("/src/features/teacher-report-center/teacher-report-document.ts");const s=await store.readSnapshot(),child=s.students[0].id,other=s.students[1].id;const model=teacherReportModel(s,{period:"month",day:"2026-09-12",studentIds:[child]});const recipe=await createTeacherReportRecipe(store,model.input);const noApplication=model.rows.filter(r=>r.category==="applications").length===0;const excludesOther=model.rows.every(r=>!r.studentIds.includes(other));const year={...s.academicYears[0],startDate:"2026-09-01",endDate:"2027-08-31"};const term=reportPeriodBounds(year,{period:"term",day:"2027-02-09"}),week=reportPeriodBounds(year,{period:"week",day:"2026-09-01"});let rejects=false;try{teacherReportModel(s,{period:"day",day:"2025-01-01"});}catch{rejects=true;}await store.transaction("readwrite",["students"],tx=>tx.putMany("students",[{...s.students[0],displayName:"Değişen kurgu isim"}]));let stale=false;try{await recipe.assertExportAllowed!(recipe.initial);}catch{stale=true;}return{noApplication,excludesOther,term,week,rejects,stale};});expect(result).toEqual({noApplication:true,excludesOther:true,term:{start:"2027-02-08",end:"2027-06-25"},week:{start:"2026-09-01",end:"2026-09-06"},rejects:true,stale:true});
});
test("report version survives real backup restore and is removed only with its child; empty date offers actual actions",async({page})=>{
 await page.goto("/tests/teacher-report-center-fixture.html");await page.waitForFunction(()=>!!(window as any).reportTest);
 const result=await page.evaluate(async()=>{const {store,scope}=(window as any).reportTest;const {createTeacherReportRecipe}=await import("/src/features/teacher-report-center/teacher-report-document.ts");const {saveDocumentVersion}=await import("/src/features/documents/document-history-service.ts");const {BackupService}=await import("/src/core/backup/backup-service.ts");const {IndexedDbDataStore}=await import("/src/core/repository/indexed-db.ts");const {previewPermanentStudentDeletion,permanentlyDeleteStudent}=await import("/src/features/students/student-lifecycle.ts");const before=await store.readSnapshot(),studentId=before.students[0].id;const recipe=await createTeacherReportRecipe(store,{period:"month",day:"2026-09-12",studentIds:[studentId]});const file=await recipe.build(recipe.initial);const first=await saveDocumentVersion({store,scope},{file,title:recipe.title,selection:recipe.initial});const retry=await saveDocumentVersion({store,scope},{file,title:recipe.title,selection:recipe.initial});const now=new Date("2026-09-12T12:00:00Z"),backup=await new BackupService(store,{appVersion:"0.43.0",clock:()=>now}).exportBackup();const restored=new IndexedDbDataStore({databaseName:crypto.randomUUID()});await new BackupService(restored,{appVersion:"0.43.0",clock:()=>now}).restoreBackup(backup,{mode:"replace",createRecoverySnapshot:false});const snapshot=await restored.readSnapshot(),history=snapshot.settings.find(r=>r.id===first.id),impact=previewPermanentStudentDeletion(snapshot,studentId);await permanentlyDeleteStudent(restored,{studentId,confirmationName:impact.displayName,expectedFingerprint:impact.fingerprint,now});const after=await restored.readSnapshot();restored.close();return{same:first.id===retry.id,restored:history?.sha256===first.sha256,removed:!after.settings.some(r=>r.id===first.id),other:after.students.some(r=>r.id===before.students[1].id)};});expect(result).toEqual({same:true,restored:true,removed:true,other:true});
 await page.reload();const panel=page.getByRole("region",{name:"İdare ve öğretmen dosyası",exact:true});await expect(panel.getByText("Çocuk kapsamı · 1 çocuk",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Günlük",exact:true}).click();await panel.getByLabel("Rapor tarihi",{exact:true}).fill("2026-09-13");await expect(panel.getByRole("button",{name:"Seçili kayıtlarla dosyayı aç",exact:true})).toBeDisabled();await panel.getByText("Hazır tamamlama ve resmî kaynaklar",{exact:true}).click();await panel.getByRole("button",{name:"Bu güne plan hazırla",exact:true}).click();await expect(page.getByLabel("Açılan işlem")).toHaveText("plan:2026-09-13");
});
