export const REPORT_EDITOR_COPY = {
  title: "Öğretmen gözlem özeti",
  loading: "Gözlem özeti hazırlanıyor…",
  loadError: "Gözlem özeti okunamadı. Ekranı yeniden açın.",
  overviewError: "Gözlem özeti okunamadı. Ekranı yeniden açın.",
  periodStart: "Dönem başlangıcı",
  periodEnd: "Dönem sonu",
  evidence: "Rapora alınacak gözlemler",
  selectedCount: (count: number) => `${count} gözlem seçili`,
  empty: "Bu dönemde kayıt yok. Tarih aralığını değiştirin veya önce bir gözlem kaydedin.",
  evaluation: "Öğretmen değerlendirmesi",
  evaluationHint: "Seçtiğiniz gözlemlere dayanan değerlendirmenizi yazın.",
  nextSupport: "Sonraki destek adımı (isteğe bağlı)",
  support: "Bu gözlemde destek",
  source: "Gözlem ve Maarif kaynağı",
  programSource: "Program kaynağı",
  profileDetails: "Kayıt arşivi ve çocuk bilgileri",
  unavailable: (count: number) => `${count} kayıt kaynak veya üyelik doğrulaması tamamlanamadığı için bu özete alınamıyor. Ham gözlemler arşivde korunur.`,
  noDomain: "Alan belirtilmedi",
  saved: "Taslak bu cihazda korundu.",
  saving: "Taslak kaydediliyor…",
  unsaved: "Değişiklikler kaydedilecek.",
  approve: "Özeti onayla",
  approving: "Özet onaylanıyor…",
  approved: "Öğretmen onaylı",
  confirm: "Seçilen gözlemleri ve değerlendirmemi kontrol ettim.",
  missing: "Onay için bir gözlem seçin ve değerlendirmenizi yazın.",
  confirmHint: "İçeriği kontrol edip onay kutusunu işaretleyin.",
  pdf: "PDF indir",
  pdfReady: "PDF bu cihaz için hazırlandı.",
  newDraft: "Yeni taslak oluştur",
  newDraftHint: "Önceki onaylı özet korunur.",
  previous: "Kaydedilmiş özetler",
  currentSources: "Kaynak kayıtlar doğrulandı.",
  stale: "Kaynak kayıtlar değişmiş. Güncel kayıtlarla yeni taslak oluşturup yeniden onaylayın.",
  sourceChanged: "PDF hazırlanırken özet değişti. Güncel özeti yeniden açın.",
  refreshSources: "Kaynakları yenile",
  sourcesRefreshed: "Kaynaklar yenilendi; metniniz korundu. Gözlemleri yeniden inceleyin.",
  conflictRecovered: "Başka işlemdeki kayıt korundu; metniniz ayrı bir taslağa kaydedildi. Kaynakları yeniden inceleyin.",
  failed: "İşlem tamamlanamadı; taslağınız ekranda korunuyor.",
  draft: "Taslak",
  close: "Kapat",
} as const;
