import { useRef, useState } from "react";
import { KeyboardInput, KeyboardTextarea } from "../../mobile";
import { civilDateInIstanbul } from "../../core/domain/attendance.ts";
import { resolveActiveClassroomScope } from "../../core/domain/classroom-scope.ts";
import { adminLedgerHead, classroomAdminRecords, handoverState, inventoryBalances, missingHandoverSources, staleHandoverItems, type ClassroomAdminRecord, type ClassroomAdminWorkflow, type InventoryAction } from "../../core/domain/classroom-admin.ts";
import type { DataSnapshot } from "../../core/domain/model.ts";
import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { teacherFollowups } from "../../core/domain/teacher-followup.ts";
import { useTeacherFollowupSnapshot } from "../teacher-followup/TeacherFollowupWorkspace.tsx";
import { requestPdfDocument } from "../documents/pdf-preview-model.ts";
import { appendClassroomAdmin, buildHandoverItems } from "./classroom-admin-service.ts";
import { classroomHandoverPdf, classroomInventoryPdf, inventoryPartyName } from "./classroom-admin-document.ts";
import "./classroom-admin.css";

const clean = (s: string) => s.normalize("NFC").trim();
const labels: Record<InventoryAction, string> = { add: "Stok ekle", consume: "Kullan / tüket", loan: "Emanet ver", return: "İade al", damage: "Hasarlıya ayır", repair: "Onarıldı / kullanıma döndü" };
type Save = (w: ClassroomAdminWorkflow) => Promise<boolean>;
type Scope = { academicYearId: string; classroomId: string };
export function ClassroomAdminWorkspace({ store, initialSection = "inventory", refreshKey, disabled, onChanged }: { store: LocalDataStore; initialSection?: "inventory" | "handover"; refreshKey?: unknown; disabled?: boolean; onChanged?(): void }) {
  const { snapshot, error, reload, refresh } = useTeacherFollowupSnapshot(store, refreshKey);
  const openedScope = useRef<string | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [failure, setFailure] = useState("");
  const scope = snapshot ? resolveActiveClassroomScope(snapshot) : null;
  if (scope && !openedScope.current) openedScope.current = `${scope.academicYearId}:${scope.classroomId}`;
  const changedScope = !!scope && openedScope.current !== `${scope.academicYearId}:${scope.classroomId}`;
  const today = civilDateInIstanbul(new Date());
  const records = snapshot && scope ? classroomAdminRecords(snapshot, scope) : [];
  const save: Save = async workflow => {
    if (busy || disabled || !scope || changedScope) return false;
    setBusy(true); setFailure(""); setMessage("");
    try { await appendClassroomAdmin(store, { workflow, expectedScope: scope, expectedHead: adminLedgerHead(records) }); await refresh(); onChanged?.(); setMessage("Defter kaydı kaydedildi."); return true; }
    catch (e) { setFailure(e instanceof Error ? e.message : "Kaydedilemedi. Önceki kayıtlar korundu."); reload(); return false; }
    finally { setBusy(false); }
  };
  const preview = async (task: () => Promise<unknown>) => { setFailure(""); try { await task(); } catch (e) { setFailure(e instanceof Error ? e.message : "Belge hazırlanamadı."); } };
  if (error) return <p role="alert">{error}<button type="button" onClick={reload}>Yeniden dene</button></p>;
  if (!snapshot) return <p role="status">Sınıf defteri hazırlanıyor…</p>;
  if (!scope) return <p>Bu defter için önce sınıfınızı hazırlayın.</p>;
  if (changedScope) return <p role="alert">Etkin sınıf değişti. Çalışma alanını kapatıp yeniden açın; önceki sınıfın taslağı yeni sınıfa kaydedilmez.</p>;
  const locked = !!disabled || busy || snapshot.academicYears.find(y => y.id === scope.academicYearId)?.status === "archived";
  return <div className="classroom-admin" data-testid="classroom-admin-workspace">
    {failure ? <p role="alert" className="admin-error">{failure}</p> : null}{message ? <p role="status" className="admin-success">{message}</p> : null}
    {initialSection === "inventory" ? <InventoryPanel snapshot={snapshot} scope={scope} records={records} today={today} disabled={locked} save={save} preview={() => preview(() => requestPdfDocument(classroomInventoryPdf(snapshot, scope, today)))} /> : <HandoverPanel snapshot={snapshot} scope={scope} records={records} today={today} disabled={locked} save={save} preview={id => preview(() => requestPdfDocument(classroomHandoverPdf(snapshot, scope, id)))} />}
  </div>;
}
function InventoryPanel({ snapshot, scope, records, today, disabled, save, preview }: { snapshot: DataSnapshot; scope: Scope; records: ClassroomAdminRecord[]; today: string; disabled: boolean; save: Save; preview(): Promise<void> }) {
  const [name, setName] = useState(""), [category, setCategory] = useState(""), [unit, setUnit] = useState("adet"), [initial, setInitial] = useState("0");
  const [selected, setSelected] = useState(""), [action, setAction] = useState<InventoryAction>("loan"), [quantity, setQuantity] = useState("1");
  const [party, setParty] = useState(""), [adult, setAdult] = useState(""), [due, setDue] = useState(today), [loanId, setLoanId] = useState(""), [note, setNote] = useState(""), [preparation, setPreparation] = useState("");
  const [reversalId, setReversalId] = useState(""), [reason, setReason] = useState("");
  const balances = inventoryBalances(records), balance = balances.find(b => b.item.id === selected);
  const students = snapshot.students.filter(s => s.academicYearId === scope.academicYearId && s.classroomId === scope.classroomId && s.active !== false && typeof s.deletedAt !== "string");
  const preparations = teacherFollowups(snapshot).filter(r => r.academicYearId === scope.academicYearId && r.classroomId === scope.classroomId && r.workflow.kind === "preparation-list");
  const reversed = new Set(records.flatMap(r => r.workflow.kind === "inventory-reversal" ? [r.workflow.sourceId] : []));
  const movement = async () => { if (await save({ kind: "inventory-movement", itemId: selected, action, quantity: Number(quantity), party: action === "loan" ? party === "adult" ? { type: "adult", studentId: null, name: clean(adult) } : { type: "student", studentId: party, name: "" } : null, dueOn: action === "loan" ? due : null, loanId: action === "return" ? loanId : null, note: clean(note), preparationId: preparation || null })) { setNote(""); setQuantity("1"); } };
  return <>
    <div className="admin-lead"><span className="admin-eyebrow">SINIF DÜZENİ</span><h2>Malzeme ve emanet</h2><p>Elinizde olanı, kullanımda olanı ve geri gelecek malzemeyi ayrı izleyin.</p></div>
    <div className="admin-summary"><span><strong>{balances.length}</strong> malzeme çeşidi</span><span><strong>{balances.flatMap(b => b.loans.filter(l => l.remaining > 0)).length}</strong> açık emanet</span></div>
    <details className="admin-card"><summary>Yeni malzeme ekle</summary><form onSubmit={e => { e.preventDefault(); void (async () => { if (await save({ kind: "inventory-item", name: clean(name), category: clean(category), unit: clean(unit), initialQuantity: Number(initial), note: "" })) { setName(""); setInitial("0"); } })(); }}><fieldset disabled={disabled}><label>Malzeme adı<KeyboardInput value={name} onChange={e => setName(e.target.value)} required maxLength={200} /></label><div className="admin-grid"><label>Kategori<KeyboardInput value={category} onChange={e => setCategory(e.target.value)} maxLength={120} placeholder="Kitap, sanat, oyun…" /></label><label>Birim<select value={unit} onChange={e => setUnit(e.target.value)}>{["adet", "kitap", "paket", "kutu", "set", "rulo"].map(s => <option key={s}>{s}</option>)}</select></label></div><label>Başlangıç miktarı<KeyboardInput type="number" inputMode="numeric" min="0" max="1000000" step="1" value={initial} onChange={e => setInitial(e.target.value)} required /></label><button type="submit" className="admin-primary">Malzemeyi kaydet</button></fieldset></form></details>
    {balances.length ? <><label>Malzeme seç<select value={selected} onChange={e => { setSelected(e.target.value); setLoanId(""); setReversalId(""); }}><option value="">Malzeme seçin</option>{balances.map(b => <option key={b.item.id} value={b.item.id}>{b.item.workflow.name} · {b.available} {b.item.workflow.unit} kullanılabilir</option>)}</select></label><button type="button" onClick={() => void preview()}>Malzeme defteri · PDF</button></> : <p className="admin-empty">Henüz malzeme yok. İlk kayıtta fiziksel sayımınızdaki miktarı girin.</p>}
    {balance ? <><section className="admin-card"><h3>{balance.item.workflow.name}</h3><div className="admin-stock-grid">{[["Toplam", balance.owned], ["Kullanılabilir", balance.available], ["Emanet", balance.onLoan], ["Hasarlı", balance.damaged]].map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span><small>{balance.item.workflow.unit}</small></div>)}</div></section>
      <form className="admin-card" onSubmit={e => { e.preventDefault(); void movement(); }}><h3>Hareket kaydet</h3><fieldset disabled={disabled}><div className="admin-grid"><label>İşlem<select value={action} onChange={e => setAction(e.target.value as InventoryAction)}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Miktar ({balance.item.workflow.unit})<KeyboardInput type="number" min="1" max="1000000" step="1" inputMode="numeric" value={quantity} onChange={e => setQuantity(e.target.value)} required /></label></div>
      {action === "loan" ? <><label>Emanet alan<select value={party} onChange={e => setParty(e.target.value)} required><option value="">Kişi seçin</option>{students.map(s => <option key={s.id} value={s.id}>{String(s.displayName)}</option>)}<option value="adult">Öğretmen / diğer yetişkin</option></select></label>{party === "adult" ? <label>Yetişkin adı soyadı<KeyboardInput value={adult} onChange={e => setAdult(e.target.value)} required maxLength={200} /></label> : null}<label>Beklenen iade tarihi<KeyboardInput type="date" min={today} value={due} onChange={e => setDue(e.target.value)} required /></label></> : null}
      {action === "return" ? <label>İade alınacak emanet<select value={loanId} onChange={e => setLoanId(e.target.value)} required><option value="">Emanet seçin</option>{balance.loans.filter(l => l.remaining > 0).map(l => <option key={l.record.id} value={l.record.id}>{inventoryPartyName(snapshot, l.record.workflow.kind === "inventory-movement" ? l.record.workflow.party : null)} · kalan {l.remaining}</option>)}</select></label> : null}
      <label>Haftalık hazırlık bağlantısı<select value={preparation} onChange={e => setPreparation(e.target.value)}><option value="">Bağlantı yok</option>{preparations.map(p => <option key={p.id} value={p.id}>{p.workflow.kind === "preparation-list" ? `${p.workflow.weekStart} · ${p.workflow.items.length} hazırlık maddesi` : ""}</option>)}</select></label><label>Hareket notu<KeyboardTextarea value={note} onChange={e => setNote(e.target.value)} maxLength={4000} rows={2} /></label><button type="submit" className="admin-primary">Hareketi kaydet</button></fieldset></form>
      {balance.loans.some(l => l.remaining > 0) ? <section className="admin-card"><h3>İade bekleyenler</h3>{balance.loans.filter(l => l.remaining > 0).map(l => <div className="admin-row" key={l.record.id}><span><strong>{inventoryPartyName(snapshot, l.record.workflow.kind === "inventory-movement" ? l.record.workflow.party : null)}</strong><small>{l.remaining} {balance.item.workflow.unit} · {l.record.workflow.kind === "inventory-movement" ? l.record.workflow.dueOn : ""}</small></span><button type="button" disabled={disabled} onClick={() => { setAction("return"); setLoanId(l.record.id); setQuantity(String(l.remaining)); }}>İade hazırla</button></div>)}</section> : null}
      <details className="admin-card"><summary>Hareket ve düzeltme geçmişi</summary>{records.filter(r => r.workflow.kind === "inventory-movement" && r.workflow.itemId === selected).slice().reverse().map(r => r.workflow.kind === "inventory-movement" ? <div className="admin-history" key={r.id}><strong>{labels[r.workflow.action]} · {r.workflow.quantity} {balance.item.workflow.unit}</strong><small>{r.civilDate} · {reversed.has(r.id) ? "Gerekçeyle geri alındı" : "Kayıt geçerli"}</small>{r.workflow.note ? <p>{r.workflow.note}</p> : null}{reversed.has(r.id) ? <p>{records.find(e => e.workflow.kind === "inventory-reversal" && e.workflow.sourceId === r.id)?.workflow.kind === "inventory-reversal" ? (records.find(e => e.workflow.kind === "inventory-reversal" && e.workflow.sourceId === r.id)!.workflow as Extract<ClassroomAdminWorkflow, {kind: "inventory-reversal"}>).note : ""}</p> : <button type="button" disabled={disabled} onClick={() => { setReversalId(r.id); setReason(""); }}>Gerekçeli geri alma</button>}</div> : null)}
      {reversalId ? <form onSubmit={e => { e.preventDefault(); void (async () => { if (await save({ kind: "inventory-reversal", sourceId: reversalId, note: clean(reason) })) setReversalId(""); })(); }}><label>Geri alma gerekçesi<KeyboardTextarea value={reason} onChange={e => setReason(e.target.value)} required maxLength={4000} /></label><p>Bu işlem stok hesabını yeniden yapar. Bağlı iade veya sonraki tüketim varsa önce ilgili hareket düzeltilmelidir.</p><button type="submit" disabled={disabled}>Gerekçeyle geri al</button><button type="button" onClick={() => setReversalId("")}>Vazgeç</button></form> : null}</details></> : null}
  </>;
}
function HandoverPanel({ snapshot, scope, records, today, disabled, save, preview }: { snapshot: DataSnapshot; scope: Scope; records: ClassroomAdminRecord[]; today: string; disabled: boolean; save: Save; preview(id: string): Promise<void> }) {
  const [title, setTitle] = useState("Dönem sonu sınıf devri"), [recipient, setRecipient] = useState(""), [due, setDue] = useState(today), [manual, setManual] = useState("Sınıf anahtarları ve dolap düzeni\nBasılı sınıf dosyası\nDijital yedeğin teslim kontrolü"), [note, setNote] = useState("");
  const [selected, setSelected] = useState(""), [reason, setReason] = useState("");
  const plans = records.filter(r => r.workflow.kind === "handover-plan"), state = handoverState(records, selected), missing = state ? missingHandoverSources(snapshot, scope, state.items) : [], stale = staleHandoverItems(snapshot, records, selected), completedCount = (state?.completedCount ?? 0) - stale.length;
  return <><div className="admin-lead"><span className="admin-eyebrow">EĞİTİM YILI KAPANIŞI</span><h2>Dönem sonu devir</h2><p>Açık takipler, emanetler ve teslim edilecek dosyalar tek kontrol listesinde.</p></div>
    <details className="admin-card"><summary>Devir listesi oluştur</summary><form onSubmit={e => { e.preventDefault(); void (async () => { const items = buildHandoverItems(snapshot, scope, manual.split("\n")); if (await save({ kind: "handover-plan", title: clean(title), recipient: clean(recipient), dueOn: due, note: clean(note), items })) setNote(""); })(); }}><fieldset disabled={disabled}><label>Devir başlığı<KeyboardInput value={title} onChange={e => setTitle(e.target.value)} required maxLength={200} /></label><label>Teslim alacak kişi / görev<KeyboardInput value={recipient} onChange={e => setRecipient(e.target.value)} required maxLength={200} /></label><label>Hedef devir tarihi<KeyboardInput type="date" value={due} onChange={e => setDue(e.target.value)} required /></label><label>Ek kontrol maddeleri · her satıra bir madde<KeyboardTextarea value={manual} onChange={e => setManual(e.target.value)} rows={4} maxLength={10000} /></label><p>Açık veli / eğitim / uyum takipleri, haftalık hazırlıklar ve henüz dönmeyen emanetler otomatik eklenir.</p><label>Devir notu<KeyboardTextarea value={note} onChange={e => setNote(e.target.value)} rows={2} maxLength={4000} /></label><button type="submit" className="admin-primary">Devir listesini kaydet</button></fieldset></form></details>
    {plans.length ? <label>Devir listesi<select value={selected} onChange={e => { setSelected(e.target.value); setReason(""); }}><option value="">Liste seçin</option>{plans.map(p => <option key={p.id} value={p.id}>{p.workflow.kind === "handover-plan" ? p.workflow.title : ""} · {handoverState(records, p.id)?.closed ? "tamamlandı" : "açık"}</option>)}</select></label> : <p className="admin-empty">Bir devir listesi oluşturarak açık işleri ve teslim edilecekleri kayda alın.</p>}
    {state && state.source.workflow.kind === "handover-plan" ? <><section className="admin-card"><h3>{state.source.workflow.title}</h3><p>{state.source.workflow.recipient} · {state.source.workflow.dueOn}</p><div className="admin-progress"><progress value={completedCount} max={state.items.length} /><strong>{completedCount} / {state.items.length} kontrol edildi</strong></div><p>Bir maddeyi işaretlemek kaynak takibi veya emaneti kapatmaz; devredilecek işin gözden geçirildiğini kaydeder.</p>
      {state.items.map(i => <label className="admin-check" key={i.id}><KeyboardInput type="checkbox" checked={state.checked(i) && !stale.some(s => s.id === i.id)} disabled={disabled || !!state.closed} onChange={e => void save({ kind: "handover-check", handoverId: selected, itemId: i.id, completed: e.target.checked, note: "" })} /><span><strong>{i.title}</strong>{stale.some(s => s.id === i.id) ? <small>Kaynak işleminden sonra yeniden kontrol edin</small> : null}{i.studentId ? <small>{String(snapshot.students.find(s => s.id === i.studentId)?.displayName ?? "Çocuk")}</small> : null}<small>{i.sourceKind === "manual" ? "Elle eklenen madde" : i.sourceKind === "loan" ? "Emanet kaydına bağlı" : "Öğretmen takibine bağlı"}</small></span></label>)}
      {!state.closed && missing.length ? <div className="admin-notice"><p>{missing.length} yeni açık iş liste dışında. Tamamlamadan önce listeye ekleyin.</p><button type="button" disabled={disabled} onClick={() => void save({ kind: "handover-revision", handoverId: selected, items: buildHandoverItems(snapshot, scope, [], state.items), note: "Yeni açık işler devir listesine eklendi." })}>Yeni açık işleri ekle</button></div> : null}
      {state.closed ? <><p className="admin-success">Devir kaydı {state.closed.civilDate} tarihinde tamamlandı.</p><label>Yeniden açma gerekçesi<KeyboardTextarea value={reason} onChange={e => setReason(e.target.value)} maxLength={4000} /></label><button type="button" disabled={disabled || !clean(reason)} onClick={() => void save({ kind: "handover-reopen", handoverId: selected, note: clean(reason) })}>Gerekçeyle yeniden aç</button></> : <button className="admin-primary" type="button" disabled={disabled || missing.length > 0 || completedCount !== state.items.length} onClick={() => void save({ kind: "handover-close", handoverId: selected, recipient: state.source.workflow.kind === "handover-plan" ? state.source.workflow.recipient : "", note: "Tüm maddeler gözden geçirilerek devir tamamlandı." })}>Devir kaydını tamamla</button>}
      <button type="button" onClick={() => void preview(selected)}>Devir tutanağı · PDF</button></section><details className="admin-card"><summary>Devir işlem geçmişi</summary>{state.history.slice().reverse().map(r => <p key={r.id}>{r.civilDate} · {({ "handover-plan": "Liste oluşturuldu", "handover-revision": "Açık işler eklendi", "handover-check": "Madde kontrolü güncellendi", "handover-close": "Devir tamamlandı", "handover-reopen": "Devir yeniden açıldı" } as Record<string, string>)[r.workflow.kind]}{"note" in r.workflow && r.workflow.note ? ` · ${r.workflow.note}` : ""}</p>)}</details></> : null}
  </>;
}
