import type { LocalDataStore } from "../../core/repository/contracts.ts";
import { canonicalJson } from "../../core/backup/canonical-json.ts";
import { activeSchoolDocumentTemplate } from "../../core/domain/school-document-template.ts";
import { isDocumentVersionRecord } from "../../core/domain/document-history.ts";
import { createSchoolStyledPdf } from "../school-document-template/school-document-template-pdf.ts";
import { documentVersionFile } from "../documents/document-history-service.ts";
import { createBinaryZip } from "../documents/binary-zip.ts";
import { TEACHER_DOCUMENT_THEME, TEACHER_PRINT_THEME } from "../documents/document-theme.ts";
import { validatePdfSelection, type PdfPreviewRecipe, type PdfPreviewSelection } from "../documents/pdf-preview-model.ts";
import type { SemanticPdfNode, SemanticTaggedPdfRuntime } from "../documents/semantic-tagged-pdf.ts";
import { teacherReportModel,reportExecutiveSummary,REPORT_PERIODS,REPORT_FIELDS,type ReportInput,type TeacherReportModel,type ReportRow } from "./teacher-report-model.ts";

export function reportRowsForSelection(model:TeacherReportModel,selection:PdfPreviewSelection){
 const chosen=new Set(selection.studentIds??[]),all=model.students.every(s=>chosen.has(s.id));
 const rows=model.rows.filter(r=>selection.fields.includes(r.id)&&r.date>=selection.periodStart!&&r.date<=selection.periodEnd!&&(r.studentIds.length?r.studentIds.every(id=>chosen.has(id)):all));
 if(!rows.length)throw new Error("Bu çocuk ve dönem seçiminde kayıt kalmadı.");return rows;
}
export function reportNodes(model:TeacherReportModel,rows:readonly ReportRow[]):SemanticPdfNode[]{
 const nodes:SemanticPdfNode[]=[{kind:"heading",level:1,text:`${REPORT_PERIODS.find(p=>p.id===model.input.period)!.label} öğretmen dosyası`},{kind:"paragraph",tone:"meta",text:`${model.schoolName} · ${model.classroomName}\n${model.period.start} — ${model.period.end}\n${model.teacherName} · Okul Öncesi Öğretmeni`},{kind:"paragraph",text:"Bu dosya seçilmiş gerçek kaynakların çalışma özetidir. Ek 4 Beceri Edinim Raporu veya Ek 18 Aylık Plan Kontrol Çizelgesi yerine geçmez. Planlama, uygulama, gözlem ve öğretmen değerlendirmesi ayrı kayıtlardır."}];
 const executive=model.input.period==="term"||model.input.period==="year";if(executive){nodes.push({kind:"heading",level:2,text:"Yönetici özeti"},...reportExecutiveSummary(rows).map(text=>({kind:"paragraph" as const,text})),{kind:"heading",level:2,text:"Ekler · Numaralı tam kaynaklar"});}let sourceNumber=0;
 for(const category of REPORT_FIELDS){const matches=rows.filter(r=>r.category===category.id);nodes.push({kind:"heading",level:2,text:`${category.label} · ${matches.length} kayıt`});if(!matches.length)nodes.push({kind:"paragraph",text:"Bu bölüm için seçilmiş kaynak kaydı yok."});for(const row of matches)nodes.push({kind:"paragraph",tone:"meta",text:`${row.date} · ${row.status} · ${row.studentNames||"Seçili sınıf"}`},{kind:"paragraph",text:`${executive?`${++sourceNumber}. `:""}${row.title}\n${row.text}`});}
 nodes.push({kind:"paragraph",text:`${model.teacherName}\nOkul Öncesi Öğretmeni\nİmza: ____________________`});return nodes;
}
export async function createTeacherReportRecipe(store:LocalDataStore,input:ReportInput,options:{recordIds?:readonly string[];attachmentIds?:readonly string[];runtime?:SemanticTaggedPdfRuntime}={}):Promise<PdfPreviewRecipe>{
 const snapshot=await store.readSnapshot(),base=teacherReportModel(snapshot,input),fixed={...input,studentIds:[...base.input.studentIds]};
 const model={...base,rows:options.recordIds?base.rows.filter(r=>options.recordIds!.includes(r.id)):base.rows};
 if(options.recordIds?.some(id=>!base.rows.some(r=>r.id===id)))throw new Error("Seçilen kaynak kaydı artık bu kapsamda bulunmuyor.");
 if(!model.rows.length)throw new Error("Önce dosyaya alınacak gerçek kayıtları seçin.");
 const template=activeSchoolDocumentTemplate(snapshot,model.scope),expected=canonicalJson({model,template});
 const attachments=snapshot.settings.filter(isDocumentVersionRecord).filter(r=>options.attachmentIds?.includes(r.id)&&!r.deletedAt&&r.classroomId===model.scope.classroomId&&r.academicYearId===model.scope.academicYearId&&r.studentIds.every(id=>fixed.studentIds.includes(id))&&r.selection.periodStart!>=model.period.start&&r.selection.periodEnd!<=model.period.end);
 if(new Set(options.attachmentIds??[]).size!==attachments.length)throw new Error("Paket ekleri seçili çocuk ve dönem kapsamında olmalıdır.");
 const assertExportAllowed=async()=>{const fresh=await store.readSnapshot(),currentBase=teacherReportModel(fresh,fixed),current={...currentBase,rows:options.recordIds?currentBase.rows.filter(r=>options.recordIds!.includes(r.id)):currentBase.rows};if(canonicalJson({model:current,template:activeSchoolDocumentTemplate(fresh,model.scope)})!==expected||attachments.some(a=>canonicalJson(fresh.settings.find(r=>r.id===a.id))!==canonicalJson(a)))throw new Error("Raporun kaynakları değişti. Aynı seçimlerle güncelleyin.");};
 const name=`MaarifOS_Ogretmen_Dosyasi_${input.period}_${model.period.start}_${model.period.end}`;
 const recipe:PdfPreviewRecipe={title:`Öğretmen dosyası · ${REPORT_PERIODS.find(p=>p.id===input.period)!.label}`,description:"Seçili kaynaklar aynı PDF, Word, Excel ve ZIP dosyasını besler. Kaynak metni kesilmez; uzun kapsam devam sayfalarına taşar.",supportsAppearance:true,printEnabled:true,students:model.students.filter(s=>fixed.studentIds.includes(s.id)),fields:model.rows.map(r=>({id:r.id,label:`${r.date} · ${r.status} · ${r.title}`})),period:{min:model.period.start,max:model.period.end},initial:{fields:model.rows.map(r=>r.id),studentIds:fixed.studentIds,periodStart:model.period.start,periodEnd:model.period.end},assertExportAllowed,
 refresh:()=>createTeacherReportRecipe(store,fixed,options),
 async build(selection){validatePdfSelection(recipe,selection);await assertExportAllowed();const rows=reportRowsForSelection(model,selection);if(!rows.length)throw new Error("Bu çocuk ve dönem seçiminde kayıt kalmadı.");const outputModel={...model,period:{start:selection.periodStart!,end:selection.periodEnd!}};const bytes=await createSchoolStyledPdf({title:recipe.title,language:"tr-TR",orientation:input.period==="week"?"landscape":"portrait",pageMargin:36,theme:selection.appearance==="ink-saving"?TEACHER_PRINT_THEME:TEACHER_DOCUMENT_THEME,nodes:reportNodes(outputModel,rows),includeTotalPages:true,artifactFooterText:"MaarifOS · Öğretmen dosyası"},template,{teacherName:model.teacherName,includeSignature:false},options.runtime);await assertExportAllowed();return{bytes,fileName:name+".pdf",mimeType:"application/pdf"};},
 exportActions:[{id:"word",label:"Word indir",async build(selection){validatePdfSelection(recipe,selection);await assertExportAllowed();const {createTeacherReportWord}=await import("./teacher-report-word.ts");await assertExportAllowed();return{bytes:createTeacherReportWord(reportNodes({...model,period:{start:selection.periodStart!,end:selection.periodEnd!}},reportRowsForSelection(model,selection)),{landscape:input.period==="week",teacherName:model.teacherName}),fileName:name+".docx",mimeType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"};}},{id:"excel",label:"Excel indir",async build(selection){validatePdfSelection(recipe,selection);await assertExportAllowed();const {teacherReportSpreadsheet}=await import("./teacher-report-spreadsheet.ts");await assertExportAllowed();return{bytes:teacherReportSpreadsheet({...model,period:{start:selection.periodStart!,end:selection.periodEnd!}},reportRowsForSelection(model,selection)),fileName:name+".xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"};}},{id:"zip",label:"Seçili eklerle dosya paketini indir",async build(selection){validatePdfSelection(recipe,selection);await assertExportAllowed();const files=await Promise.all([recipe.build(selection),...recipe.exportActions!.filter(a=>a.id!=="zip").map(a=>a.build(selection))]);const chosen=attachments.filter(a=>a.studentIds.every(id=>selection.studentIds!.includes(id))&&a.selection.periodStart!>=selection.periodStart!&&a.selection.periodEnd!<=selection.periodEnd!);for(const a of chosen)files.push(await documentVersionFile(a));await assertExportAllowed();const index=[recipe.title,model.schoolName,model.teacherName,`${selection.periodStart} — ${selection.periodEnd}`,"İçindekiler",...files.map((f,i)=>`${i+1}. ${f.fileName}`)].join("\n");const cover=await createSchoolStyledPdf({title:"Öğretmen dosyası kapak ve içindekiler",language:"tr-TR",orientation:"portrait",pageMargin:40,nodes:[{kind:"heading",level:1,text:recipe.title},{kind:"paragraph",text:index}],includeTotalPages:true},template,{teacherName:model.teacherName},options.runtime);await assertExportAllowed();return{bytes:createBinaryZip([{name:"00_Kapak_ve_Icindekiler.pdf",bytes:cover},{name:"00_Icindekiler.txt",bytes:new TextEncoder().encode(index)},...files.map((f,i)=>({name:`${String(i+1).padStart(2,"0")}_${f.fileName}`,bytes:f.bytes}))]),mimeType:"application/zip",fileName:name+".zip"};}}]};return recipe;
}
