import {resolveActiveClassroomScope} from "../../core/domain/classroom-scope.ts";
import {lazy,Suspense,useEffect,useRef,useState} from "react";
import type {LocalDataStore} from "../../core/repository/contracts.ts";
import type {DataSnapshot} from "../../core/domain/model.ts";
import {civilDateInIstanbul} from "../../core/domain/attendance.ts";
import {isDocumentVersionRecord} from "../../core/domain/document-history.ts";
import {KeyboardInput} from "../../mobile";
import {requestPdfDocument} from "../documents/pdf-preview-model.ts";
import {completeTeacherAssessments} from "../evidence/teacher-assessment-completion.ts";
import {teacherReportModel,REPORT_PERIODS,REPORT_FIELDS,type ReportPeriod,type TeacherReportModel} from "./teacher-report-model.ts";
import "./teacher-report-center.css";
const WorkPackageCenter=lazy(()=>import("../work-packages/WorkPackageCenter.tsx").then(m=>({default:m.WorkPackageCenter})));
export interface TeacherReportCenterPanelProps{store:LocalDataStore;refreshKey?:string|number;disabled?:boolean;onChanged?:()=>void;onOpenPlan?:(planId:string)=>void;onPreparePlan?:(civilDate:string)=>void;onOpenObservation?:(observationId:string)=>void;onOpenCapture?:()=>void;onOpenAssessment?:(civilDate:string)=>void;onOpenStudentReport?:(studentId:string)=>void;onOpenMonthlyEvaluation?:(monthlyPlanId:string)=>void;onOpenHistory?:()=>void;}
export function TeacherReportCenterPanel(props:TeacherReportCenterPanelProps){
 const {store,refreshKey,disabled=false}=props;
 const [snapshot,setSnapshot]=useState<DataSnapshot|null>(null),[period,setPeriod]=useState<ReportPeriod>("month"),[day,setDay]=useState(civilDateInIstanbul(new Date())),[termStart,setTermStart]=useState(""),[termEnd,setTermEnd]=useState(""),[children,setChildren]=useState<string[]|undefined>(),[selected,setSelected]=useState<string[]|null>(null),[assessments,setAssessments]=useState<string[]>([]),[attachments,setAttachments]=useState<string[]>([]),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[linkId,setLinkId]=useState("");
 const rememberedScope=useRef(""),generation=useRef(0),guard=useRef(false),disabledRef=useRef(disabled);disabledRef.current=disabled;
 useEffect(()=>{const token=++generation.current;setLoading(true);store.readSnapshot().then(value=>{if(token===generation.current){setSnapshot(value);const active=resolveActiveClassroomScope(value);const key=String(active?.academicYearId)+"/"+String(active?.classroomId);if(key!==rememberedScope.current){rememberedScope.current=key;setChildren(undefined);setSelected(null);setAssessments([]);setAttachments([]);setLinkId("");const previous=value.settings.filter(isDocumentVersionRecord).filter(r=>!r.deletedAt&&r.classroomId===active?.classroomId&&r.academicYearId===active?.academicYearId&&r.title.startsWith("Öğretmen dosyası · ")).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))[0];if(previous){const remembered=REPORT_PERIODS.find(p=>previous.title.endsWith(p.label));if(remembered)setPeriod(remembered.id);if(previous.selection.periodStart)setDay(previous.selection.periodStart);setChildren(previous.studentIds.filter(id=>value.students.some(s=>s.id===id&&!s.deletedAt)));setSelected([...previous.selection.fields]);if(remembered?.id==="term"){setTermStart(previous.selection.periodStart??"");setTermEnd(previous.selection.periodEnd??"");}}}setLoading(false);}}).catch(()=>{if(token===generation.current){setError("Rapor kaynakları okunamadı. Yenileyin.");setLoading(false);}});return()=>{generation.current++;};},[store,refreshKey,revision]);
 let model:TeacherReportModel|null=null,modelError="";if(snapshot)try{model=teacherReportModel(snapshot,{period,day,studentIds:children,termStart,termEnd});}catch(e){modelError=e instanceof Error?e.message:"Rapor dönemi geçersiz.";}
 const selectedRows=selected??model?.rows.map(r=>r.id)??[],locked=disabled||loading||busy;
 const change=()=>{setRevision(v=>v+1);try{props.onChanged?.();}catch{setMessage("Kayıt tamamlandı; güncel raporu yeniden açabilirsiniz.");}};
 const switchPeriod=(value:ReportPeriod)=>{setPeriod(value);setSelected(null);setAttachments([]);setAssessments([]);};
 async function openReport(){if(!model||locked||guard.current)return;guard.current=true;setBusy(true);setError("");const token=generation.current;try{const {createTeacherReportRecipe}=await import("./teacher-report-document.ts");const recipe=await createTeacherReportRecipe(store,model.input,{recordIds:selectedRows,attachmentIds:attachments});if(token!==generation.current||disabledRef.current)throw new Error("Kaynak kapsamı değişti; güncel seçimi yeniden açın.");await requestPdfDocument(recipe);}catch(e){setError(e instanceof Error?e.message:"Rapor hazırlanamadı.");}finally{guard.current=false;setBusy(false);}}
 async function saveAssessments(){if(!snapshot||locked||guard.current||!assessments.length)return;guard.current=true;setBusy(true);setError("");try{await completeTeacherAssessments(store,{snapshot,ids:assessments});setMessage("Seçtiğiniz kendi değerlendirmeleriniz kaydedildi.");setAssessments([]);change();}catch(e){setError(e instanceof Error?e.message:"Değerlendirme kaydedilemedi.");}finally{guard.current=false;setBusy(false);}}
 const toggle=(values:string[],id:string)=>values.includes(id)?values.filter(v=>v!==id):[...values,id];
 const versions=snapshot&&model?snapshot.settings.filter(isDocumentVersionRecord).filter(r=>!r.deletedAt&&r.classroomId===model.scope.classroomId&&r.academicYearId===model.scope.academicYearId&&r.studentIds.every(id=>model.input.studentIds.includes(id))&&r.selection.periodStart!>=model.period.start&&r.selection.periodEnd!<=model.period.end):[];
 return <section className="teacher-report-center" aria-label="İdare ve öğretmen dosyası"><h2>İdare ve öğretmen dosyası</h2><p>Dönemi ve gerçek kaynakları seçin. Aynı kapsamı PDF, Word, Excel veya ekleriyle ZIP olarak alın.</p><div className="teacher-report-periods" aria-label="Rapor dönemi">{REPORT_PERIODS.map(p=><button type="button" key={p.id} disabled={locked} aria-pressed={period===p.id} onClick={()=>switchPeriod(p.id)}>{p.label}</button>)}</div><label>Rapor tarihi<KeyboardInput type="date" value={day} disabled={locked} onChange={e=>{setDay(e.target.value);setSelected(null);setAttachments([]);}}/></label>{period==="term"&&<details><summary>Dönem sınırlarını seç</summary><label>Dönem başlangıcı<KeyboardInput type="date" value={termStart} disabled={locked} onChange={e=>setTermStart(e.target.value)}/></label><label>Dönem bitişi<KeyboardInput type="date" value={termEnd} disabled={locked} onChange={e=>setTermEnd(e.target.value)}/></label></details>}
 {model&&<><p><strong>{model.period.start} — {model.period.end}</strong> · {model.classroomName}</p><details><summary>Çocuk kapsamı · {model.input.studentIds.length} çocuk</summary>{model.students.map(s=><label className="teacher-report-choice" key={s.id}><input type="checkbox" checked={model!.input.studentIds.includes(s.id)} disabled={locked} onChange={()=>{setChildren(toggle(model!.input.studentIds,s.id));setSelected(null);setAttachments([]);setAssessments([]);}}/>{s.label}</label>)}</details>
 <div aria-label="Gerçek kayıt özeti">{REPORT_FIELDS.map(c=><p key={c.id}>{c.label}: {model!.rows.filter(r=>r.category===c.id&&selectedRows.includes(r.id)).length} seçili kayıt</p>)}</div>
 <details><summary>Dosyaya alınacak kayıtları seç · {selectedRows.length}</summary>{model.rows.map(r=><label key={r.id} className="teacher-report-choice"><input type="checkbox" checked={selectedRows.includes(r.id)} disabled={locked} onChange={()=>setSelected(toggle(selectedRows,r.id))}/><span>{r.date} · {r.status} · {r.studentNames}<strong>{r.title}</strong><span>{r.text}</span></span></label>)}</details>
 {!model.rows.length&&<p>Bu dönem ve çocuk seçiminde uygun kaynak yok.</p>}
 {model.unlinked.slice(0,3).map(r=><button type="button" key={r.id} disabled={locked} onClick={()=>setLinkId(r.sourceId)}>Gözlemin yerini seç · {r.date}</button>)}
 {linkId&&<Suspense fallback={<p>Kaynak seçenekleri hazırlanıyor…</p>}><WorkPackageCenter store={store} refreshKey={`${refreshKey}:${revision}`} disabled={locked} observationId={linkId} mode="observations" onChanged={change} onOpenPlans={props.onOpenPlan} onOpenObservation={props.onOpenObservation}/></Suspense>}
 {model.pending.length>0&&<fieldset><legend>Kendi yazdığım değerlendirmeyi kaydet</legend>{model.pending.map(r=><label className="teacher-report-choice" key={r.id}><input type="checkbox" disabled={locked} checked={assessments.includes(r.id)} onChange={()=>setAssessments(toggle(assessments,r.id))}/><span>{String(r.teacherAssessmentText)}</span></label>)}<button type="button" disabled={locked||!assessments.length} onClick={()=>void saveAssessments()}>Seçili değerlendirmelerimi kaydet</button></fieldset>}
 <details><summary>Hazır tamamlama ve resmî kaynaklar</summary>{props.onPreparePlan&&<button type="button" disabled={locked} onClick={()=>props.onPreparePlan?.(day)}>Bu güne plan hazırla</button>}{props.onOpenCapture&&<button type="button" disabled={locked} onClick={props.onOpenCapture}>Gerçek gözlem ekle</button>}{props.onOpenAssessment&&<button type="button" disabled={locked} onClick={()=>props.onOpenAssessment?.(day)}>Gün kapanışı ve ertesi gün notu</button>}{model.monthlyPlans.map(p=><button type="button" key={p.id} disabled={locked||!props.onOpenMonthlyEvaluation} onClick={()=>props.onOpenMonthlyEvaluation?.(p.id)}>Aylık değerlendirme ve Ek 18 · {String(p.monthKey)}</button>)}{model.students.filter(s=>model!.input.studentIds.includes(s.id)).map(s=><button type="button" key={s.id} disabled={locked||!props.onOpenStudentReport} onClick={()=>props.onOpenStudentReport?.(s.id)}>{s.label} için Ek 4 hazırlığını aç</button>)}<p>Ek 4 çocuk bazlı beceri edinimidir. Ek 18 aylık plan bileşenlerinin kontrolüdür; çocuk beceri puanı değildir.</p></details>
 {versions.length>0&&<details><summary>ZIP dosyasına kayıtlı ek seç · {attachments.length}</summary>{versions.map(v=><label key={v.id} className="teacher-report-choice"><input type="checkbox" disabled={locked} checked={attachments.includes(v.id)} onChange={()=>setAttachments(toggle(attachments,v.id))}/>{v.title} · {v.civilDate}</label>)}</details>}
 <button type="button" className="teacher-report-primary" disabled={locked||!selectedRows.length||!model.input.studentIds.length} onClick={()=>void openReport()}>{busy?"Dosya hazırlanıyor…":"Seçili kayıtlarla dosyayı aç"}</button><p>Önizlemede PDF paylaş, Yazdır, Word indir, Excel indir ve ZIP seçenekleri bulunur.</p></>}
 {(error||modelError)&&<p role="alert">{error||modelError}</p>}{message&&<p role="status">{message}</p>}<button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Rapor kaynaklarını yenile</button>{props.onOpenHistory&&<button type="button" onClick={props.onOpenHistory}>Önceki belge sürümlerini aç</button>}</section>;
}
